import { DefinitionTargetKind, defineSpec } from "@opencanon/core";

export default [
  defineSpec({
    id: "runtime-operations-spec",
    title: "Runtime Operations Spec",
    summary: "Long-running project operations expose bounded status, durable execution state, replayable progress, and explicit cancellation through one runtime contract.",
    surfaces: ["local-service-control", "project-canon-model", "project-knowledge-index"],
    scope: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts-change-runs.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/engine/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/project.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/contracts.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/state.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/migrations/*.sql" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-events.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/local-protocol.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-http.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-server.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-change-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/change-check-runner.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/cli-status.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/cli.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/state.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/snapshot.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/changes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/runtime-client.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/*.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/runtime-events.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/cli-reporting.test.ts" },
      { kind: DefinitionTargetKind.File, path: "package.json" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/runtime-operations-spec.md" },
    ],
    areas: ["local-service-and-runtimes", "project-map-governance"],
    rules: [
      {
        id: "status-is-bounded-summary",
        statement: "Public project status is a bounded summary and never serializes internal dependency inventories.",
        acceptance: ["validator graph status reports dependency count instead of paths", "full graph inputs require explicit inspection", "status size is bounded on large projects"],
        checks: ["contracts-tests", "runtime-client-tests"],
      },
      {
        id: "long-work-is-a-run-resource",
        statement: "Every Change check executes as a persisted run with a stable identity and explicit terminal state.",
        acceptance: ["start returns a run identity before completion", "runtime restart finalizes interrupted runs", "result and bounded output remain queryable"],
        checks: ["change-run-tests", "engine-tests"],
      },
      {
        id: "progress-is-replayable",
        statement: "Check progress and output use sequenced runtime events that reconnect from a cursor without polling.",
        acceptance: ["output is visible before process exit", "reconnect replays unseen events", "slow clients cannot create unbounded memory growth"],
        checks: ["change-run-tests", "runtime-client-tests"],
      },
      {
        id: "cancellation-is-explicit",
        statement: "Client cancellation and runtime shutdown terminate owned check process trees and persist a cancelled or interrupted terminal result.",
        acceptance: ["Ctrl-C sends cancellation", "runtime shutdown leaves no child check process", "terminal events distinguish cancellation from failure"],
        checks: ["change-run-tests", "service-lifecycle-tests"],
      },
    ],
    scenarios: [
      {
        id: "agent-watches-long-check",
        given: ["a Change check runs longer than one response timeout"],
        when: "an agent starts the check",
        then: ["the CLI prints progress while it runs", "the run survives client reconnection", "the terminal result is persisted once"],
        checks: ["change-run-tests", "runtime-client-tests"],
      },
      {
        id: "client-reads-large-project-status",
        given: ["a validator graph has thousands of dependency files"],
        when: "a client requests project status",
        then: ["the response stays bounded", "dependency count remains visible", "an explicit inspection command can list dependency paths"],
        checks: ["contracts-tests", "runtime-client-tests"],
      },
    ],
    checks: [
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "engine-tests", kind: "command", command: "npm run check:engine" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "change-run-tests", kind: "test", target: "packages/runtime/test/change-runs.test.ts" },
      { id: "service-lifecycle-tests", kind: "test", target: "packages/runtime/test/service.test.ts" },
      { id: "project-doctor", kind: "doctor" },
    ],
    governedBy: { inferFromScope: true, conventions: ["explicit-error-contracts", "service-events-current", "state-ownership-current", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/specs/runtime-operations-spec.md", style: "reference" },
  }),
  defineSpec({
    id: "release-integrity-spec",
    title: "Release Integrity Spec",
    summary: "Release publication is gated by the same proof path used for local readiness, including runtime build, validation, doctor, install rehearsal, and native embedding smoke coverage.",
    surfaces: ["release-update", "project-knowledge-index"],
    scope: [
      { kind: DefinitionTargetKind.File, path: ".github/workflows/release.yml" },
      { kind: DefinitionTargetKind.File, path: ".github/workflows/ci.yml" },
      { kind: DefinitionTargetKind.File, path: "package.json" },
      { kind: DefinitionTargetKind.File, path: "scripts/native-embedding-smoke.ts" },
      { kind: DefinitionTargetKind.File, path: "scripts/publish-opencanon-release.ts" },
      { kind: DefinitionTargetKind.File, path: "scripts/check-release-consistency.ts" },
      { kind: DefinitionTargetKind.File, path: "scripts/create-opencanon-release.ts" },
      { kind: DefinitionTargetKind.File, path: "scripts/rehearse-opencanon-install.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/release.test.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/release-integrity-spec.md" },
    ],
    areas: ["runtime-release-update", "project-knowledge-index"],
    rules: [
      {
        id: "release-workflow-runs-proof",
        statement: "A tag or manual release workflow must run the full release gate before it can publish runtime assets.",
        acceptance: ["release.yml has a preflight job", "publish-release depends on preflight", "engine builds depend on preflight"],
        checks: ["release-tests", "release-check"],
      },
      {
        id: "release-helper-runs-same-proof",
        statement: "The local release helper must run the same check:ci proof before creating and pushing a release tag.",
        acceptance: ["release publish runs check:ci before commit and tag", "release publish watches the tag workflow by commit"],
        checks: ["release-tests"],
      },
      {
        id: "native-embedding-smoke-is-explicit",
        statement: "Native embedding smoke coverage must either run and fail on error or be invoked through an explicitly optional command.",
        acceptance: ["check:ci invokes the required native embedding smoke", "the smoke script does not silently skip", "optional smoke uses an explicit optional flag"],
        checks: ["release-tests", "native-embedding-smoke"],
      },
    ],
    scenarios: [
      {
        id: "manual-release-cannot-bypass-proof",
        given: ["a maintainer starts the Release workflow manually for an existing tag"],
        when: "the release job runs",
        then: ["the preflight job checks the tagged commit", "asset publication waits for preflight success"],
        checks: ["release-tests", "release-check"],
      },
      {
        id: "embedding-config-regression-is-caught",
        given: ["Project Knowledge uses a configured native embedding model"],
        when: "the release gate runs",
        then: ["native embedding code loads the configured model path", "invalid vectors or loading failures fail the gate"],
        checks: ["native-embedding-smoke"],
      },
    ],
    checks: [
      { id: "release-tests", kind: "test", target: "tests/release.test.ts" },
      { id: "release-check", kind: "command", command: "npm run release:check" },
      { id: "native-embedding-smoke", kind: "command", command: "npm run smoke:native-embedding" },
    ],
    governedBy: { inferFromScope: true, conventions: ["state-ownership-current", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/specs/release-integrity-spec.md", style: "reference" },
  }),
  defineSpec({
    id: "spec-governance-model",
    title: "Spec Governance Model",
    summary:
      "Specs describe durable behavior as typed definitions with generated docs, governing conventions, implementation scope, impact links, and executable checks.",
    surfaces: ["project-canon-model", "project-knowledge-index"],
    scope: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/spec.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/spec-loader.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/spec-render.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/change.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/change-state.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/change-render.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/context.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/convention.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/render-links.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validation.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validator-types.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validator.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/definition-graph.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor-checks.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor-types.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/convention-history.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/project-types.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/specs.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/changes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/changes-definition.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/brief.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/mcp.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/init-flow.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/init-scaffold.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/snapshot.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/state.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/specs/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/conventions/spec-definitions-are-enforced.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/convention.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/definition-graph.test.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/spec-governance-model.md" },
    ],
    areas: ["living-conventions", "definition-authoring-flow", "project-map-governance"],
    rules: [
      {
        id: "typed-source-of-truth",
        statement: "A spec is authored as a TypeScript definition and any OpenCanon-owned Markdown is rendered from that definition.",
        acceptance: ["generated spec docs are deterministic", "definition docs have no hand-edited Markdown opt-out"],
        checks: ["spec-render", "project-doctor"],
      },
      {
        id: "definition-domain-validation",
        statement: "Validators can target explicit runtime domains such as definitions or project state without using empty file globs as the authoring contract.",
        acceptance: ["definition-scoped conventions map to validator domain definition", "project validation runs definition-domain validators once"],
        checks: ["convention-tests", "project-validation"],
      },
      {
        id: "specs-link-governance",
        statement: "Specs link the conventions and checks that keep the described behavior current.",
        acceptance: ["specs can link governing conventions", "doctor and project map can surface spec backlinks"],
        checks: ["definition-graph-tests", "project-doctor"],
      },
      {
        id: "changes-own-task-graphs",
        statement:
          "Implementation task graphs live on Change definitions while task progress is derived from runtime events.",
        acceptance: [
          "tasks can declare checks, files, impact surfaces, dependencies, blockers, and durable definition updates",
          "ready work is derived from dependency state instead of persisted as definition status",
          "task lifecycle and check events include task and check identifiers",
        ],
        checks: ["runtime-client-tests", "definition-graph-tests", "typecheck"],
      },
    ],
    scenarios: [
      {
        id: "agent-implements-feature-from-spec",
        given: ["a repo has a spec with scope, checks, and governing conventions"],
        when: "an agent changes files covered by that spec",
        then: ["OpenCanon can show the related spec", "runtime checks keep the implementation aligned with the spec and conventions"],
        checks: ["project-validation", "definition-graph-tests"],
      },
      {
        id: "agent-follows-ready-change-task",
        given: ["a Change has tasks with dependencies and declared checks"],
        when: "an agent asks for ready work",
        then: ["OpenCanon returns only unblocked work", "the agent can claim a task", "check results and close events update runtime state without editing the Change definition"],
        checks: ["runtime-client-tests", "definition-graph-tests"],
      },
    ],
    checks: [
      { id: "spec-render", kind: "command", command: "npm run opencanon -- canon render specs --dry-run" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --project" },
      { id: "project-doctor", kind: "doctor" },
      { id: "typecheck", kind: "command", command: "npm run check:types" },
      { id: "convention-tests", kind: "test", target: "tests/convention.test.ts" },
      { id: "definition-graph-tests", kind: "test", target: "tests/definition-graph.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
    ],
    governedBy: { inferFromScope: true, conventions: ["spec-definitions-are-enforced", "state-ownership-current", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/specs/spec-governance-model.md", style: "reference" },
  }),
  defineSpec({
    id: "explicit-error-contract-spec",
    title: "Explicit Error Contract Spec",
    summary: "Failed OpenCanon API envelopes expose a single error payload while diagnostics remain valid domain data inside successful responses.",
    surfaces: ["local-service-control", "project-canon-model"],
    scope: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/errors.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/local-protocol.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/conventions/explicit-error-contracts.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/explicit-error-contract-spec.md" },
    ],
    areas: ["explicit-error-contracts", "local-service-and-runtimes"],
    rules: [
      {
        id: "failed-envelope-uses-error",
        statement: "Every transport failure is represented as `{ ok: false, error }`.",
        acceptance: ["runtime HTTP failures use `error`", "service HTTP failures use `error`", "local protocol clients parse `error`"],
        checks: ["contracts-tests", "runtime-client-tests", "service-lifecycle-tests"],
      },
      {
        id: "problem-or-diagnostics",
        statement: "The error payload is discriminated as either `problem` for structured recovery or `diagnostics` for diagnostic lists.",
        acceptance: ["project-open failures use a problem payload", "diagnostic failures use a diagnostics payload", "clients branch on the error discriminant"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "diagnostics-domain-data-remains-allowed",
        statement: "Successful response bodies and internal parser results may still expose diagnostics as domain data.",
        acceptance: ["Git/history/settings diagnostics remain successful payload fields", "internal parse functions can return diagnostics before route wrapping"],
        checks: ["runtime-client-tests", "project-validation"],
      },
    ],
    scenarios: [
      {
        id: "client-opens-uninitialized-project",
        given: ["a folder exists but is not an initialized OpenCanon project"],
        when: "a CLI, MCP, or browser diagnostics client asks the service to ensure that project",
        then: ["the service returns `error.kind = problem`", "the problem includes the folder path and setup action", "the client can display a predictable recovery flow"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
    ],
    checks: [
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "service-lifecycle-tests", kind: "test", target: "packages/runtime/test/service.test.ts" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --project" },
    ],
    governedBy: { inferFromScope: true, conventions: ["explicit-error-contracts", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/specs/explicit-error-contract-spec.md", style: "reference" },
  }),
  defineSpec({
    id: "project-runtime-lifecycle-spec",
    title: "Project Runtime Lifecycle Spec",
    summary: "The local service owns a ready-only, typed, and retry-aware lifecycle for isolated project runtimes.",
    surfaces: ["local-service-control"],
    scope: [
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/cli.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/runtime-client.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/problem.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validator-graph.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/service.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/service-reconcile.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/client.test.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/project-runtime-lifecycle-spec.md" },
    ],
    areas: ["local-service-and-runtimes", "explicit-error-contracts"],
    rules: [
      {
        id: "ensure-means-ready",
        statement: "A successful project ensure or start result must reference a runtime whose process identity and health endpoint have been verified.",
        acceptance: ["process spawn is not returned as command success", "starting remains observable while the request waits", "ready results carry the running lifecycle"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "startup-failure-is-typed",
        statement: "A project runtime that exits during startup must return a structured problem or diagnostics payload to the supervising service before it exits.",
        acceptance: ["failure includes the project path", "missing definition errors include the missing path and repair action", "clients do not parse runtime logs to recover the cause"],
        checks: ["service-lifecycle-tests", "runtime-client-tests", "contracts-tests"],
      },
      {
        id: "retryability-drives-repair",
        statement: "Automatic repair and reconciliation retry transient runtime failures but do not retry deterministic non-retryable project failures.",
        acceptance: ["dead or disconnected healthy projects can restart", "invalid project definitions become terminal failures", "a repaired project can be started explicitly"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "service-owns-startup-state",
        statement: "The local service owns project startup waiting, process cleanup, and repair; clients consume its result instead of implementing a second startup state machine.",
        acceptance: ["CLI and runtime client share the same ensure path", "one startup lock serializes a project start", "failed starts leave no registered or orphaned worker"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
    ],
    scenarios: [
      {
        id: "start-healthy-project",
        given: ["an initialized project has valid Project Canon definitions", "no project runtime is running"],
        when: "a client starts or first queries the project",
        then: ["the service lazily starts one isolated runtime", "the result is returned only after health is ready", "subsequent clients reuse the ready runtime"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "start-incomplete-project",
        given: ["an OpenCanon config exists", "the required conventions entrypoint is missing"],
        when: "a client starts or queries the project",
        then: ["the request fails once with a non-retryable problem", "the problem names the missing path and repair command", "no project runtime remains registered or restarts in the background"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
    ],
    checks: [
      { id: "service-lifecycle-tests", kind: "test", target: "packages/runtime/test/service.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "project-doctor", kind: "doctor" },
    ],
    governedBy: { inferFromScope: true, conventions: ["explicit-error-contracts", "state-ownership-current", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/specs/project-runtime-lifecycle-spec.md", style: "reference" },
  }),
];
