import { DefinitionTargetKind, defineSpec } from "@opencanon/core";

export default [
  defineSpec({
    id: "domain-protocol-spec",
    title: "Domain Protocol Spec",
    summary: "CLI, MCP, browser, and desktop clients consume bounded revisioned projections and replayable events through one transport-independent runtime contract.",
    surfaces: ["local-service-control", "project-canon-model", "project-knowledge-index", "release-update"],
    scope: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/protocol*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/generated/domain-protocol.openapi.json" },
      { kind: DefinitionTargetKind.File, path: "scripts/generate-domain-protocol.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/engine/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/{contracts,project,state}.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/project/{code_graph_connection,product_model_store,protocol_event_store}.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/migrations/014_project_publication.sql" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/{project-refresh-publication,state-manager,state}.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-events.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/local-protocol.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-http.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/protocol-policy.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/{brief,changes,context,feedback,gate,graph,mcp,opencode-plugin,refactor,review,runtime-client,search,symbols,validate}.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/*.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/{contracts,cli-reporting,runtime-events,mcp}.test.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/domain-protocol-spec.md" },
    ],
    areas: ["local-service-and-runtimes", "project-map-governance", "project-knowledge-index", "runtime-release-update"],
    rules: [
      {
        id: "one-operation-registry",
        statement: "One typed operation registry owns request, response, authorization, consistency, cost, idempotency, cancellation, and transport mappings.",
        acceptance: ["runtime routing and clients use the same operation ids", "every operation has complete policy", "the generated API description is deterministic"],
        checks: ["protocol-tests", "protocol-contract-drift", "contracts-tests"],
      },
      {
        id: "projections-are-bounded-and-revisioned",
        statement: "Every project read returns a bounded projection tied to the exact published revision used to compute it.",
        acceptance: ["collections have fixed limits and opaque cursors", "graph reads return bounded neighborhoods", "no routine response contains the complete project snapshot"],
        checks: ["protocol-tests", "runtime-client-tests", "cli-tests"],
      },
      {
        id: "events-are-replayable-invalidations",
        statement: "Live project events carry monotonic cursors, published revisions, affected domains, and bounded progress without embedding project projections.",
        acceptance: ["reconnect replays unseen events once in order", "expired history requests explicit resynchronization", "slow clients are bounded by queued bytes"],
        checks: ["runtime-event-tests", "runtime-client-tests"],
      },
      {
        id: "publication-is-atomic-and-monotonic",
        statement: "Project State commits each monotonic published revision, accepted product projection, active graph generation, Canon history, and replay event as one durable publication boundary.",
        acceptance: ["failed publication keeps the previous graph and revision", "runtime restart resumes above the last published revision", "coalesced refreshes may skip revisions but can never publish a revision at or below the current one", "the serving Project State is the sole graph publication owner while isolated analysis can only stage generations into that owner", "generation cleanup cannot remove a staged graph during publication", "live delivery relays the committed replay event without appending it again", "unchanged refreshes advance revision without rewriting the product projection"],
        checks: ["engine-publication-tests", "coordinator-tests", "runtime-event-tests", "runtime-client-tests"],
      },
      {
        id: "transports-preserve-domain-semantics",
        statement: "HTTP and local pipe are adapters over the same domain operations and return identical success, problem, revision, and cancellation semantics.",
        acceptance: ["authorization precedes admission", "unsafe commands are never replayed automatically", "capacity is held through response delivery"],
        checks: ["protocol-tests", "runtime-client-tests"],
      },
      {
        id: "complete-snapshots-stay-internal",
        statement: "Complete runtime snapshots remain an internal accepted-state representation and never cross a public transport or event stream.",
        acceptance: ["the snapshot API is absent", "CLI and MCP use bounded operations", "diagnostic export, if introduced, is an isolated artifact operation"],
        checks: ["contracts-tests", "cli-tests", "mcp-tests"],
      },
    ],
    scenarios: [
      {
        id: "gui-resumes-after-disconnect",
        given: ["a GUI has cached Canon and Activity at a published revision", "its event connection closes"],
        when: "the GUI reconnects with its last event cursor",
        then: ["unseen invalidations replay in order", "only affected projections refetch", "expired history requests explicit resynchronization"],
        checks: ["runtime-event-tests", "runtime-client-tests"],
      },
      {
        id: "agent-validates-large-project",
        given: ["a project contains thousands of files and definitions"],
        when: "an agent runs changed or project validation",
        then: ["validation executes as a bounded runtime operation", "the client does not download a project snapshot", "the result names its published revision"],
        checks: ["runtime-client-tests", "cli-tests"],
      },
    ],
    checks: [
      { id: "protocol-tests", kind: "test", target: "packages/runtime/test/protocol.test.ts" },
      { id: "protocol-contract-drift", kind: "command", command: "npm run protocol:check" },
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "runtime-event-tests", kind: "test", target: "tests/runtime-events.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "cli-tests", kind: "test", target: "tests/cli-reporting.test.ts" },
      { id: "mcp-tests", kind: "test", target: "tests/mcp.test.ts" },
      { id: "engine-publication-tests", kind: "command", command: "npm run check:engine" },
      { id: "coordinator-tests", kind: "test", target: "packages/runtime/test/state-manager.test.ts" },
      { id: "project-doctor", kind: "doctor" },
    ],
    governedBy: { inferFromScope: true, conventions: ["explicit-error-contracts", "state-ownership-current", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/specs/domain-protocol-spec.md", style: "reference" },
  }),
  defineSpec({
    id: "runtime-operations-spec",
    title: "Runtime Operations Spec",
    summary: "Long-running project operations expose bounded status, durable execution state, replayable progress, and explicit cancellation through one runtime contract.",
    surfaces: ["local-service-control", "project-canon-model", "project-knowledge-index", "release-update"],
    scope: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts-change-runs.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/engine/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/project.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/contracts.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/state.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/migrations/*.sql" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-events.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/protocol-policy.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-http.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/local-protocol.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-http.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-server.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/check-command-guardian.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-change-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/change-check-runner.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/cli-status.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/cli.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/state.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/snapshot.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/project-analysis*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/changes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/runtime-client.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/client-test-sources.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/*.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/runtime-events.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/cli-reporting.test.ts" },
      { kind: DefinitionTargetKind.File, path: "package.json" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/runtime-operations-spec.md" },
    ],
    areas: ["local-service-and-runtimes", "project-map-governance"],
    rules: [
      {
        id: "status-is-bounded-summary",
        statement: "Public project status is a bounded summary and never serializes internal dependency inventories.",
        acceptance: ["validator graph status reports dependency count instead of paths", "full graph inputs require explicit inspection", "status size is bounded on large projects"],
        checks: ["contracts-tests", "runtime-client-tests"],
      },
      {
        id: "long-work-is-a-run-resource",
        statement: "Every Change check executes as a persisted run with a stable identity and explicit terminal state.",
        acceptance: ["start returns a run identity before completion", "runtime restart finalizes interrupted runs", "result and bounded output remain queryable"],
        checks: ["change-run-tests", "engine-tests"],
      },
      {
        id: "progress-is-replayable",
        statement: "Check progress and output use sequenced runtime events that reconnect from a cursor without polling.",
        acceptance: ["output is visible before process exit", "reconnect replays unseen events", "slow clients cannot create unbounded memory growth"],
        checks: ["change-run-tests", "runtime-client-tests"],
      },
      {
        id: "cancellation-is-explicit",
        statement: "Client cancellation and runtime shutdown terminate owned check process trees and persist a cancelled or interrupted terminal result.",
        acceptance: ["Ctrl-C sends cancellation", "runtime shutdown leaves no child check process", "terminal events distinguish cancellation from failure"],
        checks: ["change-run-tests", "service-lifecycle-tests"],
      },
      {
        id: "operation-resources-are-bounded",
        statement: "A project runtime bounds active operation admission and terminal run history without deleting non-terminal work.",
        acceptance: ["admission rejects a whole batch before capacity is exceeded", "terminal history is pruned by age and count", "run events cascade when their run is removed", "active operations leave process readiness running and expose work through operation resources", "project analysis and Project Knowledge indexing never overlap", "explicit Knowledge indexing waits for current analysis while later source refresh queues behind indexing", "process inspection cannot overwrite a concurrent lifecycle transition", "Project State allocates monotonic run-event sequences atomically across runtime connections"],
        checks: ["contracts-tests", "change-run-tests", "runtime-supervision-tests", "engine-tests"],
      },
      {
        id: "heavy-responses-have-shared-admission",
        statement: "Every transport shares one fail-fast capacity boundary for heavyweight project responses and holds capacity until delivery completes.",
        acceptance: ["concurrent heavy requests cannot accumulate response copies", "overload returns an explicit diagnostic instead of queueing", "bounded health and projection routes remain available", "HTTP and pipe consume the same capacity"],
        checks: ["runtime-client-tests"],
      },
      {
        id: "persisted-runs-remain-operable",
        statement: "Clients can list, inspect, watch, and cancel persisted runs independently of the process that created them.",
        acceptance: ["list and show responses are bounded", "watch resumes from an event cursor without polling", "terminal cancellation is idempotent", "shell checks use explicit bounded timeout budgets", "active runs prevent lazy runtime shutdown and receive a full idle window after completion", "in-flight responses and event streams hold an activity lease until transport completion"],
        checks: ["change-run-tests", "runtime-client-tests"],
      },
      {
        id: "isolated-check-runtimes-follow-owner-lifecycle",
        statement: "Shell-backed Proof uses isolated service namespaces whose service, project runtimes, and generated workspace share one explicit owner lifecycle.",
        acceptance: ["owner death stops the isolated service, every child project runtime, and the active shell process tree", "completed checks remove their generated workspace", "a later check reaps an orphaned workspace only after its owner is dead"],
        checks: ["change-run-tests", "service-lifecycle-tests"],
      },
      {
        id: "proof-guardians-use-process-liveness",
        statement: "A Proof command guardian distinguishes actual owner-process death from a temporarily blocked owner event loop and always enforces the declared command deadline.",
        acceptance: ["owner-process death terminates the complete command process tree", "an owner event-loop stall within the command budget does not cancel healthy work", "the external guardian enforces the deadline even when the owner event loop cannot run"],
        checks: ["service-lifecycle-tests", "change-run-tests"],
      },
      {
        id: "state-projections-use-complete-activity",
        statement: "Correctness-sensitive Change state is derived from complete indexed Activity for the relevant Changes, while browsing feeds remain bounded.",
        acceptance: ["unrelated Activity cannot reopen closed work", "ready work and snapshots use the same complete history", "complete history is queried in one batch for current Changes"],
        checks: ["engine-tests", "runtime-client-tests", "worktree-tests"],
      },
      {
        id: "local-clients-use-pipe-transport",
        statement: "Local CLI and MCP requests use the pipe control plane by default while loopback HTTP remains an explicit browser and diagnostics adapter.",
        acceptance: ["brief uses the shared default runtime client", "commands do not select HTTP without a surface requirement", "pipe transport is covered by integration proof"],
        checks: ["runtime-client-tests", "cli-tests"],
      },
      {
        id: "doctor-reports-live-knowledge",
        statement: "Doctor reports current Project Knowledge readiness when a matching project runtime is running and never presents an uninspected snapshot as ready.",
        acceptance: ["stale or missing live Knowledge warns", "invalid state or a failed live probe fails", "no running runtime is described as uninspected"],
        checks: ["doctor-tests", "cli-tests", "runtime-client-tests"],
      },
      {
        id: "diagnostics-do-not-start-project-work",
        statement: "Doctor and status surfaces inspect bounded current state without starting producers, validation, indexing, or project snapshot revisions.",
        acceptance: ["an idle producer remains idle after Doctor", "Doctor does not publish a project revision", "pipe and HTTP health remain responsive throughout Doctor", "typed validation starts its required producer and publishes the generation it consumed"],
        checks: ["doctor-tests", "cli-tests", "runtime-client-tests", "service-lifecycle-tests"],
      },
      {
        id: "source-refresh-preserves-transports",
        statement: "Project source refresh keeps pipe and HTTP responsive by running complete analysis outside the serving runtime and publishing only a complete accepted revision.",
        acceptance: ["the serving process does not perform discovery, canon bundling, fact extraction, graph construction, or project validation", "source and canon watchers schedule one coalesced isolated analysis path instead of reloading definitions on a request", "superseded analysis is cancelled and cannot publish", "analysis failure preserves the previous snapshot and serving transports", "watcher events settle without facts, validation, graph staging, or accepted-state replacement only when source inventory, canon graphs, effective configuration, and validation context are content-equivalent", "graph indexing writes a private generation that stays invisible until the serving runtime accepts it", "the product projection and graph generation commit only for the newest observed revision", "native graph writes do not run on the serving JavaScript event loop", "graph readers use independent SQLite WAL connections while graph writes are pending", "Activity and other Project State writes do not contend with graph transactions", "complete source identity derives changed and deleted graph files inside the graph store", "missing or incompatible graph state rebuilds from source", "cold graph extraction bounds memory by streaming files into one transaction", "a long refresh does not replace the serving runtime"],
        checks: ["engine-tests", "project-analysis-tests", "runtime-client-tests", "service-lifecycle-tests"],
      },
      {
        id: "knowledge-builds-are-explicit-and-isolated",
        statement: "Project Knowledge reads never start indexing, while native index and query inference execute with bounded memory outside the serving runtime.",
        acceptance: ["missing or stale Knowledge fails read commands immediately", "only project index starts a build", "source and embedding batches have fixed bounds", "index and query worker failures preserve runtime availability and the last published index", "native embedding models are never loaded into the serving runtime"],
        checks: ["semantic-index-tests", "runtime-client-tests", "service-lifecycle-tests"],
      },
      {
        id: "mutating-runtime-requests-are-idempotent",
        statement: "A repaired client may retry a mutating runtime request with the same request identity without duplicating or contradicting committed Activity.",
        acceptance: ["an identical event retry returns the committed event", "reusing an event id for different content fails explicitly", "asynchronous check persistence failures terminate the run rather than the runtime"],
        checks: ["change-run-tests", "runtime-client-tests"],
      },
    ],
    scenarios: [
      {
        id: "agent-watches-long-check",
        given: ["a Change check runs longer than one response timeout"],
        when: "an agent starts the check",
        then: ["the CLI prints progress while it runs", "the run survives client reconnection", "the terminal result is persisted once"],
        checks: ["change-run-tests", "runtime-client-tests"],
      },
      {
        id: "client-reads-large-project-status",
        given: ["a validator graph has thousands of dependency files"],
        when: "a client requests project status",
        then: ["the response stays bounded", "dependency count remains visible", "an explicit inspection command can list dependency paths"],
        checks: ["contracts-tests", "runtime-client-tests"],
      },
      {
        id: "client-reattaches-to-check-run",
        given: ["a Change check continues after its initiating client exits"],
        when: "another client inspects and watches the persisted run",
        then: ["the run is discoverable", "unseen output replays from the requested cursor", "one terminal result is observed"],
        checks: ["change-run-tests", "runtime-client-tests"],
      },
      {
        id: "agent-brief-survives-unrelated-activity",
        given: ["a Change and all of its tasks are closed", "more than 500 newer events belong to other Changes"],
        when: "an agent requests ready work or a briefing",
        then: ["the closed Change is absent from ready and blocked work", "the briefing queue agrees with the Change snapshot"],
        checks: ["engine-tests", "runtime-client-tests", "worktree-tests", "cli-tests"],
      },
      {
        id: "search-observes-missing-knowledge",
        given: ["Project Knowledge has not been built"],
        when: "a client searches or reads semantic context",
        then: ["the request returns semantic-index-not-ready without scanning the repository", "the project runtime stays healthy", "the response points to opencanon project index"],
        checks: ["semantic-index-tests", "runtime-client-tests", "cli-tests"],
      },
    ],
    checks: [
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "engine-tests", kind: "command", command: "npm run check:engine" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "semantic-index-tests", kind: "test", target: "packages/runtime/test/semantic-index.test.ts" },
      { id: "project-analysis-tests", kind: "test", target: "packages/runtime/test/project-analysis.test.ts" },
      { id: "change-run-tests", kind: "test", target: "packages/runtime/test/change-runs.test.ts" },
      { id: "runtime-supervision-tests", kind: "test", target: "packages/runtime/test/runtime-supervision.test.ts" },
      { id: "service-lifecycle-tests", kind: "test", target: "packages/runtime/test/service.test.ts" },
      { id: "cli-tests", kind: "test", target: "tests/cli-reporting.test.ts" },
      { id: "doctor-tests", kind: "test", target: "tests/validator-runtime.test.ts" },
      { id: "worktree-tests", kind: "test", target: "tests/worktree.test.ts" },
      { id: "project-doctor", kind: "doctor" },
    ],
    governedBy: { inferFromScope: true, conventions: ["explicit-error-contracts", "service-events-current", "state-ownership-current", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/specs/runtime-operations-spec.md", style: "reference" },
  }),
  defineSpec({
    id: "release-integrity-spec",
    title: "Release Integrity Spec",
    summary: "Release publication is an explicit, version-locked operation gated by the same proof path used for local readiness, dependency security, runtime build, validation, Doctor, install rehearsal, and native embedding smoke coverage.",
    surfaces: ["release-update", "project-knowledge-index"],
    scope: [
      { kind: DefinitionTargetKind.File, path: ".github/workflows/release.yml" },
      { kind: DefinitionTargetKind.File, path: ".github/workflows/ci.yml" },
      { kind: DefinitionTargetKind.File, path: "package.json" },
      { kind: DefinitionTargetKind.File, path: "scripts/native-embedding-smoke.ts" },
      { kind: DefinitionTargetKind.File, path: "scripts/prepare-opencanon-release.ts" },
      { kind: DefinitionTargetKind.File, path: "scripts/publish-opencanon-release.ts" },
      { kind: DefinitionTargetKind.File, path: "scripts/check-release-consistency.ts" },
      { kind: DefinitionTargetKind.File, path: "scripts/create-opencanon-release.ts" },
      { kind: DefinitionTargetKind.File, path: "scripts/rehearse-opencanon-install.ts" },
      { kind: DefinitionTargetKind.File, path: "crates/*/Cargo.toml" },
      { kind: DefinitionTargetKind.File, path: "crates/*/Cargo.lock" },
      { kind: DefinitionTargetKind.File, path: "tests/release.test.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/runtime-update-security.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/release-integrity-spec.md" },
    ],
    areas: ["runtime-release-update", "project-knowledge-index"],
    rules: [
      {
        id: "release-workflow-runs-proof",
        statement: "Only an explicit workflow dispatch for an existing tag may run the full release gate and publish runtime assets.",
        acceptance: ["pushing a tag does not start publication", "release.yml has a preflight job", "publish-release depends on preflight", "engine builds depend on preflight"],
        checks: ["release-tests", "release-check"],
      },
      {
        id: "release-helper-runs-same-proof",
        statement: "The local release helper must run the same check:ci proof before creating and pushing a release tag.",
        acceptance: ["release publish runs check:ci before commit and tag", "release publish dispatches the release workflow explicitly", "release publish watches the dispatched workflow by tagged commit"],
        checks: ["release-tests"],
      },
      {
        id: "release-versions-move-together",
        statement: "Every release-owned TypeScript package, Rust crate, engine constant, and committed lockfile must advertise the same runtime version and be updated by one preparation command.",
        acceptance: ["release check covers every workspace package", "release check covers every OpenCanon crate and lock entry", "release prepare updates the complete version set"],
        checks: ["release-tests", "release-check"],
      },
      {
        id: "release-supply-chain-is-audited",
        statement: "The local and release gates audit shipped npm dependencies and every committed Cargo lockfile, reject vulnerable or unsound dependencies, and pin third-party workflow actions to immutable commits.",
        acceptance: ["npm shipped dependencies are audited", "all Cargo lockfiles are audited", "unsound advisories fail", "workflow actions use immutable SHAs"],
        checks: ["release-tests", "release-check"],
      },
      {
        id: "native-embedding-smoke-is-explicit",
        statement: "Native embedding smoke coverage must either run and fail on error or be invoked through an explicitly optional command.",
        acceptance: ["check:ci invokes the required native embedding smoke", "the smoke script does not silently skip", "optional smoke uses an explicit optional flag"],
        checks: ["release-tests", "native-embedding-smoke"],
      },
    ],
    scenarios: [
      {
        id: "manual-release-cannot-bypass-proof",
        given: ["a maintainer starts the Release workflow manually for an existing tag"],
        when: "the release job runs",
        then: ["the preflight job checks the tagged commit", "asset publication waits for preflight success"],
        checks: ["release-tests", "release-check"],
      },
      {
        id: "tag-push-is-inert",
        given: ["a release tag is created or pushed"],
        when: "no maintainer explicitly dispatches the Release workflow",
        then: ["no release build starts", "no signing secret is requested", "no assets are published"],
        checks: ["release-tests", "release-check"],
      },
      {
        id: "embedding-config-regression-is-caught",
        given: ["Project Knowledge uses a configured native embedding model"],
        when: "the release gate runs",
        then: ["native embedding code loads the configured model path", "invalid vectors or loading failures fail the gate"],
        checks: ["native-embedding-smoke"],
      },
    ],
    checks: [
      { id: "release-tests", kind: "test", target: "tests/release.test.ts" },
      { id: "release-check", kind: "command", command: "npm run release:check" },
      { id: "native-embedding-smoke", kind: "command", command: "npm run smoke:native-embedding" },
    ],
    governedBy: { inferFromScope: true, conventions: ["state-ownership-current", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/specs/release-integrity-spec.md", style: "reference" },
  }),
  defineSpec({
    id: "spec-governance-model",
    title: "Spec Governance Model",
    summary:
      "Specs describe durable behavior as typed definitions with generated docs, governing conventions, implementation scope, impact links, and executable checks.",
    surfaces: ["project-canon-model", "project-knowledge-index"],
    scope: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/spec.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/spec-loader.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/spec-render.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/change.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/change-state.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/change-render.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/context.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/convention.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/render-links.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validation.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validator-types.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validator.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/definition-graph.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor-checks.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor-types.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/convention-history.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/project-types.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/specs.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/changes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/changes-definition.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/brief.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/mcp.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/init-flow.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/init-scaffold.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/snapshot.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/state.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/specs/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/conventions/spec-definitions-are-enforced.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/convention.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/definition-graph.test.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/spec-governance-model.md" },
    ],
    areas: ["living-conventions", "definition-authoring-flow", "project-map-governance"],
    rules: [
      {
        id: "typed-source-of-truth",
        statement: "A spec is authored as a TypeScript definition and any OpenCanon-owned Markdown is rendered from that definition.",
        acceptance: ["generated spec docs are deterministic", "definition docs have no hand-edited Markdown opt-out"],
        checks: ["spec-render", "project-doctor"],
      },
      {
        id: "definition-domain-validation",
        statement: "Validators can target explicit runtime domains such as definitions or project state without using empty file globs as the authoring contract.",
        acceptance: ["definition-scoped conventions map to validator domain definition", "project validation runs definition-domain validators once"],
        checks: ["convention-tests", "project-validation"],
      },
      {
        id: "specs-link-governance",
        statement: "Specs link the conventions and checks that keep the described behavior current.",
        acceptance: ["specs can link governing conventions", "doctor and project map can surface spec backlinks"],
        checks: ["definition-graph-tests", "project-doctor"],
      },
      {
        id: "changes-own-task-graphs",
        statement:
          "Implementation task graphs live on Change definitions while task progress is derived from runtime events.",
        acceptance: [
          "tasks can declare checks, files, impact surfaces, dependencies, blockers, and durable definition updates",
          "ready work is derived from dependency state instead of persisted as definition status",
          "task lifecycle and check events include task and check identifiers",
        ],
        checks: ["runtime-client-tests", "definition-graph-tests", "typecheck"],
      },
    ],
    scenarios: [
      {
        id: "agent-implements-feature-from-spec",
        given: ["a repo has a spec with scope, checks, and governing conventions"],
        when: "an agent changes files covered by that spec",
        then: ["OpenCanon can show the related spec", "runtime checks keep the implementation aligned with the spec and conventions"],
        checks: ["project-validation", "definition-graph-tests"],
      },
      {
        id: "agent-follows-ready-change-task",
        given: ["a Change has tasks with dependencies and declared checks"],
        when: "an agent asks for ready work",
        then: ["OpenCanon returns only unblocked work", "the agent can claim a task", "check results and close events update runtime state without editing the Change definition"],
        checks: ["runtime-client-tests", "definition-graph-tests"],
      },
    ],
    checks: [
      { id: "spec-render", kind: "command", command: "npm run opencanon -- canon render specs --dry-run" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --project" },
      { id: "project-doctor", kind: "doctor" },
      { id: "typecheck", kind: "command", command: "npm run check:types" },
      { id: "convention-tests", kind: "test", target: "tests/convention.test.ts" },
      { id: "definition-graph-tests", kind: "test", target: "tests/definition-graph.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
    ],
    governedBy: { inferFromScope: true, conventions: ["spec-definitions-are-enforced", "state-ownership-current", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/specs/spec-governance-model.md", style: "reference" },
  }),
  defineSpec({
    id: "explicit-error-contract-spec",
    title: "Explicit Error Contract Spec",
    summary: "Failed OpenCanon API envelopes expose a single error payload while diagnostics remain valid domain data inside successful responses.",
    surfaces: ["local-service-control", "project-canon-model"],
    scope: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/errors.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/local-protocol.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/conventions/explicit-error-contracts.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/explicit-error-contract-spec.md" },
    ],
    areas: ["explicit-error-contracts", "local-service-and-runtimes"],
    rules: [
      {
        id: "failed-envelope-uses-error",
        statement: "Every transport failure is represented as `{ ok: false, error }`.",
        acceptance: ["runtime HTTP failures use `error`", "service HTTP failures use `error`", "local protocol clients parse `error`"],
        checks: ["contracts-tests", "runtime-client-tests", "service-lifecycle-tests"],
      },
      {
        id: "problem-or-diagnostics",
        statement: "The error payload is discriminated as either `problem` for structured recovery or `diagnostics` for diagnostic lists.",
        acceptance: ["project-open failures use a problem payload", "diagnostic failures use a diagnostics payload", "clients branch on the error discriminant"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "diagnostics-domain-data-remains-allowed",
        statement: "Successful response bodies and internal parser results may still expose diagnostics as domain data.",
        acceptance: ["Git/history/settings diagnostics remain successful payload fields", "internal parse functions can return diagnostics before route wrapping"],
        checks: ["runtime-client-tests", "project-validation"],
      },
    ],
    scenarios: [
      {
        id: "client-opens-uninitialized-project",
        given: ["a folder exists but is not an initialized OpenCanon project"],
        when: "a CLI, MCP, or browser diagnostics client asks the service to ensure that project",
        then: ["the service returns `error.kind = problem`", "the problem includes the folder path and setup action", "the client can display a predictable recovery flow"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
    ],
    checks: [
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "service-lifecycle-tests", kind: "test", target: "packages/runtime/test/service.test.ts" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --project" },
    ],
    governedBy: { inferFromScope: true, conventions: ["explicit-error-contracts", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/specs/explicit-error-contract-spec.md", style: "reference" },
  }),
  defineSpec({
    id: "project-runtime-lifecycle-spec",
    title: "Project Runtime Lifecycle Spec",
    summary: "The local service and project runtime expose revision-driven readiness, typed failure, and deterministic shutdown.",
    surfaces: ["local-service-control", "release-update"],
    scope: [
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/cli.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/state-manager.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/activity-tracker.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/runtime-client.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/problem.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validator-graph.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/service.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/service-reconcile.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/client-test-sources.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/client.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/cli-reporting.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/mcp.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/worktree.test.ts" },
      { kind: DefinitionTargetKind.File, path: ".github/workflows/ci.yml" },
      { kind: DefinitionTargetKind.File, path: "package.json" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/project-runtime-lifecycle-spec.md" },
    ],
    areas: ["local-service-and-runtimes", "explicit-error-contracts"],
    rules: [
      {
        id: "readiness-is-revision-driven",
        statement: "Project readiness is determined by published and observed revisions rather than timing or a momentary process status.",
        acceptance: ["every accepted refresh has a monotonic revision", "queued filesystem refreshes coalesce to the newest revision", "superseded rebuilds cannot publish", "durable Change check results do not wait for a full snapshot rebuild", "summary responses expose observed, accepted, and published revisions"],
        checks: ["coordinator-tests", "change-run-tests", "runtime-client-tests", "contracts-tests"],
      },
      {
        id: "transport-and-project-readiness-are-distinct",
        statement: "Transport liveness, project revision readiness, and Project Knowledge readiness are independently observable states.",
        acceptance: ["both transport adapters are listening before initial project analysis is scheduled", "transport can accept status requests while project refresh is active", "read operations never trigger project analysis", "project summary reports freshness without pretending transient work is failure", "project selection is independent from process and revision status", "Knowledge routes reject missing, indexing, stale, or failed indexes explicitly"],
        checks: ["runtime-client-tests", "contracts-tests"],
      },
      {
        id: "idle-shutdown-requires-quiescence",
        statement: "A runtime can stop for idleness only after transport leases, Change checks, queued refreshes, and active refreshes are all complete.",
        acceptance: ["transport leases release exactly once", "stream cancellation releases its lease", "queued coordinator work prevents idle shutdown", "completed work receives a full idle window"],
        checks: ["activity-tests", "runtime-client-tests"],
      },
      {
        id: "shutdown-cancels-before-waiting",
        statement: "Explicit runtime shutdown rejects new work and cancels owned analysis and indexing before waiting for quiescence and disposing shared resources.",
        acceptance: ["active analysis receives abort before shutdown waits", "queued refreshes never start during shutdown", "expected cancellation does not publish a failure", "shutdown completes when an owned operation ignores cancellation only by an explicit timeout failure"],
        checks: ["coordinator-tests", "service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "ensure-means-ready",
        statement: "A successful project ensure or start result must reference a runtime whose process identity and health endpoint have been verified.",
        acceptance: ["process spawn is not returned as command success", "starting remains observable while the request waits", "ready results carry the running lifecycle", "source-runtime identity changes when an imported source or native binary changes"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "startup-failure-is-typed",
        statement: "A project runtime that exits during startup must return a structured problem or diagnostics payload to the supervising service before it exits.",
        acceptance: ["failure includes the project path", "missing definition errors include the missing path and repair action", "clients do not parse runtime logs to recover the cause"],
        checks: ["service-lifecycle-tests", "runtime-client-tests", "contracts-tests"],
      },
      {
        id: "retryability-drives-repair",
        statement: "Automatic repair and reconciliation retry transient runtime failures but do not retry deterministic non-retryable project failures.",
        acceptance: ["dead or disconnected healthy projects can restart", "invalid project definitions become terminal failures", "a repaired project can be started explicitly"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "service-owns-startup-state",
        statement: "The local service owns project startup waiting, process cleanup, and repair; clients consume its result instead of implementing a second startup state machine.",
        acceptance: ["CLI and runtime client share the same ensure path", "one startup lock serializes a project start", "failed starts leave no registered or orphaned worker", "owner-bound temporary services terminate when their owner exits"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "process-control-is-namespaced",
        statement: "Each runtime distribution owns a deterministic namespace for global control state, project processes, SQLite state, and vector state.",
        acceptance: ["installed and source services use different registries", "runtime registrations, worker leases, SQLite state, and vector state use the same namespace as their service", "namespace values cannot escape generated-state directories", "ephemeral Proof state is removed with its owned workspace"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "doctor-inspects-live-runtime",
        statement: "Doctor waits only for process startup, then observes runtime health, producers, and Project Knowledge without starting or blocking on project-state work.",
        acceptance: ["Doctor immediately after validation does not report active refresh work as unhealthy", "an idle producer is healthy and remains idle", "Doctor does not advance a project revision", "a responsive matching runtime remains process-ready while revisions refresh", "failed revision state remains explicitly observable through runtime state"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "isolated-clients-retire-owned-processes",
        statement: "Tests and ephemeral clients that create private service registries must retire every service and project process they own before deleting their workspace.",
        acceptance: ["teardown stops project runtimes before the service", "stop failures fail the test", "a completed suite leaves no process for a deleted private registry"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
    ],
    scenarios: [
      {
        id: "refresh-during-refresh",
        given: ["a project refresh is running", "the watcher observes a newer source revision"],
        when: "the older refresh completes",
        then: ["the older result is not published as current", "the queued work coalesces to the newest revision", "waiters complete only after that revision is published"],
        checks: ["coordinator-tests"],
      },
      {
        id: "start-healthy-project",
        given: ["an initialized project has valid Project Canon definitions", "no project runtime is running"],
        when: "a client starts or first queries the project",
        then: ["the service lazily starts one isolated runtime", "the result is returned only after health is ready", "subsequent clients reuse the ready runtime"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "start-incomplete-project",
        given: ["an OpenCanon config exists", "the required conventions entrypoint is missing"],
        when: "a client starts or queries the project",
        then: ["the request fails once with a non-retryable problem", "the problem names the missing path and repair command", "no project runtime remains registered or restarts in the background"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "source-and-installed-runtime-coexist",
        given: ["an installed runtime and a source checkout target the same project"],
        when: "each starts its own service and project runtime",
        then: ["neither replaces the other service registry", "neither retires the other worker lease", "each opens namespace-owned SQLite and vector state", "schema compatibility and indexing are evaluated independently without writer contention"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "doctor-after-project-work",
        given: ["a matching project runtime is registered", "validation or refresh work is still active"],
        when: "Doctor runs immediately after that project work",
        then: ["Doctor confirms the responsive running process", "health, producer, and Knowledge checks use the matching runtime", "revision progress remains visible without becoming a false health failure"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
    ],
    checks: [
      { id: "service-lifecycle-tests", kind: "test", target: "packages/runtime/test/service.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "coordinator-tests", kind: "test", target: "packages/runtime/test/state-manager.test.ts" },
      { id: "activity-tests", kind: "test", target: "packages/runtime/test/activity-tracker.test.ts" },
      { id: "change-run-tests", kind: "test", target: "packages/runtime/test/change-runs.test.ts" },
      { id: "project-doctor", kind: "doctor" },
    ],
    governedBy: { inferFromScope: true, conventions: ["explicit-error-contracts", "state-ownership-current", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/specs/project-runtime-lifecycle-spec.md", style: "reference" },
  }),
];
