import { DefinitionTargetKind, defineSpec } from "@opencanon/core";

export default [
  defineSpec({
    id: "spec-governance-model",
    title: "Spec Governance Model",
    summary:
      "Specs describe durable behavior as typed definitions with generated docs, governing conventions, implementation scope, impact links, and executable checks.",
    surfaces: ["project-canon-model", "project-context-index"],
    scope: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/spec.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/spec-loader.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/spec-render.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/change.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/change-state.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/change-render.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/context.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/convention.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/render-links.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validation.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validator-types.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validator.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/definition-graph.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor-checks.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor-types.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/convention-history.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/project-types.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/specs.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/changes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/changes-definition.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/brief.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/mcp.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/init-flow.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/init-scaffold.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/snapshot.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/state.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/specs/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/conventions/spec-definitions-are-enforced.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/convention.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/definition-graph.test.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/spec-governance-model.md" },
    ],
    areas: ["living-conventions", "definition-authoring-flow", "project-map-governance"],
    rules: [
      {
        id: "typed-source-of-truth",
        statement: "A spec is authored as a TypeScript definition and any OpenCanon-owned Markdown is rendered from that definition.",
        acceptance: ["generated spec docs are deterministic", "definition docs have no hand-edited Markdown opt-out"],
        checks: ["spec-render", "project-doctor"],
      },
      {
        id: "definition-domain-validation",
        statement: "Validators can target explicit runtime domains such as definitions or project state without using empty file globs as the authoring contract.",
        acceptance: ["definition-scoped conventions map to validator domain definition", "project validation runs definition-domain validators once"],
        checks: ["convention-tests", "project-validation"],
      },
      {
        id: "specs-link-governance",
        statement: "Specs link the conventions and checks that keep the described behavior current.",
        acceptance: ["specs can link governing conventions", "doctor and project map can surface spec backlinks"],
        checks: ["definition-graph-tests", "project-doctor"],
      },
      {
        id: "changes-own-task-graphs",
        statement:
          "Implementation task graphs live on Change definitions while task progress is derived from runtime events.",
        acceptance: [
          "tasks can declare checks, files, impact surfaces, dependencies, blockers, and durable definition updates",
          "ready work is derived from dependency state instead of persisted as definition status",
          "task lifecycle and check events include task and check identifiers",
        ],
        checks: ["runtime-client-tests", "definition-graph-tests", "typecheck"],
      },
    ],
    scenarios: [
      {
        id: "agent-implements-feature-from-spec",
        given: ["a repo has a spec with scope, checks, and governing conventions"],
        when: "an agent changes files covered by that spec",
        then: ["OpenCanon can show the related spec", "runtime checks keep the implementation aligned with the spec and conventions"],
        checks: ["project-validation", "definition-graph-tests"],
      },
      {
        id: "agent-follows-ready-change-task",
        given: ["a Change has tasks with dependencies and declared checks"],
        when: "an agent asks for ready work",
        then: ["OpenCanon returns only unblocked work", "the agent can claim a task", "check results and close events update runtime state without editing the Change definition"],
        checks: ["runtime-client-tests", "definition-graph-tests"],
      },
    ],
    checks: [
      { id: "spec-render", kind: "command", command: "npm run opencanon -- canon render specs --dry-run" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --project" },
      { id: "project-doctor", kind: "doctor" },
      { id: "typecheck", kind: "command", command: "npm run check:types" },
      { id: "convention-tests", kind: "test", target: "tests/convention.test.ts" },
      { id: "definition-graph-tests", kind: "test", target: "tests/definition-graph.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
    ],
    governedBy: { inferFromScope: true, conventions: ["spec-definitions-are-enforced", "state-ownership-current", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/specs/spec-governance-model.md", style: "reference" },
  }),
  defineSpec({
    id: "explicit-error-contract-spec",
    title: "Explicit Error Contract Spec",
    summary: "Failed OpenCanon API envelopes expose a single error payload while diagnostics remain valid domain data inside successful responses.",
    surfaces: ["local-service-control", "project-canon-model"],
    scope: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/errors.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/local-protocol.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/conventions/explicit-error-contracts.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/explicit-error-contract-spec.md" },
    ],
    areas: ["explicit-error-contracts", "local-service-and-runtimes"],
    rules: [
      {
        id: "failed-envelope-uses-error",
        statement: "Every transport failure is represented as `{ ok: false, error }`.",
        acceptance: ["runtime HTTP failures use `error`", "service HTTP failures use `error`", "local protocol clients parse `error`"],
        checks: ["contracts-tests", "runtime-client-tests", "service-lifecycle-tests"],
      },
      {
        id: "problem-or-diagnostics",
        statement: "The error payload is discriminated as either `problem` for structured recovery or `diagnostics` for diagnostic lists.",
        acceptance: ["project-open failures use a problem payload", "diagnostic failures use a diagnostics payload", "clients branch on the error discriminant"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
      {
        id: "diagnostics-domain-data-remains-allowed",
        statement: "Successful response bodies and internal parser results may still expose diagnostics as domain data.",
        acceptance: ["Git/history/settings diagnostics remain successful payload fields", "internal parse functions can return diagnostics before route wrapping"],
        checks: ["runtime-client-tests", "project-validation"],
      },
    ],
    scenarios: [
      {
        id: "client-opens-uninitialized-project",
        given: ["a folder exists but is not an initialized OpenCanon project"],
        when: "a CLI, MCP, or browser diagnostics client asks the service to ensure that project",
        then: ["the service returns `error.kind = problem`", "the problem includes the folder path and setup action", "the client can display a predictable recovery flow"],
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
    ],
    checks: [
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "service-lifecycle-tests", kind: "test", target: "packages/runtime/test/service.test.ts" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --project" },
    ],
    governedBy: { inferFromScope: true, conventions: ["explicit-error-contracts", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/specs/explicit-error-contract-spec.md", style: "reference" },
  }),
];
