import { DefinitionTargetKind, defineArea } from "@opencanon/core";

export default [
  defineArea({
    id: "company-read-model",
    title: "Example Company Read Model",
    summary: "The example company read model dogfoods service-boundary conventions without representing OpenCanon product behavior.",
    surfaces: ["company-read-model"],
    owns: [
      { kind: DefinitionTargetKind.File, path: "src/db/dal/company.ts" },
      { kind: DefinitionTargetKind.File, path: "src/api/routes/companies.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/unit/company.test.ts" },
      { kind: DefinitionTargetKind.Endpoint, path: "GET /companies?id", protocol: "http", adapter: "route" },
      { kind: DefinitionTargetKind.Resource, name: "db:companies", type: "database" },
    ],
    stories: [
      {
        id: "read-company-by-id",
        as: "developer",
        want: "company reads to go through the route/service/DAL boundary",
        so: "customer-visible company data stays stable when persistence internals change",
        acceptance: ["route handlers do not import DAL modules", "DAL reads return null for missing companies"],
        checks: ["company-unit-tests", "project-validation"],
      },
    ],
    behaviors: [
      {
        id: "protects-company-contract",
        actor: "route handler",
        action: "reads a company by id",
        outcome: "the response contract is isolated from database schema internals",
        checks: ["company-unit-tests"],
      },
    ],
    checks: [
      { id: "company-unit-tests", kind: "test", target: "tests/unit/company.test.ts" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --project" },
    ],
    governedBy: { conventions: ["no-route-dal-import", "service-db-boundary", "impact-surfaces-current"] },
    render: { kind: "generated", docs: "docs/opencanon/areas/company-read-model.md", style: "reference" },
  }),
  defineArea({
    id: "project-map-governance",
    title: "Project Map Governance",
    summary: "OpenCanon derives the Project Map across areas, changes, conventions, surfaces, checks, validators, and owned targets.",
    surfaces: ["project-canon-model", "project-knowledge-index"],
    owns: [
      { kind: DefinitionTargetKind.File, path: "opencanon/**/*.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/**/*.md" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/definition-graph.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor-checks.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor-types.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/engine/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/snapshot.ts" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/contracts.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/project.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/state.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/migrations/003_product_model.sql" },
      { kind: DefinitionTargetKind.File, path: "tests/definition-graph.test.ts" },
      { kind: DefinitionTargetKind.Resource, name: "definition-graph", type: "runtime-model" },
      { kind: DefinitionTargetKind.Resource, name: "product-model-projection", type: "sqlite-projection" },
    ],
    stories: [
      {
        id: "doctor-sees-definition-drift",
        as: "developer",
        want: "doctor to flag missing links and ownership conflicts",
        so: "the live Project Map does not quietly drift from code",
        acceptance: ["project map diagnostics appear in doctor", "runtime snapshots expose project map backlinks"],
        checks: ["definition-graph-tests", "project-doctor"],
      },
    ],
    behaviors: [
      {
        id: "derives-impact-backlinks",
        actor: "project runtime snapshot",
        action: "loads definitions and impact surfaces",
        outcome: "area, change, convention, and surface backlinks are available to runtime clients and durable project state",
        checks: ["definition-graph-tests"],
      },
    ],
    checks: [
      { id: "definition-graph-tests", kind: "test", target: "tests/definition-graph.test.ts" },
      { id: "engine-product-model-tests", kind: "test", target: "crates/opencanon-engine/src/tests.rs" },
      { id: "engine-wrapper-tests", kind: "test", target: "packages/runtime/test/engine.test.ts" },
      { id: "runtime-state-tests", kind: "test", target: "packages/runtime/test/state.test.ts" },
      { id: "project-doctor", kind: "doctor" },
    ],
    governedBy: { inferFromScope: true, conventions: ["impact-surfaces-current", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/areas/project-map-governance.md", style: "reference" },
  }),
  defineArea({
    id: "project-knowledge-index",
    title: "Project Knowledge",
    summary: "OpenCanon owns search, chunks, embeddings, vector storage, and related-code retrieval as derived project runtime state tied back to definitions.",
    surfaces: ["project-knowledge-index"],
    owns: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/semantic-index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/semantic-models.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/project-context.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/knowledge-producers.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/semantic-index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/state.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/semantic-index.test.ts" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/migrations/005_knowledge_index.sql" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/migrations/006_knowledge_hybrid.sql" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-vector/**" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-inference/**" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon-architecture.md" },
      { kind: DefinitionTargetKind.Endpoint, path: "/api/context/status", protocol: "http", adapter: "runtime" },
      { kind: DefinitionTargetKind.Endpoint, path: "/api/context/search", protocol: "http", adapter: "runtime" },
      { kind: DefinitionTargetKind.Endpoint, path: "/api/context/ask", protocol: "http", adapter: "runtime" },
      { kind: DefinitionTargetKind.Endpoint, path: "/api/context/chunks", protocol: "http", adapter: "runtime" },
      { kind: DefinitionTargetKind.Endpoint, path: "/api/context/coverage", protocol: "http", adapter: "runtime" },
      { kind: DefinitionTargetKind.Endpoint, path: "/api/context/backlinks", protocol: "http", adapter: "runtime" },
      { kind: DefinitionTargetKind.Resource, name: "semantic-index", type: "runtime-state" },
      { kind: DefinitionTargetKind.Resource, name: "semantic-chunks", type: "runtime-state" },
      { kind: DefinitionTargetKind.Resource, name: "vector-store", type: "runtime-state" },
    ],
    stories: [
      {
        id: "search-related-code-through-definitions",
        as: "developer",
        want: "search and related-code results to point back to definitions, checks, and surfaces",
        so: "search helps agents and humans navigate without becoming a separate source of truth",
        acceptance: ["Knowledge chunks are derived from project files and facts", "search results can be scoped by paths", "doctor reports Knowledge health"],
        checks: ["semantic-index-tests", "project-doctor"],
      },
      {
        id: "grounded-search-and-ask",
        as: "developer",
        want: "Search and Ask to show evidence, citations, freshness, and backlinks",
        so: "I can understand project behavior without treating generated answers as enforcement",
        acceptance: ["answers cite retrieved evidence", "stale context state is visible", "suggested backlinks remain proposals"],
        checks: ["semantic-index-tests", "project-doctor"],
      },
    ],
    behaviors: [
      {
        id: "derived-context-substrate",
        actor: "project runtime",
        action: "indexes project files and generated docs",
        outcome: "chunks, embeddings, and lexical search rows are rebuilt from committed definitions and current files",
        checks: ["semantic-index-tests"],
      },
      {
        id: "advisory-search-results",
        actor: "OpenCanon search",
        action: "returns semantic or lexical matches",
        outcome: "results are treated as context until a deterministic check, gate, validator, or test enforces the claim",
        checks: ["project-doctor"],
      },
      {
        id: "deterministic-validator-context",
        actor: "validator runtime",
        action: "queries Project Knowledge",
        outcome: "blocking findings depend on deterministic files, facts, definitions, surfaces, chunks, freshness, coverage, or backlinks",
        checks: ["project-doctor"],
      },
    ],
    checks: [
      { id: "semantic-index-tests", kind: "test", target: "packages/runtime/test/semantic-index.test.ts" },
      { id: "engine-semantic-index-tests", kind: "test", target: "crates/opencanon-engine/src/tests.rs" },
      { id: "project-doctor", kind: "doctor" },
    ],
    governedBy: { inferFromScope: true, conventions: ["project-knowledge-boundary-current", "state-ownership-current", "product-language-current"] },
    render: { kind: "generated", docs: "docs/opencanon/areas/project-knowledge-index.md", style: "reference" },
  }),
  defineArea({
    id: "local-service-and-runtimes",
    title: "Local Service and Project Runtimes",
    summary: "The OpenCanon local service discovers projects and lazily starts isolated per-project runtimes.",
    surfaces: ["local-service-control"],
    owns: [
      { kind: DefinitionTargetKind.File, path: "packages/service-contracts/**" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/local-protocol.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/runtime-client.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/service.test.ts" },
      { kind: DefinitionTargetKind.Endpoint, path: "/api/projects/ensure", protocol: "http", adapter: "service" },
      { kind: DefinitionTargetKind.Endpoint, path: "/api/projects/request", protocol: "http", adapter: "service" },
      { kind: DefinitionTargetKind.Endpoint, path: "/api/projects/events/stream", protocol: "http", adapter: "service" },
      { kind: DefinitionTargetKind.Command, name: "opencanon service", adapter: "cli" },
      { kind: DefinitionTargetKind.Command, name: "opencanon project", adapter: "cli" },
    ],
    stories: [
      {
        id: "lazy-project-runtime",
        as: "developer",
        want: "OpenCanon commands to start the project runtime on demand",
        so: "projects do not require manually managed background processes",
        acceptance: [
          "service registry records runtime identity",
          "large context requests move through the local protocol",
          "project start succeeds only after runtime health is ready",
          "non-retryable project failures remain terminal until the project is repaired",
        ],
        checks: ["runtime-client-tests", "project-doctor"],
      },
    ],
    behaviors: [
      {
        id: "large-related-context-request",
        actor: "CLI",
        action: "requests related context for a large change set",
        outcome: "the request uses the local protocol without exceeding HTTP query/header limits",
        checks: ["runtime-client-tests"],
      },
      {
        id: "project-event-stream-is-explicit",
        actor: "local service",
        action: "proxies project runtime events to CLI, MCP, and diagnostics clients",
        outcome: "transport close or failure is reported as an explicit event-stream error instead of being masked by stale project data",
        checks: ["runtime-client-tests", "service-lifecycle-tests"],
      },
      {
        id: "project-worker-single-owner",
        actor: "local service",
        action: "starts or repairs a project runtime",
        outcome: "one project worker owns the repo state before SQLite opens, while stale or duplicate workers are retired",
        checks: ["service-lifecycle-tests"],
      },
      {
        id: "project-start-is-readiness-contract",
        actor: "CLI, MCP, or app client",
        action: "asks the local service to ensure a project runtime",
        outcome: "success means verified ready; failure preserves a typed cause, retry policy, project path, and recovery action",
        checks: ["runtime-client-tests", "service-lifecycle-tests"],
      },
    ],
    checks: [
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "service-lifecycle-tests", kind: "test", target: "packages/runtime/test/service.test.ts" },
      { id: "project-doctor", kind: "doctor" },
    ],
    governedBy: { inferFromScope: true, conventions: ["framework-package-boundaries", "service-events-current"] },
    render: { kind: "generated", docs: "docs/opencanon/areas/local-service-and-runtimes.md", style: "reference" },
  }),
  defineArea({
    id: "explicit-error-contracts",
    title: "Explicit Error Contracts",
    summary: "OpenCanon runtime, service, local protocol, CLI, and MCP failures use a single `{ ok: false, error }` envelope.",
    surfaces: ["local-service-control", "project-canon-model"],
    owns: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/errors.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/result.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/branch.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/safe-json.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/retry.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/singleflight.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/concurrency.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/conventions/explicit-error-contracts.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/areas/explicit-error-contracts.md" },
      { kind: DefinitionTargetKind.Endpoint, path: "/api/* failure envelope", protocol: "http", adapter: "runtime" },
      { kind: DefinitionTargetKind.Endpoint, path: "/api/projects/* failure envelope", protocol: "http", adapter: "service" },
      { kind: DefinitionTargetKind.Resource, name: "runtime-error-envelope", type: "protocol-contract" },
    ],
    stories: [
      {
        id: "predictable-project-open-errors",
        as: "developer",
        want: "project-open and runtime failures to carry structured problem or diagnostic payloads",
        so: "CLI, MCP, and browser diagnostics can show explicit recovery steps without guessing from strings",
        acceptance: ["project-open failures carry `error.kind = problem`", "diagnostic failures carry `error.kind = diagnostics`", "successful payload diagnostics remain domain data"],
        checks: ["service-lifecycle-tests", "runtime-client-tests", "contracts-tests"],
      },
    ],
    behaviors: [
      {
        id: "failure-envelope-is-explicit",
        actor: "runtime or service API",
        action: "returns a failed response",
        outcome: "the response is `{ ok: false, error }`; top-level diagnostics are not used for transport failures",
        checks: ["contracts-tests", "runtime-client-tests"],
      },
      {
        id: "problem-errors-drive-client-recovery",
        actor: "runtime client",
        action: "opens an uninitialized project",
        outcome: "the client receives a structured problem with code, path, action, retryability, and status",
        checks: ["service-lifecycle-tests", "runtime-client-tests"],
      },
    ],
    checks: [
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "service-lifecycle-tests", kind: "test", target: "packages/runtime/test/service.test.ts" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --project" },
    ],
    governedBy: { inferFromScope: true, conventions: ["explicit-error-contracts", "tests-follow-risk"] },
    render: { kind: "generated", docs: "docs/opencanon/areas/explicit-error-contracts.md", style: "reference" },
  }),
  defineArea({
    id: "living-conventions",
    title: "Living Conventions",
    summary: "Conventions are typed definitions that can render human docs and enforce runtime validators, gates, or tests.",
    surfaces: ["project-canon-model"],
    owns: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/convention.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/convention-render.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/render-links.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validator-graph.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validation.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/conventions/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/conventions/docs-only-conventions.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/canon/architecture.md" },
      { kind: DefinitionTargetKind.File, path: "tests/convention.test.ts" },
      { kind: DefinitionTargetKind.Command, name: "opencanon canon", adapter: "cli" },
      { kind: DefinitionTargetKind.Command, name: "opencanon validate", adapter: "cli" },
    ],
    stories: [
      {
        id: "generated-docs-stay-current",
        as: "maintainer",
        want: "generated convention docs to match definitions exactly",
        so: "humans and agents read the same current canon",
        acceptance: ["doctor detects stale generated docs", "runtime validators adapt from convention definitions"],
        checks: ["convention-tests", "project-doctor"],
      },
    ],
    behaviors: [
      {
        id: "runtime-axis-enforces",
        actor: "validator runtime",
        action: "loads a convention with runtime validation",
        outcome: "findings and gates are produced from the convention definition",
        checks: ["convention-tests"],
      },
    ],
    checks: [
      { id: "convention-tests", kind: "test", target: "tests/convention.test.ts" },
      { id: "project-doctor", kind: "doctor" },
    ],
    governedBy: { inferFromScope: true },
    render: { kind: "generated", docs: "docs/opencanon/areas/living-conventions.md", style: "reference" },
  }),
  defineArea({
    id: "product-docs-and-guidance",
    title: "Product Docs and Agent Guidance",
    summary: "The public docs, README, managed skill, and product copy explain OpenCanon as agent-ready, human-readable, runtime-enforced Project Canon, Proof, Knowledge, Activity, and Health.",
    owns: [
      { kind: DefinitionTargetKind.File, path: "README.md" },
      { kind: DefinitionTargetKind.File, path: "CHANGELOG.md" },
      { kind: DefinitionTargetKind.File, path: "SECURITY.md" },
      { kind: DefinitionTargetKind.File, path: "NOTICE.md" },
      { kind: DefinitionTargetKind.File, path: "docs/*.md" },
      { kind: DefinitionTargetKind.Doc, path: ".agents/skills/opencanon/SKILL.md" },
      { kind: DefinitionTargetKind.Doc, path: "AGENTS.md" },
      { kind: DefinitionTargetKind.Doc, path: "CLAUDE.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/areas/product-docs-and-guidance.md" },
    ],
    stories: [
      {
        id: "plain-product-framing",
        as: "developer",
        want: "docs and agent guidance to use the same product vocabulary as the CLI",
        so: "I can understand what OpenCanon does before learning internal architecture",
        acceptance: ["README and managed agent entries use Project Canon, Proof, Knowledge, Activity, and Health consistently", "generated docs remain derived from definitions"],
        checks: ["project-doctor"],
      },
    ],
    behaviors: [
      {
        id: "guidance-matches-cli-language",
        actor: "agent guidance",
        action: "describes OpenCanon concepts",
        outcome: "product-facing language matches CLI commands and generated Project Canon docs",
        checks: ["project-doctor"],
      },
    ],
    checks: [
      { id: "project-doctor", kind: "doctor" },
    ],
    governedBy: { inferFromScope: true, conventions: ["product-language-current", "state-ownership-current"] },
    render: { kind: "generated", docs: "docs/opencanon/areas/product-docs-and-guidance.md", style: "reference" },
  }),
  defineArea({
    id: "definition-authoring-flow",
    title: "Definition Authoring Flow",
    summary: "OpenCanon provides project-local authoring support and draft commands for conventions, areas, and change definitions.",
    owns: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/project-types.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/project-types-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/setup.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/areas.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/changes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/changes-definition.ts" },
      { kind: DefinitionTargetKind.Doc, path: ".agents/skills/opencanon/SKILL.md" },
      { kind: DefinitionTargetKind.Command, name: "opencanon canon draft convention", adapter: "cli" },
      { kind: DefinitionTargetKind.Command, name: "opencanon canon draft area", adapter: "cli" },
      { kind: DefinitionTargetKind.Command, name: "opencanon canon draft change", adapter: "cli" },
    ],
    stories: [
      {
        id: "draft-typed-definitions",
        as: "developer",
        want: "draft commands and generated authoring support",
        so: "new canon can be written by agents or humans without memorizing every type shape",
        acceptance: ["canon draft convention prints a compile-ready definition skeleton", "canon draft area and canon draft change print deterministic snippets", "project authoring support remains generated state"],
        checks: ["convention-tests", "project-doctor"],
      },
    ],
    behaviors: [
      {
        id: "authoring-state-is-derived",
        actor: "init and project runtime",
        action: "write authoring declaration files automatically",
        outcome: "generated files stay under .opencanon/generated and out of committed source",
        checks: ["project-doctor"],
      },
    ],
    checks: [
      { id: "convention-tests", kind: "test", target: "tests/convention.test.ts" },
      { id: "project-doctor", kind: "doctor" },
    ],
    governedBy: { inferFromScope: true, conventions: ["state-ownership-current", "product-language-current"] },
    render: { kind: "generated", docs: "docs/opencanon/areas/definition-authoring-flow.md", style: "reference" },
  }),
  defineArea({
    id: "agent-feedback-and-gates",
    title: "Agent Feedback and Gates",
    summary: "Agent hooks and CLI feedback surface related conventions, impact surfaces, findings, and explicit approval gates.",
    owns: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/feedback.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/commit-approvals.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/hook-install.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/feedback.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/gate.ts" },
      { kind: DefinitionTargetKind.Command, name: "opencanon feedback", adapter: "cli" },
      { kind: DefinitionTargetKind.Command, name: "opencanon gate", adapter: "cli" },
    ],
    stories: [
      {
        id: "feedback-after-edits",
        as: "agent",
        want: "concise feedback after editing files",
        so: "I can correct drift before commit",
        acceptance: ["feedback includes related changes and impact surfaces", "unresolved gates are persisted for approval"],
        checks: ["feedback-tests", "project-doctor"],
      },
    ],
    behaviors: [
      {
        id: "commit-gate-records-user-intent",
        actor: "commit gate",
        action: "requires approval for sensitive changes",
        outcome: "approval context is recorded outside committed canon definitions",
        checks: ["feedback-tests"],
      },
    ],
    checks: [
      { id: "feedback-tests", kind: "test", target: "tests/feedback.test.ts" },
      { id: "project-doctor", kind: "doctor" },
    ],
    governedBy: { inferFromScope: true, conventions: ["sensitive-change-requires-approval"] },
    render: { kind: "generated", docs: "docs/opencanon/areas/agent-feedback-and-gates.md", style: "reference" },
  }),
  defineArea({
    id: "runtime-release-update",
    title: "Runtime Updates",
    summary: "Runtime updates are selected from signed manifests with target-specific SHA-256 bundles.",
    surfaces: ["release-update"],
    owns: [
      { kind: DefinitionTargetKind.File, path: "package.json" },
      { kind: DefinitionTargetKind.File, path: "package-lock.json" },
      { kind: DefinitionTargetKind.File, path: "packages/*/package.json" },
      { kind: DefinitionTargetKind.File, path: "packages/distribution/src/update.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/distribution/src/node.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/distribution/package.json" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/update.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/package.json" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/release-manifest.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/release-keys.ts" },
      { kind: DefinitionTargetKind.File, path: "scripts/**" },
      { kind: DefinitionTargetKind.File, path: "packages/distribution/test/update.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/update-guard.test.ts" },
      { kind: DefinitionTargetKind.Command, name: "opencanon update", adapter: "cli" },
    ],
    stories: [
      {
        id: "targeted-runtime-install",
        as: "developer",
        want: "updates to select the current platform bundle automatically",
        so: "runtime and engine versions stay in lockstep",
        acceptance: [
          "manifest checks validate hashes",
          "install rehearsal verifies runtime layout",
          "the CLI supplies service and project runtime safety guards before writes",
          "installed updates report the Doctor fix command for managed project artifacts",
        ],
        checks: ["release-update-tests", "release-check"],
      },
    ],
    behaviors: [
      {
        id: "refuses-unsafe-update",
        actor: "updater",
        action: "applies a runtime bundle",
        outcome: "hash or signature failures stop before replacing installed files",
        checks: ["release-update-tests"],
      },
      {
        id: "reports-project-refresh-action",
        actor: "updater",
        action: "installs a new runtime bundle",
        outcome: "the apply result reports opencanon doctor --fix as the only managed-project-artifact repair path",
        checks: ["release-update-tests"],
      },
    ],
    checks: [
      { id: "release-update-tests", kind: "test", target: "tests/release-update-e2e.test.ts" },
      { id: "release-check", kind: "command", command: "npm run release:check" },
    ],
    governedBy: { inferFromScope: true, conventions: ["hardcoded-secrets-and-config"] },
    render: { kind: "generated", docs: "docs/opencanon/areas/runtime-release-update.md", style: "reference" },
  }),
];
