export type {
  ContextConfig,
  ContextPaths,
  ContextReferenceValidator,
  ContextValidationInput,
  Baseline,
  ChangePolicy,
  Decision,
  ImpactSurface,
  Format,
  ProposedImpactNote,
} from "./context.ts";
export type { FileDiscoveryMode, ProjectFileDiscovery } from "./discovery.ts";
export type { DocSnippet } from "./docs.ts";
export {
  createDefaultConfig,
  createPaths,
  loadBaseline,
  loadConfig,
  loadContextFiles,
  loadImpactSurfaces,
  loadProposedImpactNotes,
  resolveRootDir,
  validateConfig,
  validateContext,
  validateImpactSurfaces,
} from "./context.ts";
export { fail } from "./core.ts";
export { explainGlobMatches, intersects, matchesAny, matchesAnyFile, pathToImportUrl, relative, splitList, toRepoRelativePath, unique } from "./core-utils.ts";
export {
  discoverProjectFiles,
  FileDiscoveryMode,
  listFiles,
  listProjectFiles,
  matchesProjectFileScope,
} from "./discovery.ts";
export {
  normalizeMarkdownHeading,
  parseMarkdownDoc,
  resolveDocsReferences,
} from "./docs.ts";
export type { GitCommitInfo, GitFileDiff, GitFileHistory } from "./git.ts";
export { getChangedFiles, getGitFileDiff, getGitFileHistory, getGitRoot } from "./git.ts";
export type {
  BuildRepoGraphRequest,
  BuildRepoGraphResult,
  CallFact,
  CanonDecision,
  CanonBundle,
  CanonBundleDocs,
  CanonBundleFile,
  CanonBundleOption,
  CanonBundleOptionValue,
  CanonEvent,
  CanonFinding,
  CanonFix,
  CommentFact,
  ContextRequest,
  DaemonHealth,
  DaemonResponse,
  DaemonState,
  DiagnosticSeverity,
  DiagnosticFact,
  DomainEdge,
  DuplicateFact,
  ChangePolicy as ContractChangePolicy,
  CanonDocSnippet,
  ExportFact,
  ExtractFactsRequest,
  ExtractFactsResult,
  FactDiagnostic,
  FactKind,
  FileFacts,
  FindingKind,
  ImpactSurface as ContractImpactSurface,
  ImportEdgeFact,
  ImportFact,
  Language,
  LiteralFact,
  ProposedImpactNote as ContractProposedImpactNote,
  ReferenceFact,
  AnnotationFact,
  BaselineFinding,
  Baseline as ContractBaseline,
  ExternalTool,
  ExternalToolMissingSeverity,
  EngineVersion,
  EngineProjectStatus,
  OpenProjectRequest,
  Position,
  Recommendation,
  RepoGraph,
  ResolvedProjectSettings,
  ScanAndDiffRequest,
  ScanAndDiffResult,
  SymbolFact,
  ValidateRequest,
  ValidatorContract,
  ValidatorScope,
  WatcherEventBatch,
  WatcherStartRequest,
  WatcherStartResult,
  WatcherStatus,
  WorkspaceNode,
} from "./contracts.ts";
export {
  AnnotationFactSchema,
  BaselineFindingSchema,
  BaselineSchema,
  BuildRepoGraphRequestSchema,
  BuildRepoGraphResultSchema,
  CallFactSchema,
  CanonBundleDocsSchema,
  CanonBundleFileSchema,
  CanonBundleOptionSchema,
  CanonBundleOptionType,
  CanonBundleOptionValueSchema,
  CanonBundleSchema,
  CanonEventSchema,
  CanonFindingSchema,
  CanonFixSchema,
  CommentFactSchema,
  ContextRequestSchema,
  DaemonFailureSchema,
  DaemonHealthSchema,
  DaemonResponseSchema,
  DaemonStateSchema,
  DaemonSuccessSchema,
  DecisionSchema,
  DiagnosticSeverity,
  DiagnosticFactSchema,
  DocSnippetSchema,
  DomainEdgeSchema,
  DuplicateFactSchema,
  ChangePolicySchema,
  ExternalToolSchema,
  ExternalToolCommandSchema,
  ExternalToolDefinitionSchema,
  ExportFactSchema,
  ExtractFactsRequestSchema,
  ExtractFactsResultSchema,
  FactDiagnosticSchema,
  FactKindSchema,
  FileFactsSchema,
  FindingKindSchema,
  ImpactSurfaceSchema,
  ImportEdgeFactSchema,
  ImportFactSchema,
  LanguageSchema,
  LiteralFactSchema,
  ProposedImpactNoteSchema,
  ReferenceFactSchema,
  EngineVersionSchema,
  EngineProjectStatusSchema,
  OpenProjectRequestSchema,
  PositionSchema,
  RecommendationSchema,
  RepoGraphSchema,
  ResolvedProjectSettingsSchema,
  ScanAndDiffRequestSchema,
  ScanAndDiffResultSchema,
  SymbolFactSchema,
  ValidateRequestSchema,
  ValidatorContractSchema,
  ValidatorScopeSchema,
  WatcherEventBatchSchema,
  WatcherStartRequestSchema,
  WatcherStartResultSchema,
  WatcherStatusSchema,
  WorkspaceNodeSchema,
  factKindValues,
  canonBundleOptionTypeValues,
  diagnosticSeverityValues,
  externalToolMissingSeverityValues,
  languageValues,
  validatorSeverityValues,
  validatorScopeValues,
} from "./contracts.ts";
export type { ResolvedExternalTool } from "./external-tools.ts";
export { normalizeExternalTool, resolveExternalTool, validateExternalTool } from "./external-tools.ts";
export type { OpenCanonDiagnostic, OpenCanonErrorCode, OpenCanonFailure } from "./errors.ts";
export {
  OpenCanonDiagnosticSchema,
  OpenCanonError,
  OpenCanonErrorCodeSchema,
  OpenCanonFailureSchema,
  createOpenCanonDiagnostic,
  createOpenCanonFailure,
  formatOpenCanonDiagnostics,
  openCanonErrorCodeValues,
  throwOpenCanonError,
} from "./errors.ts";
export { writeAtomicBinaryFileSync, writeAtomicJsonFileSync, writeAtomicTextFileSync } from "./atomic.ts";
export type { ResolvedInsideRootResult, SafeRelativePathResult } from "./paths.ts";
export { resolveInsideRoot, safeRelativePath } from "./paths.ts";
export type {
  CommentInfo,
  BaselineApi,
  DomainEdge as ValidatorDomainEdge,
  FactsApi,
  Finding,
  FindingFix,
  FixSafety,
  FolderInfo,
  ImpactApi,
  ImpactRequiredChecks,
  ImportEdge,
  JsonRead,
  ProjectAnnotationFact,
  ProjectCallFact,
  ProjectComment,
  ProjectDiagnosticFact,
  ProjectDuplicateFact,
  ProjectExportFact,
  ProjectFile,
  ProjectLiteralFact,
  ProjectReferenceFact,
  ProjectSymbolFact,
  ReportInput,
  Severity,
  TextMatch,
  TextEdit,
  FileRead,
  ValidationContext,
  Validator,
  ValidatorArgs,
  ValidatorDefinition,
  ValidatorFactory,
  ValidatorFactoryBaseOptions,
  FindingValidationContext,
  ValidatorRuntime,
  ValidatorSummary,
  ValidatorSummaryInput,
  ValidatorVisual,
  WorkspaceGraph,
  WorkspaceKind,
  WorkspacePackage,
} from "./validator.ts";
export {
  createValidatorFactory,
  createRuntime,
  createValidationContext,
  createValidationContextFromFixture,
  defineValidator,
  flushValidationContextCache,
  formatValidatorApplies,
  resolveValidators,
  validateFindings,
  validateValidatorDefinitions,
  validatorMatchesAnyFile,
  validatorMatchesFile,
} from "./validator.ts";
export type { FixApplicationResult, FixMode } from "./fixes.ts";
export { applyFindingFixes, FixModeValue, isFixAllowed } from "./fixes.ts";
export type {
  EnumMemberInfo,
  ExportInfo,
  FunctionInfo,
  InitializerInfo,
  ImportInfo,
  LiteralContext,
  LiteralInfo,
  ObjectPropertyInfo,
  TypeScriptDeclaration,
  TypeScriptEnumDeclaration,
  TypeScriptVariableDeclaration,
} from "./typescript.ts";
export type { TreeBoundaryRule, TreeDefinition, TreeFileRules, TreeFolderRules, TreeGraphDefinition, TreeImportRules, TreeNode, TreePathDefinition } from "./tree.ts";
export { tree, validateTree, validateTreeDefinition } from "./tree.ts";
export type { DoctorCheck, DoctorFixResult, DoctorReport, DoctorStatus } from "./doctor.ts";
export { applyDoctorFixes, buildDoctorReport, DoctorStatus, renderDoctorFixMarkdown, renderDoctorMarkdown } from "./doctor.ts";
export type { AnalysisCache } from "./cache.ts";
export { getAnalysisCache } from "./cache.ts";
export type { LazyValue } from "./lazy.ts";
export { lazy } from "./lazy.ts";
export type { Resource, ResourceOptions, ResourceSignal } from "./resource.ts";
export { resource } from "./resource.ts";
export { defineCanonBundle } from "./bundles.ts";
export type { ProfileEntry, Profiler } from "./profiler.ts";
export { createProfiler, renderProfileMarkdown } from "./profiler.ts";
export type { ProjectContext } from "./project.ts";
export { loadProjectContext, loadValidators } from "./project.ts";
export type { FeedbackDedupeScope, FeedbackHost, FeedbackInput, FeedbackRenderOptions, FeedbackResult } from "./feedback.ts";
export { formatFeedbackResult, renderFeedbackMarkdown, runFeedback } from "./feedback.ts";
export type { HookFileAction, HookInspection, HookInstallFileResult, HookInstallHost, HookInstallResult, HookInstallScope } from "./hook-install.ts";
export {
  claudeHookConfig,
  codexHookConfig,
  HookInstallHost,
  HookInstallScope,
  installHook,
  inspectHookInstallations,
  openCodePluginSource,
  renderHookInspectionMarkdown,
  renderHookInstallResult,
} from "./hook-install.ts";
export type { HookFeedback } from "./hooks.ts";
export { appendOpenCodeFeedback, createHookFeedback, extractFilesFromPatchText, normalizeHookPayload, renderHookResponse } from "./hooks.ts";
export type { ValidationInput, ValidationResult } from "./validation.ts";
export { runValidation, selectValidators, sortFindings } from "./validation.ts";
