export type ProjectTypesGeneratedEntry = {
  key: string;
  value: unknown;
  docs: string[];
};

export type ProjectTypesAmbientModuleDeclaration = {
  source: string;
  namedExports: string[];
  defaultExport: boolean;
  namespaceExport: boolean;
};

export function renderProjectTypes(input: {
  packages: ProjectTypesGeneratedEntry[];
  packageRoots: ProjectTypesGeneratedEntry[];
  importSpecifiers: ProjectTypesGeneratedEntry[];
  npmDependencies: ProjectTypesGeneratedEntry[];
  crates: ProjectTypesGeneratedEntry[];
  crateRoots: ProjectTypesGeneratedEntry[];
  cargoDependencies: ProjectTypesGeneratedEntry[];
  pythonDependencies: ProjectTypesGeneratedEntry[];
}): string {
  return [
    "// Generated by OpenCanon. Do not edit by hand.",
    "import \"@opencanon/core\";",
    "",
    "/** Workspace package names discovered from package.json files. */",
    renderConstObject("Packages", input.packages),
    "",
    "/** Literal union of generated workspace package names. */",
    "export type PackageName = (typeof Packages)[keyof typeof Packages];",
    "/** Literal union of generated workspace package keys. */",
    "export type PackageKey = keyof typeof Packages;",
    "",
    "/** Workspace package root directories keyed the same way as `Packages`. */",
    renderConstObject("PackageRoots", input.packageRoots),
    "",
    "/** Literal union of generated workspace package roots. */",
    "export type PackageRoot = (typeof PackageRoots)[keyof typeof PackageRoots];",
    "/** Literal union of generated package root keys. */",
    "export type PackageRootKey = keyof typeof PackageRoots;",
    "",
    "/** Import specifiers discovered from workspace packages and declared dependencies. */",
    renderConstObject("ImportSpecifiers", input.importSpecifiers),
    "",
    "/** Literal union of generated import specifier strings. */",
    "export type ImportSpecifier = (typeof ImportSpecifiers)[keyof typeof ImportSpecifiers];",
    "/** Literal union of generated import specifier keys. */",
    "export type ImportSpecifierKey = keyof typeof ImportSpecifiers;",
    "",
    "/** npm dependencies discovered from package.json dependency sections. Values include `name` and declared `version`. */",
    renderConstObject("Npm", input.npmDependencies),
    "",
    "/** Literal union of generated npm dependency objects. */",
    "export type NpmDependency = (typeof Npm)[keyof typeof Npm];",
    "/** Literal union of generated npm dependency package names. */",
    "export type NpmDependencyName = NpmDependency[\"name\"];",
    "/** Literal union of generated npm dependency version ranges. */",
    "export type NpmDependencyVersion = NpmDependency[\"version\"];",
    "/** Literal union of generated npm dependency keys. */",
    "export type NpmDependencyKey = keyof typeof Npm;",
    "",
    "/** Rust crate names discovered from Cargo manifests. */",
    renderConstObject("Crates", input.crates),
    "",
    "/** Literal union of generated Rust crate names. */",
    "export type CrateName = (typeof Crates)[keyof typeof Crates];",
    "/** Literal union of generated Rust crate keys. */",
    "export type CrateKey = keyof typeof Crates;",
    "",
    "/** Rust crate root directories keyed the same way as `Crates`. */",
    renderConstObject("CrateRoots", input.crateRoots),
    "",
    "/** Literal union of generated Rust crate roots. */",
    "export type CrateRoot = (typeof CrateRoots)[keyof typeof CrateRoots];",
    "/** Literal union of generated Rust crate root keys. */",
    "export type CrateRootKey = keyof typeof CrateRoots;",
    "",
    "/** Cargo dependencies discovered from dependency sections in Cargo manifests. Values include `name`, `version`, and `section`. */",
    renderConstObject("Cargo", input.cargoDependencies),
    "",
    "/** Literal union of generated Cargo dependency objects. */",
    "export type CargoDependency = (typeof Cargo)[keyof typeof Cargo];",
    "/** Literal union of generated Cargo dependency names. */",
    "export type CargoDependencyName = CargoDependency[\"name\"];",
    "/** Literal union of generated Cargo dependency version requirements. */",
    "export type CargoDependencyVersion = CargoDependency[\"version\"];",
    "/** Literal union of generated Cargo dependency sections. */",
    "export type CargoDependencySection = CargoDependency[\"section\"];",
    "/** Literal union of generated Cargo dependency keys. */",
    "export type CargoDependencyKey = keyof typeof Cargo;",
    "",
    "/** Python dependencies discovered from pyproject.toml and requirements files. Values include `name`, `version`, `source`, and `group`. */",
    renderConstObject("Python", input.pythonDependencies),
    "",
    "/** Literal union of generated Python dependency objects. */",
    "export type PythonDependency = (typeof Python)[keyof typeof Python];",
    "/** Literal union of generated Python dependency names. */",
    "export type PythonDependencyName = PythonDependency[\"name\"];",
    "/** Literal union of generated Python dependency version specifiers. */",
    "export type PythonDependencyVersion = PythonDependency[\"version\"];",
    "/** Literal union of generated Python dependency sources. */",
    "export type PythonDependencySource = PythonDependency[\"source\"];",
    "/** Literal union of generated Python dependency groups. */",
    "export type PythonDependencyGroup = PythonDependency[\"group\"];",
    "/** Literal union of generated Python dependency keys. */",
    "export type PythonDependencyKey = keyof typeof Python;",
    "",
    "/** Lightweight type-only project index. Fact maps are intentionally empty by default to keep editors responsive. */",
    renderProjectIndexType(),
    "",
    "/** Literal union of generated indexed file paths. */",
    "export type ProjectFilePath = keyof ProjectIndex[\"files\"] & string;",
    "/** Import source literals for one indexed file. */",
    "export type ImportSourceIn<F extends ProjectFilePath> = ProjectIndex[\"files\"][F][\"imports\"];",
    "/** Export name literals for one indexed file. */",
    "export type ExportNameIn<F extends ProjectFilePath> = ProjectIndex[\"files\"][F][\"exports\"];",
    "/** Function name literals for one indexed file. */",
    "export type FunctionNameIn<F extends ProjectFilePath> = ProjectIndex[\"files\"][F][\"functions\"];",
    "/** String literal value literals for one indexed file. */",
    "export type StringLiteralIn<F extends ProjectFilePath> = ProjectIndex[\"files\"][F][\"stringLiterals\"];",
    "/** Symbol name literals for one indexed file. */",
    "export type SymbolNameIn<F extends ProjectFilePath> = ProjectIndex[\"files\"][F][\"symbols\"];",
    "/** Call callee literals for one indexed file. */",
    "export type CallNameIn<F extends ProjectFilePath> = ProjectIndex[\"files\"][F][\"calls\"];",
    "",
    "type LookupValues<T> = T extends Record<string, infer V> ? V : never;",
    "type FileLookupValues<T> = T extends Record<string, infer PerFile> ? LookupValues<PerFile> : never;",
    "",
    "/** Generated import records derived from the per-file lookup map. */",
    "export type ProjectImportRecord = FileLookupValues<ProjectIndex[\"imports\"]>;",
    "",
    "/** Generated export records derived from the per-file lookup map. */",
    "export type ProjectExportRecord = FileLookupValues<ProjectIndex[\"exports\"]>;",
    "",
    "/** Generated function records derived from the per-file lookup map. */",
    "export type ProjectFunctionRecord = FileLookupValues<ProjectIndex[\"functions\"]>;",
    "",
    "/** Generated string literal records derived from the per-file lookup map. */",
    "export type ProjectStringLiteralRecord = FileLookupValues<ProjectIndex[\"stringLiterals\"]>;",
    "",
    "/** Generated symbol records derived from the symbol-id lookup map. */",
    "export type ProjectSymbolRecord = LookupValues<ProjectIndex[\"symbols\"]>;",
    "",
    "/** Generated call records derived from the per-file lookup map. */",
    "export type ProjectCallRecord = FileLookupValues<ProjectIndex[\"calls\"]>;",
    "",
    "/** Stable symbol id literals from the generated project index. */",
    "export type ProjectSymbolId = ProjectIndex[\"symbolIds\"];",
    "",
    "declare module \"@opencanon/core\" {",
    "  interface OpenCanonProjectIndex extends ProjectIndex {}",
    "}",
    "",
  ].join("\n");
}

function renderProjectIndexType(): string {
  const lines = ["export type ProjectIndex = {"];
  lines.push("  files: Record<string, import(\"@opencanon/core\").OpenCanonProjectIndexFile>;");
  lines.push("  symbolIds: string;");
  lines.push("  imports: {};");
  lines.push("  exports: {};");
  lines.push("  functions: {};");
  lines.push("  stringLiterals: {};");
  lines.push("  symbols: {};");
  lines.push("  calls: {};");
  lines.push("};");
  return lines.join("\n");
}

function renderConstObject(name: string, entries: ProjectTypesGeneratedEntry[]): string {
  const lines = [`export const ${name} = {`];
  for (const entry of entries) {
    lines.push(...renderJsDoc(entry.docs, "  "));
    lines.push(`  ${entry.key}: ${JSON.stringify(entry.value)},`);
  }
  lines.push("} as const;");
  return lines.join("\n");
}

export function renderAmbientAliases(modules: ProjectTypesAmbientModuleDeclaration[]): string {
  const lines = [
    "// Generated by OpenCanon. Do not edit by hand.",
    "// Ambient declarations for fixture and convention authoring imports.",
    "",
  ];
  for (const item of modules) {
    lines.push(`declare module ${JSON.stringify(item.source)} {`);
    lines.push("  const __opencanonModule: any;");
    if (item.defaultExport) lines.push("  export default __opencanonModule;");
    if (item.namespaceExport) lines.push("  export = __opencanonModule;");
    for (const name of item.namedExports) {
      lines.push(`  export const ${name}: any;`);
    }
    lines.push("}");
    lines.push("");
  }
  return lines.join("\n");
}

export function renderCoreAuthoringDeclarations(): string {
  return [
    "// Generated by OpenCanon. Do not edit by hand.",
    "// Local editor declarations for convention authoring imports.",
    "",
    "export type Severity = \"error\" | \"warning\" | \"info\";",
    "export type ValidatorScope = \"project\" | \"file\" | \"import-edge\";",
    "export type ValidatorDomain = \"file\" | \"import-edge\" | \"impact-surface\" | \"definition\" | \"project\" | \"custom\";",
    "export type FactKind = \"imports\" | \"exports\" | \"symbols\" | \"calls\" | \"literals\" | \"comments\" | \"references\" | \"annotations\" | \"diagnostics\" | \"duplicates\" | \"declarations\";",
    "export type ConventionId = string;",
    "export declare const ConventionDefinitionKind: { readonly Area: \"area\"; readonly Change: \"change\"; readonly Convention: \"convention\"; readonly Spec: \"spec\" };",
    "export type ConventionDefinitionKind = \"area\" | \"change\" | \"convention\" | \"spec\";",
    "export type Applies =",
    "  | { kind: \"files\"; globs: string[] }",
    "  | { kind: \"symbols\"; globs: string[]; symbolKinds?: Array<\"function\" | \"class\" | \"type\"> }",
    "  | { kind: \"imports\"; from?: string[]; to?: string[] }",
    "  | { kind: \"impact-surface\"; surfaceIds: string[] }",
    "  | { kind: \"definitions\"; definitions: Array<{ kind: ConventionDefinitionKind; ids?: string[] }> }",
    "  | { kind: \"project\"; describe?: string }",
    "  | { kind: \"custom\"; describe: string };",
    "export type RenderStyle = \"narrative\" | \"checklist\" | \"reference\" | \"architecture-note\" | \"decision-record\";",
    "export type Render = { kind: \"generated\"; docs: string; style: RenderStyle } | { kind: \"none\" };",
    "export type FindingFix = { safety?: \"safe\" | \"suggested\" | \"manual\"; description?: string; edits?: Array<{ file: string; range?: unknown; replacement: string }>; command?: string };",
    "export type Finding = { file?: string; line?: number; column?: number; message: string; severity?: Severity; docs?: string[]; fix?: FindingFix; conventionIds?: string[] };",
    "export type ReportInput = Omit<Finding, \"file\">;",
    "export type ProjectFile = { path: string; language?: string; content?: string; lineAt(line: number): string; report(input: ReportInput): Finding; ts: any };",
    "export type CommitGateInput = { id: string; title: string; reason: string; question: string; file?: string; line?: number; evidence?: unknown; conventionIds?: string[] };",
    "export type ValidatorArgs = { ctx: any; runtime: any; file?: ProjectFile; edge?: any };",
    "export type ValidatorVisual = any;",
    "export type RuntimeBody = { scope: ValidatorScope; domain?: ValidatorDomain; facts: FactKind[]; visuals?: ValidatorVisual[]; requiresProducers?: string[]; fixtures?: \"valid-and-invalid\" | \"valid-only\"; validate(args: ValidatorArgs): Finding[] | Promise<Finding[]> };",
    "export type Runtime = { kind: \"none\" } | ({ kind: \"validator\"; severity: Severity } & RuntimeBody) | ({ kind: \"gate\"; question: string } & RuntimeBody) | ({ kind: \"test\"; severity: Severity } & RuntimeBody);",
    "export type Convention = { id: ConventionId; title: string; topics?: string[]; why?: string; rule: string; examples?: Array<{ good?: string; bad?: string; note?: string }>; related?: ConventionId[]; impactSurfaces?: string[]; applies: Applies; render: Render; runtime: Runtime };",
    "export declare function defineConvention(convention: Convention): Convention;",
    "export type AreaId = string;",
    "export type AreaRenderStyle = \"narrative\" | \"checklist\" | \"reference\" | \"architecture-note\" | \"decision-record\";",
    "export type AreaRender = { kind: \"generated\"; docs: string; style: AreaRenderStyle } | { kind: \"none\" };",
    "export declare const DefinitionTargetKind: { readonly File: \"file\"; readonly Package: \"package\"; readonly Endpoint: \"endpoint\"; readonly Command: \"command\"; readonly Doc: \"doc\"; readonly Resource: \"resource\" };",
    "export type DefinitionTargetKind = (typeof DefinitionTargetKind)[keyof typeof DefinitionTargetKind];",
    "export type DefinitionTargetBase = { id?: string; label?: string; description?: string; adapter?: string };",
    "export type DefinitionTarget =",
    "  | (DefinitionTargetBase & { kind: \"file\"; path: string })",
    "  | (DefinitionTargetBase & { kind: \"package\"; name: string })",
    "  | (DefinitionTargetBase & { kind: \"endpoint\"; path: string; protocol?: string })",
    "  | (DefinitionTargetBase & { kind: \"command\"; name: string })",
    "  | (DefinitionTargetBase & { kind: \"doc\"; path: string })",
    "  | (DefinitionTargetBase & { kind: \"resource\"; name: string; type?: string });",
    "export type AreaOwnership = DefinitionTarget[];",
    "export type AreaCheck =",
    "  | { id: string; kind: \"command\"; command: string; description?: string }",
    "  | { id: string; kind: \"doctor\"; description?: string }",
    "  | { id: string; kind: \"validator\"; validatorId: string; description?: string }",
    "  | { id: string; kind: \"test\"; target: string; description?: string };",
    "export type AreaStory = { id: string; as: string; want: string; so: string; acceptance: string[]; checks?: string[] };",
    "export type AreaBehavior = { id: string; actor: string; action: string; outcome: string; checks?: string[] };",
    "export type AreaGovernance = { inferFromScope?: boolean; conventions?: string[] };",
    "export type Area = { id: AreaId; title: string; summary: string; surfaces?: string[]; owns?: AreaOwnership; stories?: AreaStory[]; behaviors?: AreaBehavior[]; checks?: AreaCheck[]; dependsOn?: AreaId[]; governedBy?: AreaGovernance; render: AreaRender };",
    "export declare function defineArea(area: Area): Area;",
    "export type SpecId = string;",
    "export type SpecRenderStyle = \"narrative\" | \"checklist\" | \"reference\" | \"architecture-note\" | \"decision-record\";",
    "export type SpecRender = { kind: \"generated\"; docs: string; style: SpecRenderStyle } | { kind: \"none\" };",
    "export type SpecScope = DefinitionTarget[];",
    "export type SpecCheck =",
    "  | { id: string; kind: \"command\"; command: string; description?: string }",
    "  | { id: string; kind: \"doctor\"; description?: string }",
    "  | { id: string; kind: \"validator\"; validatorId: string; description?: string }",
    "  | { id: string; kind: \"test\"; target: string; description?: string };",
    "export type SpecRule = { id: string; statement: string; acceptance?: string[]; checks?: string[] };",
    "export type SpecScenario = { id: string; given: string[]; when: string; then: string[]; checks?: string[] };",
    "export type SpecGovernance = { inferFromScope?: boolean; conventions?: ConventionId[] };",
    "export type Spec = { id: SpecId; title: string; summary: string; scope?: SpecScope; surfaces?: string[]; areas?: AreaId[]; rules?: SpecRule[]; scenarios?: SpecScenario[]; checks?: SpecCheck[]; dependsOn?: SpecId[]; governedBy?: SpecGovernance; render: SpecRender };",
    "export declare function defineSpec(spec: Spec): Spec;",
    "export type ChangeId = string;",
    "export type ChangeKind = \"feature\" | \"fix\" | \"refactor\" | \"docs\" | \"chore\" | \"research\";",
    "export type ChangeRenderStyle = \"narrative\" | \"checklist\" | \"reference\" | \"architecture-note\" | \"decision-record\";",
    "export type ChangeRender = { kind: \"generated\"; docs: string; style: ChangeRenderStyle } | { kind: \"none\" };",
    "export type ChangeUpdates = { areas?: AreaId[]; specs?: SpecId[]; conventions?: ConventionId[]; surfaces?: string[]; docs?: string[] };",
    "export type ChangeScope = DefinitionTarget[];",
    "export type ChangeIntent = { problem: string; outcome: string; why?: string };",
    "export type ChangeCheck =",
    "  | { id: string; kind: \"command\"; command: string; description?: string }",
    "  | { id: string; kind: \"doctor\"; description?: string }",
    "  | { id: string; kind: \"validator\"; validatorId: string; description?: string }",
    "  | { id: string; kind: \"test\"; target: string; description?: string };",
    "export type ChangePlanItem = { id: string; title: string; detail?: string; checks?: string[] };",
    "export type ChangeTask = { id: string; title: string; detail?: string; files?: string[]; checks?: string[]; dependsOn?: string[]; blockedBy?: string[]; updates?: ChangeUpdates };",
    "export type ChangeLinks = { commits?: string[]; pullRequests?: string[]; issues?: string[] };",
    "export type Change = { id: ChangeId; title: string; kind: ChangeKind; summary?: string; updates?: ChangeUpdates; scope?: ChangeScope; intent: ChangeIntent; plan?: ChangePlanItem[]; tasks?: ChangeTask[]; checks?: ChangeCheck[]; dependsOn?: ChangeId[]; blockedBy?: ChangeId[]; links?: ChangeLinks; render: ChangeRender };",
    "export declare function defineChange(change: Change): Change;",
    "export type ConventionFactoryBaseOptions = { id: string; topics: string[]; severity: Severity; related?: string[]; docs?: string[]; summary?: string; title?: string; rule?: string; render?: Render };",
    "export type ValidatorDefinition = { id: string; topics?: string[]; applies?: string[]; severity?: Severity; scope?: ValidatorScope; domain?: ValidatorDomain; facts?: FactKind[]; conventionIds?: string[]; docs?: string[]; summary?: string; visuals?: ValidatorVisual[]; requiresProducers?: string[]; fixtures?: \"valid-and-invalid\" | \"valid-only\"; validate?: (args: ValidatorArgs) => Finding[] | Promise<Finding[]> };",
    "export type ConventionFactory<TOptions extends Record<string, unknown> = Record<string, never>> = (options: ConventionFactoryBaseOptions & TOptions) => Convention;",
    "export declare function createConventionFactory<TOptions extends Record<string, unknown> = Record<string, never>>(create: (options: ConventionFactoryBaseOptions & TOptions) => ValidatorDefinition, applies?: (definition: ValidatorDefinition, options: ConventionFactoryBaseOptions & TOptions) => Applies): ConventionFactory<TOptions>;",
    "export declare const LiteralContext: { readonly Comparison: \"comparison\"; readonly Argument: \"argument\"; readonly ObjectProperty: \"object-property\"; readonly ArrayItem: \"array-item\"; readonly TypeUnion: \"type-union\"; readonly ConstObject: \"const-object\"; readonly ImportSource: \"import-source\"; readonly TestTitle: \"test-title\"; readonly Unknown: \"unknown\" };",
    "export type LiteralContext = (typeof LiteralContext)[keyof typeof LiteralContext];",
    "export declare const LiteralValueKind: { readonly String: \"string\"; readonly Number: \"number\"; readonly Boolean: \"boolean\" };",
    "export type LiteralValueKind = (typeof LiteralValueKind)[keyof typeof LiteralValueKind];",
    "export declare const TypeScriptDeclarationKind: { readonly Enum: \"enum\"; readonly Variable: \"variable\"; readonly Type: \"type\"; readonly Function: \"function\"; readonly Class: \"class\"; readonly Interface: \"interface\" };",
    "export type TypeScriptDeclarationKind = (typeof TypeScriptDeclarationKind)[keyof typeof TypeScriptDeclarationKind];",
    "export declare const ProjectSymbolKind: { readonly Function: \"function\"; readonly Class: \"class\"; readonly Method: \"method\"; readonly Variable: \"variable\"; readonly Type: \"type\"; readonly Interface: \"interface\"; readonly Enum: \"enum\"; readonly Property: \"property\"; readonly Unknown: \"unknown\" };",
    "export type ProjectSymbolKind = (typeof ProjectSymbolKind)[keyof typeof ProjectSymbolKind];",
    "export declare const ProjectFileLanguage: { readonly TypeScript: \"typescript\"; readonly JavaScript: \"javascript\"; readonly Svelte: \"svelte\"; readonly Python: \"python\"; readonly Rust: \"rust\"; readonly Markdown: \"markdown\"; readonly Json: \"json\"; readonly Unknown: \"unknown\" };",
    "export type ProjectFileLanguage = (typeof ProjectFileLanguage)[keyof typeof ProjectFileLanguage];",
    "export type LiteralContextInfo = any;",
    "export type OpenCanonProjectIndexFile = { imports: string; exports: string; functions: string; stringLiterals: string; symbols: string; calls: string };",
    "export interface OpenCanonProjectIndex {}",
    "export declare function asFiniteLiteralSet(value: unknown): unknown;",
    "export declare function finiteLiteralIncludes(set: unknown, value: unknown): boolean;",
    "",
  ].join("\n");
}

export function renderTestingAuthoringDeclarations(): string {
  return [
    "// Generated by OpenCanon. Do not edit by hand.",
    "// Local editor declarations for fixture authoring imports.",
    "",
    "export type FixtureTextInput = string;",
    "export type FixtureFileOptions = { target?: boolean; analysis?: boolean };",
    "export type FixtureTextFileInput = FixtureTextInput | { text: FixtureTextInput; target?: boolean; analysis?: boolean };",
    "export type FixtureFileEntry = { path: string; text: string; target?: boolean; analysis?: boolean };",
    "export type FixtureFileBuilder = {",
    "  (path: string, input: FixtureTextFileInput): FixtureFileEntry;",
    "  ts(path: string, input: FixtureTextInput, options?: FixtureFileOptions): FixtureFileEntry;",
    "  tsx(path: string, input: FixtureTextInput, options?: FixtureFileOptions): FixtureFileEntry;",
    "  js(path: string, input: FixtureTextInput, options?: FixtureFileOptions): FixtureFileEntry;",
    "  jsx(path: string, input: FixtureTextInput, options?: FixtureFileOptions): FixtureFileEntry;",
    "  py(path: string, input: FixtureTextInput, options?: FixtureFileOptions): FixtureFileEntry;",
    "  rs(path: string, input: FixtureTextInput, options?: FixtureFileOptions): FixtureFileEntry;",
    "  toml(path: string, input: FixtureTextInput, options?: FixtureFileOptions): FixtureFileEntry;",
    "  md(path: string, input: FixtureTextInput, options?: FixtureFileOptions): FixtureFileEntry;",
    "  json(path: string, value: unknown, options?: FixtureFileOptions): FixtureFileEntry;",
    "};",
    "export type FixtureFileApi = { file: FixtureFileBuilder };",
    "export type FixtureDefinition = { directories?: string[]; files?: (api: FixtureFileApi) => FixtureFileEntry[]; targetFiles?: string[]; analysisFiles?: string[] };",
    "export declare function defineFixture(input: FixtureDefinition): FixtureDefinition;",
    "",
  ].join("\n");
}

export function renderValidatorsAuthoringDeclarations(): string {
  const factories = [
    "fileNames",
    "requiredFileSibling",
    "requiredFunctionParam",
    "requireExportPattern",
    "noUnusedExports",
    "similarFunctionNames",
    "noNativeEnums",
    "noHardcodedConfigValues",
    "noSecretLikeLiterals",
    "repeatedLiterals",
    "restrictedSymbols",
    "noImports",
    "noForbiddenImports",
    "noDeepRelativeImports",
    "noBarrelCrossBoundary",
    "noLayerCall",
    "noFolderNames",
    "folderStructure",
    "noCommentMatches",
    "noHeaderComments",
    "noBypassComments",
    "noForbiddenCalls",
    "noShimFiles",
    "annotationRequiresTags",
    "externalCommand",
    "externalDiagnostics",
    "noBareExcept",
    "duplicateBoundaryLiterals",
    "sensitiveChangePolicy",
    "migrationReferences",
  ];
  return [
    "// Generated by OpenCanon. Do not edit by hand.",
    "// Local editor declarations for curated convention factories.",
    "import type { Convention, ConventionFactoryBaseOptions } from \"@opencanon/core\";",
    "",
    "export type CuratedConventionFactory<TOptions extends Record<string, unknown> = Record<string, unknown>> = (options: ConventionFactoryBaseOptions & TOptions) => Convention;",
    ...factories.map((name) => `export declare const ${name}: CuratedConventionFactory;`),
    "",
  ].join("\n");
}

function renderJsDoc(lines: string[], indent: string): string[] {
  if (lines.length === 0) return [];
  return [
    `${indent}/**`,
    ...lines.flatMap((line, index) => {
      const text = escapeComment(line);
      return index === 0 ? [`${indent} * ${text}`, `${indent} *`] : [`${indent} * ${text}`];
    }),
    `${indent} */`,
  ];
}

function escapeComment(input: string): string {
  return input.replaceAll("*/", "* /").replace(/\s+/g, " ").trim();
}
