import { defineConvention } from "@opencanon/core";

const productLanguageDocs = ["docs/opencanon/canon/product-language-current.md#product-facing-language-stays-simple"];
const forbiddenProductTerms = [
  {
    pattern: /\bCapabilities\b/g,
    message: "Use Areas, Project Map, Runtime Features, or a specific product surface instead of Capabilities as a product concept.",
  },
  {
    pattern: /\bCapability\b/g,
    message: "Use Area, Project Map, Runtime Feature, or a specific product surface instead of Capability as a product concept.",
  },
  {
    pattern: /\bWorks\b/g,
    message: "Use Changes for planned implementation units; avoid Works as a product concept.",
  },
  {
    pattern: /\bWork\b/g,
    message: "Use Change for planned implementation units; avoid Work as a product concept.",
  },
  {
    pattern: /\b[Ss]emantic search\b/g,
    message: "Use Search, Knowledge, or Embedding search depending on the exact surface; do not overclaim semantic search.",
  },
  {
    pattern: /\b[Aa]gent docs\b/g,
    message: "Use the managed OpenCanon skill, managed agent entry files, or Project Canon docs instead of agent docs.",
  },
];

const docsOnlyConventions = [
  defineConvention({
    id: "dal-transaction-flow",
    title: "DAL functions accept optional transactions",
    topics: ["dal","api-route"],
    related: ["dal-transaction-param","no-route-dal-import","service-no-db-client"],
    why: "Services often need multi-step writes to commit or roll back as one unit. Routes should stay HTTP-focused and not know persistence details. One transaction-aware DAL pattern is cleaner than parallel transactional/non-transactional helpers.",
    rule: "Database access functions accept an optional transaction/client so services can compose multi-step writes atomically.",
    examples: [{"note":"src/db/dal/company.ts shows the transaction-aware DAL shape."},{"note":"src/api/routes/companies.ts shows a route calling a service instead of DAL."}],
    applies: { kind: "files", globs: ["src/db/dal/**/*.{ts,tsx}","src/services/**/*.{ts,tsx}","src/api/routes/**/*.{ts,tsx}","packages/*/src/db/dal/**/*.{ts,tsx}","packages/*/src/services/**/*.{ts,tsx}","packages/*/src/api/routes/**/*.{ts,tsx}"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/dal-transaction-flow.md", style: "reference" },
    runtime: { kind: "none" },
  }),
  defineConvention({
    id: "service-db-boundary",
    title: "Services compose DAL instead of direct DB clients",
    topics: ["service","dal"],
    related: ["service-no-db-client"],
    why: "DAL modules keep table/query details in one layer. Services stay focused on business sequencing and transactions.",
    rule: "Services own workflow composition but should use DAL modules for persistence details.",
    applies: { kind: "files", globs: ["src/services/**/*.{ts,tsx}","packages/*/src/services/**/*.{ts,tsx}"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/service-db-boundary.md", style: "reference" },
    runtime: { kind: "none" },
  }),
  defineConvention({
    id: "import-boundaries-current",
    title: "Imports preserve local ownership boundaries",
    topics: ["imports","folder-structure"],
    related: ["no-deep-relative-imports","source-files-stay-cohesive"],
    why: "Agents tend to copy nearby imports. Deep relative paths make it hard to see whether a dependency direction is intentional.",
    rule: "Deep relative imports are treated as a boundary smell because they make layer ownership implicit.",
    applies: { kind: "files", globs: ["src/**/*.{ts,tsx}","tests/**/*.{ts,tsx}","packages/*/src/**/*.{ts,tsx}"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/import-boundaries-current.md", style: "reference" },
    runtime: { kind: "none" },
  }),
  defineConvention({
    id: "product-language-current",
    title: "Product-facing language stays simple",
    topics: ["architecture","lifecycle"],
    why: "The internal model needs precise terms, but docs and agent guidance should present a smaller vocabulary so humans and agents do not treat implementation details as product concepts.",
    rule: "Use Project Canon, Proof, Knowledge, Activity, Areas, Specs, Changes, Surfaces, Project Map, Search, Doctor, and Health in product-facing surfaces unless an exact internal type is required.",
    examples: [{"note":"Use Project Canon as the umbrella for conventions, areas, specs, and changes; keep definitionGraph in code."},{"note":"Use Changes in navigation; keep ChangeSummary as the internal DTO name."},{"note":"Use Knowledge or Search in app copy; keep Semantic Index and chunks in runtime architecture."},{"note":"Use Proof for checks, validators, gates, doctor, and coverage; keep exact runtime kind names where they matter."},{"note":"Use Activity for events, agent runs, indexing progress, check results, and logs."}],
    impactSurfaces: ["project-canon-model"],
    applies: { kind: "files", globs: ["README.md","docs/opencanon/**/*.md","apps/site/src/**/*.{svelte,js,ts}",".agents/skills/**/*.md","AGENTS.md","CLAUDE.md"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/product-language-current.md", style: "reference" },
    runtime: {
      kind: "validator",
      severity: "warning",
      scope: "file",
      facts: [],
      validate({ ctx }) {
        return ctx.targetFiles.flatMap((file) =>
          forbiddenProductTerms.flatMap((term) =>
            file.find(term.pattern).map((match) =>
              file.report({
                line: match.line,
                column: match.column,
                message: term.message,
                docs: productLanguageDocs,
                fix: {
                  safety: "manual",
                  description: "Rewrite the copy to the current product vocabulary.",
                },
              }),
            ),
          ),
        );
      },
    },
  }),
  defineConvention({
    id: "service-events-current",
    title: "Runtime data updates through explicit service events",
    topics: ["architecture","runtime"],
    related: ["state-ownership-current"],
    why: "Project data should either come from the project runtime event stream or be visibly unavailable. Silent polling fallback makes stale data look healthy and hides transport failures from humans and agents.",
    rule: "Service and project-runtime data updates come from explicit runtime events; transport failures enter reconnecting or offline states rather than hidden project-data fallback.",
    examples: [{"note":"Runtime snapshots update summary, doctor, gates, context, Activity, and Project Map queries from the project event stream."},{"note":"Refresh Project restarts event-stream repair after bounded reconnect attempts instead of leaving hidden polling active."},{"note":"Service discovery may refresh service health, but it does not replace project runtime live updates."}],
    impactSurfaces: ["local-service-control"],
    applies: { kind: "files", globs: ["packages/runtime/src/server-events.ts","packages/runtime/src/service.ts","packages/runtime/src/server*.ts","packages/runtime/test/service.test.ts","packages/runtime/test/client.test.ts"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/service-events-current.md", style: "reference" },
    runtime: { kind: "none" },
  }),
  defineConvention({
    id: "project-knowledge-boundary-current",
    title: "Project Knowledge is derived OpenCanon runtime state",
    topics: ["architecture","search","runtime"],
    why: "Search, chunks, embeddings, and related-code retrieval are valuable only when they serve the OpenCanon product model. Treating them as a separate product or authored source of truth would split responsibility and weaken deterministic enforcement.",
    rule: "Project Knowledge belongs to OpenCanon runtime state; authored definitions stay in repo source, and semantic results remain advisory unless backed by checks or convention runtimes.",
    examples: [{"note":"A chunk can backlink to an area, spec, change item, convention, finding, and impact surface, but the chunk itself is regenerated state."},{"note":"Use search to discover likely related code, then enforce behavior through validators, checks, gates, or tests."}],
    impactSurfaces: ["project-knowledge-index"],
    applies: { kind: "files", globs: ["packages/core/src/semantic-index.ts","packages/runtime/src/semantic-index.ts","packages/runtime/src/snapshot.ts","packages/runtime/src/server*.ts","crates/opencanon-vector/**","crates/opencanon-inference/**","docs/opencanon/canon/architecture.md"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/project-knowledge-boundary-current.md", style: "reference" },
    runtime: { kind: "none" },
  }),
  defineConvention({
    id: "state-ownership-current",
    title: "Repo definitions own truth; generated state stays derived",
    topics: ["architecture","configuration"],
    why: "A local service introduces global state, project-local state, and committed definitions. Mixing those ownership domains causes stale docs, unreviewed state drift, and hard-to-debug runtime behavior.",
    rule: "Committed repo definitions are the source of truth; .opencanon and OpenCanon home directory data are generated state, projections, cache, history, indexes, or local service metadata.",
    examples: [{"note":"Project Canon lives in opencanon/conventions, opencanon/areas, opencanon/specs, and opencanon/changes."},{"note":"Product model rows, semantic chunks, and vector files in .opencanon are derived from committed definitions and project files."}],
    impactSurfaces: ["local-service-control", "project-knowledge-index", "project-canon-model"],
    applies: { kind: "files", globs: ["opencanon/**/*.ts","docs/opencanon/**/*.md",".agents/skills/**/*.md",".opencanon/**","packages/runtime/src/**/*.{ts,tsx}","packages/core/src/doctor.ts"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/state-ownership-current.md", style: "reference" },
    runtime: { kind: "none" },
  }),
  defineConvention({
    id: "comments-current",
    title: "Comments describe current intent",
    topics: ["comments"],
    related: ["no-stale-intent-comments","no-shim-files","shim-requires-expiry","deprecated-requires-replacement"],
    why: "Agents may treat comments as live instructions. Legacy/deprecation/shim comments invite preserving old paths instead of cleaning touched code.",
    rule: "Comments should explain current behavior, not preserve stale compatibility narratives.",
    applies: { kind: "files", globs: ["src/**/*.{ts,tsx,py}","tests/**/*.{ts,tsx,py}"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/comments-current.md", style: "reference" },
    runtime: { kind: "none" },
  }),
  defineConvention({
    id: "const-object-enums",
    title: "Use const objects instead of native TypeScript enums",
    topics: ["type-patterns"],
    related: ["no-native-enums","repeated-domain-literals"],
    why: "Const objects are plain JavaScript and avoid TypeScript enum runtime semantics. The pattern keeps value casing and type naming visible to agents and reviewers.",
    rule: "Enum-like values use JavaScript const objects plus a derived union type instead of native TypeScript enums.",
    examples: [{"note":"export const CompanyStatus = { ACTIVE: \"active\" } as const;"},{"note":"export type CompanyStatus = (typeof CompanyStatus)[keyof typeof CompanyStatus];"}],
    applies: { kind: "files", globs: ["src/**/*.{ts,tsx}","tests/**/*.{ts,tsx}","packages/*/src/**/*.{ts,tsx}"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/const-object-enums.md", style: "reference" },
    runtime: { kind: "none" },
  }),
  defineConvention({
    id: "schema-contract-boundary",
    title: "Schemas define contracts at package boundaries",
    topics: ["schema","api-route"],
    related: ["no-db-schema-in-contracts","duplicate-boundary-literals"],
    why: "Boundary schemas stabilize request/response contracts. Database table definitions are persistence details and should not leak into public DTO modules.",
    rule: "Validation schemas and DTO contracts live at boundaries; internals use typed domain objects.",
    applies: { kind: "files", globs: ["src/contracts/**/*.{ts,tsx}","src/db/schema/**/*.{ts,tsx}","src/api/routes/**/*.{ts,tsx}"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/schema-contract-boundary.md", style: "reference" },
    runtime: { kind: "none" },
  }),
  defineConvention({
    id: "tests-follow-risk",
    title: "Tests scale with blast radius",
    topics: ["testing"],
    related: ["spec-definitions-are-enforced","source-files-stay-cohesive"],
    why: "Tests should catch regressions at the same boundary where the risk was introduced.",
    rule: "Narrow changes get focused unit tests; shared behavior and cross-layer workflows need broader tests.",
    applies: { kind: "files", globs: ["tests/**/*.{ts,tsx,py}","src/**/*.test.{ts,tsx,py}","packages/*/test/**/*.{ts,tsx,py}","packages/*/src/**/*.test.{ts,tsx,py}"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/tests-follow-risk.md", style: "reference" },
    runtime: { kind: "none" },
  }),
  defineConvention({
    id: "python-module-boundaries",
    title: "Python modules use package imports instead of sys.path mutation",
    topics: ["python"],
    related: ["python-no-sys-path-mutation","python-no-bare-except"],
    why: "Runtime path mutation hides dependency boundaries. Package imports are easier for tests, agents, and tooling to reason about.",
    rule: "Python code should use normal package/module configuration rather than mutating sys.path at runtime.",
    applies: { kind: "files", globs: ["src/python/**/*.py"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/python-module-boundaries.md", style: "reference" },
    runtime: { kind: "none" },
  }),
  defineConvention({
    id: "folder-structure-current",
    title: "Folders use approved responsibility names",
    topics: ["folder-structure","service"],
    related: ["no-dumpster-folders","folder-file-naming","source-files-stay-cohesive"],
    why: "Agents copy folder names they see. Ambiguous folders make ownership and import direction harder to infer.",
    rule: "Folders should communicate ownership and layer responsibility instead of becoming dumping grounds.",
    applies: { kind: "files", globs: ["src/**","tests/**","packages/*/src/**"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/folder-structure-current.md", style: "reference" },
    runtime: { kind: "none" },
  }),
  defineConvention({
    id: "impact-surfaces-current",
    title: "Impact surfaces describe sensitive downstream effects",
    topics: ["impact","testing"],
    related: ["sensitive-change-requires-approval"],
    impactSurfaces: ["company-read-model"],
    why: "Import graphs miss domain dependencies such as data, events, jobs, permissions, and external contracts. Agents need explicit risk context before changing sensitive surfaces.",
    rule: "Sensitive files and domain resources are linked through impact surfaces so agents can see downstream effects before changing them.",
    applies: { kind: "files", globs: ["src/**/*.{ts,tsx,py}","tests/**/*.{ts,tsx,py}"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/impact-surfaces-current.md", style: "reference" },
    runtime: { kind: "none" },
  }),
  defineConvention({
    id: "hardcoded-secrets-and-config",
    title: "Secrets and environment config stay out of source literals",
    topics: ["security","configuration"],
    related: ["no-secret-like-literals","no-hardcoded-config-values"],
    why: "Committed secrets are difficult to revoke reliably after publication. Hardcoded URLs, hosts, and ports make deployment environments harder to change. Agents may copy literal values unless config ownership is explicit.",
    rule: "Source code should not contain live-looking secrets or environment-specific configuration literals.",
    impactSurfaces: ["release-update"],
    applies: { kind: "files", globs: ["src/**/*.{ts,tsx}","packages/*/src/**/*.{ts,tsx}"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/hardcoded-secrets-and-config.md", style: "reference" },
    runtime: { kind: "none" },
  }),
  defineConvention({
    id: "guard-file-json-parse",
    title: "JSON.parse of file I/O must be guarded by try/catch",
    topics: ["robustness"],
    related: ["no-unguarded-json-parse"],
    why: "JSON.parse throws a SyntaxError on malformed input; an unguarded parse of an on-disk file turns a corrupt or partially-written file into a process crash. File contents are untrusted input at runtime (user edits, partial writes, version skew) and should be treated defensively. Graceful degradation (default value, skipped entry, reported diagnostic) keeps tooling usable when a single file is bad.",
    rule: "Parsing file contents with JSON.parse must sit inside a try/catch so a malformed file degrades gracefully instead of throwing an unhandled SyntaxError.",
    examples: [{"note":"let data; try { data = JSON.parse(readFileSync(path, 'utf8')); } catch { data = null; }"}],
    applies: { kind: "files", globs: ["packages/*/src/**/*.{ts,tsx}"] },
    render: { kind: "generated", docs: "docs/opencanon/canon/guard-file-json-parse.md", style: "reference" },
    runtime: { kind: "none" },
  }),
];

export default docsOnlyConventions;
