import { repeatedLiterals } from "@opencanon/validators";

const frameworkVocabulary = [
  "GET",
  "POST",
  "PUT",
  "PATCH",
  "DELETE",
  "opencanon",
  "file",
  "folder",
  "import-edge",
  "package",
  "project",
  "imports",
  "exports",
  "symbols",
  "calls",
  "literals",
  "comments",
  "tree",
  "string",
  "number",
  "boolean",
  "sha256",
  "hex",
  "function",
  "engine",
  "ready",
  "running",
  "severity",
  "stale",
  "status",
  "start",
  "language",
  "ui",
  ".opencanon",
  "state.sqlite",
  "engine-binary-missing",
  " (dry-run)",
  ".agents/skills/opencanon",
];

const incidentalCodeVocabulary = [
  "-h",
  "--help",
  "-h, --help",
  "--dry-run",
  "--format <format>",
  "--files <path>",
  "--changed",
  "--topic <topic>",
  "--topics <topics>",
  "--version",
  "error",
  "fixed",
  "invalid",
  "valid",
  "Show help.",
  "Show files that would change without writing.",
  "Show selected fixes without writing files.",
  "No changed files.",
  "Output format.",
  "node",
  "help",
  "h",
  "all",
  "dryRun",
  "json",
  "markdown",
  "safe",
  "suggested",
  "utf8",
  "object",
  "<project>",
];

const validator = repeatedLiterals({
  id: "repeated-domain-literals",
  title: "Repeated domain literals move into const objects",
  topics: ["type-patterns"],
  in: ["src/**/*.{ts,tsx}"],
  severity: "warning",
  related: ["const-object-enums"],
  minOccurrences: 3,
  minFiles: 1,
  ignore: [...frameworkVocabulary, ...incidentalCodeVocabulary],
  message: "Repeated domain literals should be promoted to a const object plus derived union type.",
  fix: {
    safety: "manual",
    description: "Extract the repeated values into a const object and use the derived union type at call sites.",
  },
  docs: ["docs/opencanon/canon/repeated-domain-literals.md#repeated-domain-literals-move-into-const-objects"],
});

export default validator;
