import { DefinitionTargetKind, defineChange } from "@opencanon/core";

export const domainProtocolChanges = [
  defineChange({
    id: "versioned-domain-protocol",
    title: "Replace snapshot transport with the domain protocol",
    kind: "refactor",
    summary: "Serve bounded revisioned projections and replayable events through one typed protocol shared by CLI, MCP, browser, and desktop clients.",
    updates: {
      areas: ["local-service-and-runtimes", "project-map-governance", "project-knowledge-index", "runtime-release-update"],
      specs: ["domain-protocol-spec", "runtime-operations-spec", "project-runtime-lifecycle-spec"],
      surfaces: ["local-service-control", "project-canon-model", "project-knowledge-index", "release-update"],
    },
    scope: [
      { kind: DefinitionTargetKind.File, path: "opencanon/specs/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/changes/domain-protocol.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/domain-protocol-spec.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/{runtime-operations-spec,project-runtime-lifecycle-spec}.md" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/protocol*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/package.json" },
      { kind: DefinitionTargetKind.File, path: "packages/core/generated/domain-protocol.openapi.json" },
      { kind: DefinitionTargetKind.File, path: "scripts/generate-domain-protocol.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/errors.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/producer-registry.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/engine/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/{contracts,project,state}.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/project/protocol_event_store.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/migrations/013_protocol_events.sql" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/tests/protocol_events.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/tests/jobs.rs" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/{routes,server-routes,server-events,local-protocol,server-http,protocol-policy,service-types}.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/{activity-projection,change-check-runner,knowledge-index-progress,project-refresh-publication,project-types-runtime,state-manager,state}.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/{brief,changes,context,feedback,gate,graph,mcp,opencode-plugin,refactor,review,runtime-client,search,symbols,validate}.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/{change-runs,client,engine,protocol,protocol-policy,semantic-index,state}.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/service.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/state-manager.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/{change-run-test-support,client-test-sources,engine-binding-test-support,runtime-supervision,service-support}.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/{contracts,cli-reporting,runtime-events,mcp}.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/setup-vitest.ts" },
      { kind: DefinitionTargetKind.File, path: "package.json" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon-architecture.md" },
    ],
    intent: {
      problem: "Public snapshot responses and snapshot-bearing events couple every client to an oversized runtime object, duplicate route knowledge, and make resource cost unpredictable.",
      outcome: "One operation registry serves bounded revisioned projections, durable replayable invalidations, and explicit commands identically over HTTP and local pipe.",
      why: "The CLI, MCP, browser, and desktop app need one stable contract that remains responsive on large projects and can evolve without duplicating business logic across clients.",
    },
    tasks: [
      {
        id: "canon-contract",
        title: "Define the versioned domain protocol",
        files: ["opencanon/specs/index.ts", "opencanon/changes/domain-protocol.ts", "docs/opencanon/specs/domain-protocol-spec.md"],
        checks: ["canon-render", "contracts-tests", "project-doctor"],
      },
      {
        id: "protocol-registry",
        title: "Create the canonical operation and event registry",
        files: ["packages/core/src/protocol*.ts", "packages/core/src/contracts-runtime.ts", "packages/core/src/index.ts", "packages/runtime/test/protocol.test.ts"],
        checks: ["protocol-tests", "contracts-tests", "typecheck"],
        dependsOn: ["canon-contract"],
      },
      {
        id: "bounded-projections",
        title: "Migrate runtime clients to bounded revisioned projections",
        files: ["packages/runtime/src/routes.ts", "packages/runtime/src/server-routes.ts", "packages/runtime/src/index.ts", "packages/runtime/src/local-protocol.ts", "packages/runtime/src/service-types.ts", "packages/cli/src/runtime-client.ts", "packages/cli/src/validate.ts", "packages/cli/src/review.ts", "packages/cli/src/mcp.ts", "packages/runtime/test/client.test.ts", "packages/runtime/test/client-test-sources.ts", "packages/runtime/test/runtime-supervision.test.ts", "packages/runtime/test/service-support.ts", "tests/cli-reporting.test.ts", "tests/mcp.test.ts", "tests/runtime-events.test.ts", "tests/setup-vitest.ts"],
        checks: ["runtime-client-tests", "cli-tests", "mcp-tests", "typecheck"],
        dependsOn: ["protocol-registry"],
      },
      {
        id: "revision-events",
        title: "Publish replayable revision events with byte-bounded streaming",
        files: [
          "packages/core/src/{errors,index,protocol,protocol-operations}.ts",
          "packages/engine/src/index.ts",
          "crates/opencanon-engine/src/{contracts,project,state}.rs",
          "crates/opencanon-engine/src/project/protocol_event_store.rs",
          "crates/opencanon-engine/src/migrations/013_protocol_events.sql",
          "crates/opencanon-engine/src/tests/protocol_events.rs",
          "crates/opencanon-engine/src/tests/jobs.rs",
          "packages/runtime/src/{activity-projection,change-check-runner,knowledge-index-progress,project-refresh-publication,project-types-runtime,routes,server-events,server-routes,server,state-manager,state}.ts",
          "packages/cli/src/changes.ts",
          "packages/runtime/test/{auth,change-runs,client,engine,semantic-index,state}.test.ts",
          "packages/runtime/test/{change-run-test-support,client-test-sources,engine-binding-test-support}.ts",
          "tests/runtime-events.test.ts",
        ],
        checks: ["runtime-event-tests", "runtime-client-tests", "cli-tests", "typecheck"],
        dependsOn: ["bounded-projections"],
      },
      {
        id: "policy-and-cleanup",
        title: "Make protocol policy mandatory and remove snapshot contracts",
        files: ["packages/core/src/protocol*.ts", "packages/core/src/producer-registry.ts", "packages/core/package.json", "packages/core/generated/domain-protocol.openapi.json", "scripts/generate-domain-protocol.ts", "packages/runtime/src/protocol-policy.ts", "packages/runtime/src/server-http.ts", "packages/runtime/src/local-protocol.ts", "packages/runtime/src/routes.ts", "packages/cli/src/{brief,changes,context,feedback,gate,graph,mcp,opencode-plugin,refactor,review,runtime-client,search,symbols,validate}.ts", "packages/runtime/test/client-test-sources.ts", "packages/runtime/test/client.test.ts", "packages/runtime/test/protocol-policy.test.ts", "packages/runtime/test/protocol.test.ts", "package.json"],
        checks: ["protocol-tests", "protocol-contract-drift", "runtime-client-tests", "typecheck", "process-steady-state"],
        dependsOn: ["revision-events"],
      },
      {
        id: "publication-integrity",
        title: "Commit revisions and replay events atomically",
        files: ["opencanon/specs/index.ts", "docs/opencanon/specs/domain-protocol-spec.md", "packages/core/src/protocol*.ts", "packages/engine/src/index.ts", "crates/opencanon-engine/src/{contracts,project,state}.rs", "crates/opencanon-engine/src/project/{code_graph_connection,product_model_store,protocol_event_store}.rs", "crates/opencanon-engine/src/migrations/014_project_publication.sql", "crates/opencanon-engine/src/tests/*.rs", "packages/runtime/src/{project-refresh-publication,server-events,server,state-manager,state,snapshot}.ts", "packages/runtime/test/{client,engine,state-manager,state}.test.ts", "tests/runtime-events.test.ts"],
        checks: ["engine-publication-tests", "coordinator-tests", "runtime-event-tests", "runtime-client-tests", "typecheck"],
        dependsOn: ["policy-and-cleanup"],
      },
      {
        id: "shutdown-integrity",
        title: "Cancel runtime work before shutdown waits",
        files: ["opencanon/specs/index.ts", "docs/opencanon/specs/project-runtime-lifecycle-spec.md", "packages/runtime/src/{server,state-manager}.ts", "packages/runtime/test/{client,state-manager,service}.test.ts"],
        checks: ["coordinator-tests", "runtime-client-tests", "typecheck", "process-steady-state"],
        dependsOn: ["publication-integrity"],
      },
      {
        id: "full-proof",
        title: "Prove the protocol end to end",
        checks: ["protocol-tests", "protocol-contract-drift", "contracts-tests", "runtime-event-tests", "runtime-client-tests", "cli-tests", "mcp-tests", "typecheck", "project-validation", "project-doctor", "process-steady-state", "full-ci"],
        dependsOn: ["shutdown-integrity"],
      },
    ],
    checks: [
      { id: "canon-render", kind: "command", command: "npm run opencanon -- canon render specs --dry-run" },
      { id: "protocol-tests", kind: "test", target: "packages/runtime/test/protocol.test.ts" },
      { id: "protocol-contract-drift", kind: "command", command: "npm run protocol:check" },
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "runtime-event-tests", kind: "test", target: "tests/runtime-events.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "cli-tests", kind: "test", target: "tests/cli-reporting.test.ts" },
      { id: "mcp-tests", kind: "test", target: "tests/mcp.test.ts" },
      { id: "engine-publication-tests", kind: "command", command: "npm run check:engine", timeoutMs: 5 * 60 * 1000 },
      { id: "coordinator-tests", kind: "test", target: "packages/runtime/test/state-manager.test.ts" },
      { id: "typecheck", kind: "command", command: "npm run check:types" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --changed" },
      { id: "project-doctor", kind: "doctor" },
      { id: "process-steady-state", kind: "command", command: "npm run check:test-processes" },
      { id: "full-ci", kind: "command", command: "npm run check:ci", timeoutMs: 10 * 60 * 1000 },
    ],
    render: { kind: "none" },
  }),
];
