import { DefinitionTargetKind, defineChange } from "@opencanon/core";

export const domainProtocolChanges = [
  defineChange({
    id: "versioned-domain-protocol",
    title: "Replace snapshot transport with the domain protocol",
    kind: "refactor",
    summary: "Serve bounded revisioned projections and replayable events through one typed protocol shared by CLI, MCP, browser, and desktop clients.",
    updates: {
      areas: ["local-service-and-runtimes", "project-map-governance", "project-knowledge-index"],
      specs: ["domain-protocol-spec", "runtime-operations-spec", "project-runtime-lifecycle-spec"],
      surfaces: ["local-service-control", "project-canon-model", "project-knowledge-index"],
    },
    scope: [
      { kind: DefinitionTargetKind.File, path: "opencanon/specs/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/changes/domain-protocol.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/domain-protocol-spec.md" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/protocol*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/{routes,server-routes,server-events,local-protocol,server-http,request-admission}.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/{runtime-client,validate,review,mcp}.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/{protocol,client,request-admission}.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/{contracts,cli-reporting,runtime-events,mcp}.test.ts" },
      { kind: DefinitionTargetKind.File, path: "package.json" },
    ],
    intent: {
      problem: "Public snapshot responses and snapshot-bearing events couple every client to an oversized runtime object, duplicate route knowledge, and make resource cost unpredictable.",
      outcome: "One operation registry serves bounded revisioned projections, durable replayable invalidations, and explicit commands identically over HTTP and local pipe.",
      why: "The CLI, MCP, browser, and desktop app need one stable contract that remains responsive on large projects and can evolve without duplicating business logic across clients.",
    },
    tasks: [
      {
        id: "canon-contract",
        title: "Define the versioned domain protocol",
        files: ["opencanon/specs/index.ts", "opencanon/changes/domain-protocol.ts", "docs/opencanon/specs/domain-protocol-spec.md"],
        checks: ["canon-render", "contracts-tests", "project-doctor"],
      },
      {
        id: "protocol-registry",
        title: "Create the canonical operation and event registry",
        files: ["packages/core/src/protocol*.ts", "packages/core/src/contracts-runtime.ts", "packages/core/src/index.ts", "packages/runtime/test/protocol.test.ts"],
        checks: ["protocol-tests", "contracts-tests", "typecheck"],
        dependsOn: ["canon-contract"],
      },
      {
        id: "bounded-projections",
        title: "Migrate runtime clients to bounded revisioned projections",
        files: ["packages/runtime/src/routes.ts", "packages/runtime/src/server-routes.ts", "packages/runtime/src/index.ts", "packages/cli/src/runtime-client.ts", "packages/cli/src/validate.ts", "packages/cli/src/review.ts", "packages/cli/src/mcp.ts", "packages/runtime/test/client.test.ts", "tests/cli-reporting.test.ts", "tests/mcp.test.ts"],
        checks: ["runtime-client-tests", "cli-tests", "mcp-tests", "typecheck"],
        dependsOn: ["protocol-registry"],
      },
      {
        id: "revision-events",
        title: "Publish replayable revision events with byte-bounded streaming",
        files: ["packages/core/src/protocol*.ts", "packages/runtime/src/server-events.ts", "packages/runtime/src/server-routes.ts", "packages/runtime/src/local-protocol.ts", "tests/runtime-events.test.ts", "packages/runtime/test/client.test.ts"],
        checks: ["runtime-event-tests", "runtime-client-tests", "typecheck"],
        dependsOn: ["bounded-projections"],
      },
      {
        id: "policy-and-cleanup",
        title: "Make protocol policy mandatory and remove snapshot contracts",
        files: ["packages/runtime/src/request-admission.ts", "packages/runtime/src/server-http.ts", "packages/runtime/src/local-protocol.ts", "packages/runtime/src/routes.ts", "packages/cli/src/runtime-client.ts", "packages/runtime/test/request-admission.test.ts", "packages/runtime/test/protocol.test.ts"],
        checks: ["protocol-tests", "runtime-client-tests", "typecheck", "process-steady-state"],
        dependsOn: ["revision-events"],
      },
      {
        id: "full-proof",
        title: "Prove the protocol end to end",
        checks: ["protocol-tests", "contracts-tests", "runtime-event-tests", "runtime-client-tests", "cli-tests", "mcp-tests", "typecheck", "project-validation", "project-doctor", "process-steady-state", "full-ci"],
        dependsOn: ["policy-and-cleanup"],
      },
    ],
    checks: [
      { id: "canon-render", kind: "command", command: "npm run opencanon -- canon render specs --dry-run" },
      { id: "protocol-tests", kind: "test", target: "packages/runtime/test/protocol.test.ts" },
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "runtime-event-tests", kind: "test", target: "tests/runtime-events.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "cli-tests", kind: "test", target: "tests/cli-reporting.test.ts" },
      { id: "mcp-tests", kind: "test", target: "tests/mcp.test.ts" },
      { id: "typecheck", kind: "command", command: "npm run check:types" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --changed" },
      { id: "project-doctor", kind: "doctor" },
      { id: "process-steady-state", kind: "command", command: "npm run check:test-processes" },
      { id: "full-ci", kind: "command", command: "npm run check:ci", timeoutMs: 10 * 60 * 1000 },
    ],
    render: { kind: "none" },
  }),
];
