import { DefinitionTargetKind, defineChange } from "@opencanon/core";

export default [
  defineChange({
    id: "agent-readiness-integrity",
    title: "Keep agent readiness projections truthful",
    kind: "fix",
    summary: "Keep agent readiness truthful across complete Change Activity, pipe-first CLI traffic, live Knowledge checks, and owner-bound Proof runtimes.",
    updates: {
      areas: ["local-service-and-runtimes", "project-map-governance"],
      specs: ["runtime-operations-spec", "spec-governance-model"],
      surfaces: ["local-service-control", "project-canon-model", "project-knowledge-index", "release-update"],
    },
    scope: [
      { kind: DefinitionTargetKind.File, path: "opencanon/specs/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/areas/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/changes/index.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/areas/local-service-and-runtimes.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/runtime-operations-spec.md" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/change.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts-change-runs.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts-governance.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/generated-state.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/engine/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/**" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-canon-events.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/snapshot.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/worktree-coordination.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/brief.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/runtime-client.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/review.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-change-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-check-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-control.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/state.ts" },
      { kind: DefinitionTargetKind.File, path: ".gitignore" },
      { kind: DefinitionTargetKind.File, path: "package.json" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/change-run-test-support.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/engine-binding-test-support.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/change-runs.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/runtime-supervision.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/engine.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/semantic-index.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/state.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/client.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/cli-reporting.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/contracts.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/validator-runtime.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/init*.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/worktree.test.ts" },
    ],
    intent: {
      problem: "Bounded Activity could hide closure events, brief forced HTTP, Doctor could claim uninspected Knowledge, and a crashed Proof owner could leave its nested project runtime alive.",
      outcome: "Brief, ready work, snapshots, local transport, Doctor, and isolated Proof runtime lifecycles agree on complete current state without hidden fallbacks or leaked processes.",
      why: "The managed agent workflow starts with brief and ends with Doctor, so both commands must be trustworthy before agents can safely act on Project Canon.",
    },
    tasks: [
      {
        id: "canon-contract",
        title: "Define agent readiness integrity behavior",
        files: ["opencanon/specs/index.ts", "opencanon/changes/index.ts"],
        checks: ["canon-render", "project-doctor"],
      },
      {
        id: "complete-activity-projection",
        title: "Batch complete Change Activity for state projections",
        files: ["packages/core/src/contracts-governance.ts", "packages/engine/src/index.ts", "crates/opencanon-engine/src/**", "packages/runtime/src/server-canon-events.ts", "packages/runtime/src/server-routes.ts", "packages/runtime/src/snapshot.ts", "packages/runtime/src/worktree-coordination.ts", "packages/runtime/test/client.test.ts", "tests/worktree.test.ts"],
        checks: ["engine-tests", "runtime-client-tests", "worktree-tests", "typecheck"],
        dependsOn: ["canon-contract"],
      },
      {
        id: "pipe-first-brief",
        title: "Restore pipe-first brief transport",
        files: ["packages/cli/src/brief.ts", "packages/cli/src/runtime-client.ts", "tests/cli-reporting.test.ts"],
        checks: ["cli-tests", "typecheck"],
        dependsOn: ["complete-activity-projection"],
      },
      {
        id: "live-knowledge-doctor",
        title: "Report live Project Knowledge in Doctor",
        files: ["packages/core/src/doctor-checks.ts", "packages/core/src/doctor-types.ts", "packages/core/src/doctor.ts", "packages/core/src/index.ts", "packages/cli/src/index.ts", "packages/cli/src/runtime-client.ts", "packages/cli/src/review.ts", "packages/runtime/src/server-change-runtime.ts", "packages/runtime/src/server-routes.ts", "tests/validator-runtime.test.ts", "tests/cli-reporting.test.ts"],
        checks: ["doctor-tests", "cli-tests", "typecheck"],
        dependsOn: ["pipe-first-brief"],
      },
      {
        id: "owned-check-runtimes",
        title: "Bind isolated Proof runtimes to their owner lifecycle",
        files: ["packages/runtime/src/cli.ts", "packages/runtime/src/service-control.ts", "packages/runtime/src/service-check-runtime.ts", "packages/runtime/src/server-change-runtime.ts", "packages/core/src/generated-state.ts", ".gitignore", "packages/runtime/test/service.test.ts", "packages/runtime/test/change-runs.test.ts", "tests/init.test.ts", "tests/init-flow.test.ts", "tests/validator-runtime.test.ts", "opencanon/areas/index.ts"],
        checks: ["service-lifecycle-tests", "change-run-tests", "init-tests", "typecheck"],
        dependsOn: ["live-knowledge-doctor"],
      },
      {
        id: "full-proof",
        title: "Prove agent readiness integrity end to end",
        files: ["package.json", ".gitignore", "packages/core/src/change.ts", "packages/core/src/contracts-change-runs.ts", "packages/core/src/generated-state.ts", "packages/core/src/index.ts", "packages/engine/src/index.ts", "crates/opencanon-engine/src/**", "packages/runtime/src/change-check-runner.ts", "packages/runtime/src/cli.ts", "packages/runtime/src/local-protocol.ts", "packages/runtime/src/server.ts", "packages/runtime/src/server-change-runtime.ts", "packages/runtime/src/server-http.ts", "packages/runtime/src/service-check-runtime.ts", "packages/runtime/src/service-control.ts", "packages/runtime/src/state.ts", "packages/runtime/test/change-run-test-support.ts", "packages/runtime/test/engine-binding-test-support.ts", "packages/runtime/test/change-runs.test.ts", "packages/runtime/test/runtime-supervision.test.ts", "packages/runtime/test/client-test-sources.ts", "packages/runtime/test/client.test.ts", "packages/runtime/test/engine.test.ts", "packages/runtime/test/semantic-index.test.ts", "packages/runtime/test/service.test.ts", "packages/runtime/test/state.test.ts", "tests/contracts.test.ts", "tests/cli-reporting.test.ts", "tests/init*.test.ts", "tests/validator-runtime.test.ts", "opencanon/areas/index.ts", "opencanon/specs/index.ts", "opencanon/changes/index.ts", "docs/opencanon/areas/local-service-and-runtimes.md", "docs/opencanon/specs/project-runtime-lifecycle-spec.md", "docs/opencanon/specs/runtime-operations-spec.md"],
        checks: ["contracts-tests", "change-run-tests", "runtime-supervision-tests", "service-lifecycle-tests", "init-tests", "engine-tests", "runtime-client-tests", "worktree-tests", "cli-tests", "doctor-tests", "typecheck", "project-validation", "project-doctor", "full-ci"],
        dependsOn: ["owned-check-runtimes"],
      },
    ],
    checks: [
      { id: "canon-render", kind: "command", command: "npm run opencanon -- canon render specs --dry-run" },
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "engine-tests", kind: "command", command: "npm run check:engine" },
      { id: "change-run-tests", kind: "test", target: "packages/runtime/test/change-runs.test.ts" },
      { id: "runtime-supervision-tests", kind: "test", target: "packages/runtime/test/runtime-supervision.test.ts" },
      { id: "service-lifecycle-tests", kind: "test", target: "packages/runtime/test/service.test.ts" },
      { id: "init-tests", kind: "command", command: "npx vitest run tests/init.test.ts tests/init-flow.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "cli-tests", kind: "test", target: "tests/cli-reporting.test.ts" },
      { id: "doctor-tests", kind: "test", target: "tests/validator-runtime.test.ts" },
      { id: "worktree-tests", kind: "test", target: "tests/worktree.test.ts" },
      { id: "typecheck", kind: "command", command: "npm run check:types" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --changed" },
      { id: "project-doctor", kind: "doctor" },
      { id: "full-ci", kind: "command", command: "npm run check:ci", timeoutMs: 10 * 60 * 1000 },
    ],
    render: { kind: "none" },
  }),
  defineChange({
    id: "runtime-operations-hardening",
    title: "Harden runtime operations and lifecycle integrity",
    kind: "fix",
    summary: "Isolate source runtime ownership, enforce Change transitions, bound operation history, and expose persisted runs through the CLI.",
    updates: {
      areas: ["local-service-and-runtimes", "project-map-governance"],
      specs: ["project-runtime-lifecycle-spec", "runtime-operations-spec"],
      surfaces: ["local-service-control", "project-canon-model", "project-knowledge-index", "release-update"],
    },
    scope: [
      { kind: DefinitionTargetKind.File, path: "opencanon/specs/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/changes/index.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/project-runtime-lifecycle-spec.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/runtime-operations-spec.md" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/change-state.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts-change-runs.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/problem.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/errors.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/generated-state.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon-architecture.md" },
      { kind: DefinitionTargetKind.Doc, path: "README.md" },
      { kind: DefinitionTargetKind.File, path: "packages/engine/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/**" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-change-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/change-check-runner.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/state.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/changes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/runtime-client.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/*.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/change-state.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/cli-reporting.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/contracts.test.ts" },
      { kind: DefinitionTargetKind.File, path: "package.json" },
    ],
    intent: {
      problem: "Source and installed runtimes can replace each other's process state, Changes can close with unfinished tasks, and persisted check runs have no total retention, admission, or independent CLI management.",
      outcome: "Runtime ownership is namespaced, lifecycle state is internally consistent, operation resources stay bounded, and every persisted run remains operable after its initiating client exits.",
      why: "Long-lived agent workflows need deterministic process ownership and durable operations without contradictory planning state or unbounded local resource growth.",
    },
    tasks: [
      {
        id: "canon-contract",
        title: "Define runtime operation hardening behavior",
        files: ["opencanon/specs/index.ts", "opencanon/changes/index.ts"],
        checks: ["canon-render", "project-doctor"],
      },
      {
        id: "namespace-isolation",
        title: "Isolate service and project process ownership by runtime namespace",
        files: ["packages/runtime/src/service*.ts", "packages/runtime/test/service.test.ts"],
        checks: ["service-tests", "typecheck"],
        dependsOn: ["canon-contract"],
      },
      {
        id: "lifecycle-integrity",
        title: "Enforce Change and task lifecycle transitions",
        files: ["packages/core/src/change-state.ts", "packages/runtime/src/server-change-runtime.ts", "packages/runtime/src/server-routes.ts", "tests/change-state.test.ts", "packages/runtime/test/client.test.ts"],
        checks: ["change-state-tests", "runtime-client-tests", "typecheck"],
        dependsOn: ["namespace-isolation"],
      },
      {
        id: "bounded-history",
        title: "Bound operation admission and persisted history",
        files: ["packages/core/src/contracts-change-runs.ts", "packages/engine/src/index.ts", "crates/opencanon-engine/src/**", "packages/runtime/src/change-check-runner.ts", "packages/runtime/src/state.ts", "packages/runtime/test/change-runs.test.ts"],
        checks: ["engine-tests", "change-run-tests", "typecheck"],
        dependsOn: ["lifecycle-integrity"],
      },
      {
        id: "run-cli",
        title: "Expose persisted run lifecycle commands",
        files: ["packages/runtime/src/server-routes.ts", "packages/runtime/src/routes.ts", "packages/cli/src/changes.ts", "packages/cli/src/runtime-client.ts", "tests/cli-reporting.test.ts"],
        checks: ["runtime-client-tests", "cli-tests", "typecheck"],
        dependsOn: ["bounded-history"],
      },
      {
        id: "full-proof",
        title: "Prove isolated, bounded, and recoverable workflows",
        checks: ["service-tests", "change-state-tests", "change-run-tests", "runtime-client-tests", "cli-tests", "project-validation", "project-doctor"],
        dependsOn: ["run-cli"],
      },
    ],
    checks: [
      { id: "canon-render", kind: "command", command: "npm run opencanon -- canon render specs --dry-run" },
      { id: "service-tests", kind: "test", target: "packages/runtime/test/service.test.ts" },
      { id: "change-state-tests", kind: "test", target: "tests/change-state.test.ts" },
      { id: "engine-tests", kind: "command", command: "npm run check:engine" },
      { id: "change-run-tests", kind: "test", target: "packages/runtime/test/change-runs.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "cli-tests", kind: "test", target: "tests/cli-reporting.test.ts" },
      { id: "typecheck", kind: "command", command: "npm run check:types" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --changed" },
      { id: "project-doctor", kind: "doctor" },
    ],
    render: { kind: "none" },
  }),
  defineChange({
    id: "runtime-operations",
    title: "Bounded status and observable runtime operations",
    kind: "feature",
    summary: "Make project status compact and execute Change checks as durable, replayable, cancellable runtime operations.",
    updates: {
      areas: ["local-service-and-runtimes", "project-map-governance"],
      specs: ["runtime-operations-spec"],
      surfaces: ["local-service-control", "project-canon-model", "project-knowledge-index", "release-update"],
    },
    scope: [
      { kind: DefinitionTargetKind.File, path: "opencanon/specs/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/changes/index.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/runtime-operations-spec.md" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts-change-runs.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/engine/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/**" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/local-protocol.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-http.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-server.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/change-check-runner.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/state.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/snapshot.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/cli*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/changes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/runtime-client.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/*.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/contracts.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/runtime-events.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/cli-reporting.test.ts" },
      { kind: DefinitionTargetKind.File, path: "package.json" },
    ],
    intent: {
      problem: "Status responses expose unbounded internal dependency paths, while long Change checks buffer output and look frozen until the request completes.",
      outcome: "Status remains small on large projects and every Change check has durable state, live replayable output, cancellation, and one terminal result.",
      why: "CLI, MCP, browser, and desktop clients need one predictable operation contract instead of transport-specific waiting, polling, or hidden buffers.",
    },
    tasks: [
      {
        id: "canon-contract",
        title: "Define bounded status and runtime operation behavior",
        files: ["opencanon/specs/index.ts", "opencanon/changes/index.ts"],
        checks: ["canon-render", "project-doctor"],
      },
      {
        id: "compact-status",
        title: "Separate compact public status from runtime inspection",
        files: ["packages/core/src/contracts-runtime.ts", "packages/runtime/src/snapshot.ts", "packages/runtime/src/cli-status.ts", "packages/runtime/src/cli.ts", "tests/contracts.test.ts", "packages/runtime/test/client.test.ts"],
        checks: ["contracts-tests", "runtime-client-tests", "typecheck"],
        dependsOn: ["canon-contract"],
      },
      {
        id: "persisted-check-runs",
        title: "Persist Change check runs and incremental output",
        files: ["packages/engine/src/index.ts", "crates/opencanon-engine/src/**", "packages/runtime/src/state.ts", "packages/runtime/src/server-change-runtime.ts", "packages/runtime/test/change-runs.test.ts"],
        checks: ["engine-tests", "change-run-tests", "typecheck"],
        dependsOn: ["compact-status"],
      },
      {
        id: "streaming-clients",
        title: "Stream, replay, and cancel Change check runs",
        files: ["packages/runtime/src/server-events.ts", "packages/runtime/src/server-routes.ts", "packages/cli/src/changes.ts", "packages/cli/src/runtime-client.ts", "packages/runtime/test/client.test.ts", "packages/runtime/test/change-runs.test.ts"],
        checks: ["change-run-tests", "runtime-client-tests", "service-tests", "typecheck"],
        dependsOn: ["persisted-check-runs"],
      },
      {
        id: "real-workflow-proof",
        title: "Prove status bounds and live check behavior",
        checks: ["change-run-tests", "runtime-client-tests", "project-validation", "project-doctor"],
        dependsOn: ["streaming-clients"],
      },
    ],
    checks: [
      { id: "canon-render", kind: "command", command: "npm run opencanon -- canon render specs --dry-run" },
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "engine-tests", kind: "command", command: "npm run check:engine" },
      { id: "change-run-tests", kind: "test", target: "packages/runtime/test/change-runs.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "service-tests", kind: "test", target: "packages/runtime/test/service.test.ts" },
      { id: "typecheck", kind: "command", command: "npm run check:types" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --changed" },
      { id: "project-doctor", kind: "doctor" },
    ],
    render: { kind: "none" },
  }),
  defineChange({
    id: "project-runtime-readiness",
    title: "Project runtime readiness",
    kind: "fix",
    summary: "Make project startup success, failure, repair, and restart behavior explicit across the service, runtime, and CLI.",
    updates: {
      areas: ["local-service-and-runtimes", "explicit-error-contracts"],
      specs: ["project-runtime-lifecycle-spec"],
      surfaces: ["local-service-control", "project-canon-model", "release-update"],
    },
    scope: [
      { kind: DefinitionTargetKind.File, path: "opencanon/changes/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/areas/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/specs/index.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/areas/local-service-and-runtimes.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/project-runtime-lifecycle-spec.md" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/service-contracts/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/cli.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/project-summary.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/runtime-client.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/search.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/update.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validator-graph.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/problem.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/service*.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/service-support.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/client.test.ts" },
    ],
    intent: {
      problem: "Project start can report success before health is ready, deterministic definition failures lose their typed cause, and automatic repair can retry failures that cannot succeed without a project edit.",
      outcome: "Every successful start is ready, every failed start returns one structured actionable cause, transient failures remain repairable, and deterministic project failures stop retrying.",
      why: "The service must be the single owner of project process lifecycle so CLI, MCP, desktop, and browser clients observe the same predictable state machine.",
    },
    tasks: [
      {
        id: "canon-contract",
        title: "Define the readiness contract",
        files: ["opencanon/areas/index.ts", "opencanon/specs/index.ts", "opencanon/changes/index.ts"],
        checks: ["canon-render", "project-doctor"],
      },
      {
        id: "ready-only-ensure",
        title: "Centralize ready-only project ensure",
        files: [
          "packages/runtime/src/service-start.ts",
          "packages/runtime/src/service-server.ts",
          "packages/runtime/src/cli.ts",
          "packages/cli/src/runtime-client.ts",
          "packages/cli/src/search.ts",
          "packages/runtime/test/service.test.ts",
          "packages/runtime/test/service-support.ts",
        ],
        checks: ["service-tests", "client-tests", "typecheck"],
        dependsOn: ["canon-contract"],
      },
      {
        id: "typed-startup-failure",
        title: "Carry typed startup failures across the process boundary",
        files: [
          "packages/core/src/problem.ts",
          "packages/core/src/validator-graph.ts",
          "packages/core/src/index.ts",
          "packages/runtime/src/service*.ts",
          "packages/runtime/src/cli.ts",
          "packages/cli/src/index.ts",
        ],
        checks: ["service-tests", "client-tests", "contracts-tests", "typecheck"],
        dependsOn: ["ready-only-ensure"],
      },
      {
        id: "retry-policy",
        title: "Stop retrying deterministic project failures",
        files: [
          "packages/runtime/src/service-lifecycle.ts",
          "packages/runtime/src/service-reconcile.ts",
          "packages/runtime/src/service-monitor.ts",
          "packages/runtime/src/service-types.ts",
          "packages/runtime/src/service-storage.ts",
          "packages/runtime/src/service-overview.ts",
          "packages/runtime/src/cli-status.ts",
          "packages/runtime/src/project-summary.ts",
          "packages/service-contracts/src/index.ts",
          "packages/cli/src/update.ts",
          "packages/runtime/test/service-reconcile.test.ts",
        ],
        checks: ["service-tests", "typecheck"],
        dependsOn: ["typed-startup-failure"],
      },
      {
        id: "real-project-proof",
        title: "Prove healthy and incomplete project flows",
        checks: ["service-tests", "client-tests", "project-validation", "project-doctor"],
        dependsOn: ["retry-policy"],
      },
    ],
    checks: [
      { id: "canon-render", kind: "command", command: "npm run opencanon -- canon render specs --dry-run" },
      { id: "service-tests", kind: "command", command: "npx vitest run packages/runtime/test/service.test.ts packages/runtime/test/service-reconcile.test.ts" },
      { id: "client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "typecheck", kind: "command", command: "npm run check:types" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --changed" },
      { id: "project-doctor", kind: "doctor" },
    ],
    render: { kind: "none" },
  }),
  defineChange({
    id: "pre-release-integrity-audit",
    title: "Close pre-release integrity gaps",
    kind: "fix",
    summary: "Make project governance complete, process teardown deterministic, derived vector state current-only, and release proof explicit and version-locked.",
    updates: {
      areas: ["local-service-and-runtimes", "project-knowledge-index", "runtime-release-update", "product-docs-and-guidance"],
      specs: ["project-runtime-lifecycle-spec", "release-integrity-spec"],
      surfaces: ["local-service-control", "project-canon-model", "project-knowledge-index", "release-update"],
    },
    scope: [
      { kind: DefinitionTargetKind.File, path: "opencanon.config.json" },
      { kind: DefinitionTargetKind.File, path: "opencanon/specs/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/changes/index.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/project-runtime-lifecycle-spec.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/release-integrity-spec.md" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-vector/**" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/Cargo.lock" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/project/semantic_store.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/tests/semantic_index.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-inference/Cargo.lock" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/validate.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/changes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/change-check-runner.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-check-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/knowledge-index-manager.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/semantic-index.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/*.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/mcp.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/worktree.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/validator-producers.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/release.test.ts" },
      { kind: DefinitionTargetKind.File, path: "scripts/check-release-consistency.ts" },
      { kind: DefinitionTargetKind.File, path: "scripts/prepare-opencanon-release.ts" },
      { kind: DefinitionTargetKind.File, path: "scripts/publish-opencanon-release.ts" },
      { kind: DefinitionTargetKind.File, path: ".github/workflows/release.yml" },
      { kind: DefinitionTargetKind.File, path: "package.json" },
      { kind: DefinitionTargetKind.Doc, path: "docs/language-support-foundation.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/runtime-update-security.md" },
    ],
    intent: {
      problem: "Full project Proof omits release-owned Rust crates, required producers can be checked against a different execution policy, private Proof registries leak or interrupt owned processes, derived vector files accept obsolete formats, and release version/publication checks do not cover every owned artifact.",
      outcome: "All authored release code is governed, required producers are bound to the Proof that used them, every run reaches an observable terminal state, old vector data rebuilds instead of loading, and one explicit audited release path moves every version together.",
      why: "A release gate is trustworthy only when its inventory, producer generation, process steady state, derived data formats, dependency security, and publication trigger are complete and deterministic.",
    },
    tasks: [
      {
        id: "canon-contract",
        title: "Define pre-release integrity behavior",
        files: ["opencanon/specs/index.ts", "opencanon/changes/index.ts"],
        checks: ["canon-render", "project-doctor"],
      },
      {
        id: "complete-source-governance",
        title: "Govern every authored crate and split vector database ownership",
        files: ["opencanon.config.json", "crates/opencanon-vector/src/**", "tests/release.test.ts"],
        checks: ["vector-tests", "release-tests", "project-validation", "typecheck"],
        dependsOn: ["canon-contract"],
      },
      {
        id: "current-vector-formats",
        title: "Reject obsolete vector formats and rebuild derived state",
        files: ["crates/opencanon-vector/src/**", "crates/opencanon-engine/src/project.rs", "crates/opencanon-engine/src/project/semantic_status.rs", "crates/opencanon-engine/src/project/semantic_store.rs", "crates/opencanon-engine/src/tests/semantic_index.rs", "packages/runtime/src/knowledge-index-manager.ts", "packages/runtime/test/semantic-index.test.ts"],
        checks: ["vector-tests", "engine-tests", "semantic-index-tests"],
        dependsOn: ["complete-source-governance"],
      },
      {
        id: "owned-test-processes",
        title: "Retire every process owned by isolated tests",
        files: ["packages/runtime/src/service-check-runtime.ts", "packages/runtime/test/*.test.ts", "tests/setup-vitest.ts", "tests/mcp.test.ts", "tests/worktree.test.ts", "tests/validate-cli-fast-path.test.ts", "tests/cli-reporting.test.ts", "scripts/check-test-processes.ts", "package.json"],
        checks: ["service-tests", "change-run-tests", "runtime-client-tests", "mcp-tests", "worktree-tests", "process-steady-state"],
        dependsOn: ["canon-contract"],
      },
      {
        id: "proof-terminal-contracts",
        title: "Bind required producers and reconnect interrupted Proof clients",
        files: [
          "packages/cli/src/validate.ts",
          "packages/cli/src/changes.ts",
          "packages/core/src/contracts-change-runs.ts",
          "packages/runtime/src/change-check-runner.ts",
          "packages/runtime/src/server.ts",
          "packages/runtime/src/server-events.ts",
          "packages/runtime/src/server-routes.ts",
          "packages/runtime/test/change-runs.test.ts",
          "crates/opencanon-engine/src/state.rs",
          "crates/opencanon-engine/src/migrations/**",
          "crates/opencanon-engine/src/tests/**",
          "tests/cli-reporting.test.ts",
          "tests/contracts.test.ts",
          "tests/validate-cli-fast-path.test.ts",
          "tests/validator-producers.test.ts",
        ],
        checks: ["validator-producer-tests", "change-run-tests", "runtime-client-tests", "cli-tests", "project-validation"],
        dependsOn: ["complete-source-governance", "owned-test-processes"],
      },
      {
        id: "dependency-security",
        title: "Patch Rust soundness advisories and gate all lockfiles",
        files: ["package.json", "crates/*/Cargo.toml", "crates/*/Cargo.lock", ".github/workflows/release.yml", "tests/release.test.ts"],
        checks: ["dependency-audit", "engine-tests", "inference-tests", "vector-tests", "release-tests"],
        dependsOn: ["current-vector-formats"],
      },
      {
        id: "release-publication-integrity",
        title: "Lock versions and require explicit release dispatch",
        files: ["scripts/check-release-consistency.ts", "scripts/prepare-opencanon-release.ts", "scripts/publish-opencanon-release.ts", ".github/workflows/release.yml", "tests/release.test.ts", "docs/runtime-update-security.md"],
        checks: ["release-tests", "release-check"],
        dependsOn: ["dependency-security"],
      },
      {
        id: "durable-docs-only",
        title: "Remove stale implementation plans from durable docs",
        files: ["docs/convention-model-strawman.ts", "docs/ast-facts-migration.md", "docs/polyglot-facts-plan.md", "docs/producer-status-plan.md", "docs/language-support-foundation.md", "docs/runtime-update-security.md"],
        checks: ["release-tests", "project-doctor"],
        dependsOn: ["release-publication-integrity"],
      },
      {
        id: "full-proof",
        title: "Prove release integrity and clean steady state",
        checks: ["typecheck", "vector-tests", "engine-tests", "inference-tests", "service-tests", "runtime-client-tests", "mcp-tests", "worktree-tests", "release-tests", "dependency-audit", "project-validation", "project-doctor", "process-steady-state", "full-ci"],
        dependsOn: ["proof-terminal-contracts", "durable-docs-only"],
      },
    ],
    checks: [
      { id: "canon-render", kind: "command", command: "npm run opencanon -- canon render specs --dry-run" },
      { id: "typecheck", kind: "command", command: "npm run check:types" },
      { id: "vector-tests", kind: "command", command: "cargo test --manifest-path crates/opencanon-vector/Cargo.toml" },
      { id: "engine-tests", kind: "command", command: "npm run check:engine" },
      { id: "inference-tests", kind: "command", command: "npm run check:inference" },
      { id: "semantic-index-tests", kind: "test", target: "packages/runtime/test/semantic-index.test.ts" },
      { id: "service-tests", kind: "command", command: "npx vitest run packages/runtime/test/service.test.ts packages/runtime/test/service-reconcile.test.ts" },
      { id: "change-run-tests", kind: "test", target: "packages/runtime/test/change-runs.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "validator-producer-tests", kind: "test", target: "tests/validator-producers.test.ts" },
      { id: "cli-tests", kind: "command", command: "npx vitest run tests/validate-cli-fast-path.test.ts tests/cli-reporting.test.ts" },
      { id: "mcp-tests", kind: "test", target: "tests/mcp.test.ts" },
      { id: "worktree-tests", kind: "test", target: "tests/worktree.test.ts" },
      { id: "release-tests", kind: "test", target: "tests/release.test.ts" },
      { id: "dependency-audit", kind: "command", command: "npm run security:audit" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --project --require-producer typescript" },
      { id: "project-doctor", kind: "doctor" },
      { id: "process-steady-state", kind: "command", command: "node scripts/check-test-processes.ts" },
      { id: "release-check", kind: "command", command: "npm run release:check" },
      { id: "full-ci", kind: "command", command: "npm run check:ci", timeoutMs: 10 * 60 * 1000 },
    ],
    render: { kind: "none" },
  }),
];
