import { DefinitionTargetKind, defineChange } from "@opencanon/core";

export default [
  defineChange({
    id: "area-change-model",
    title: "Area and Change Model",
    kind: "feature",
    summary:
      "OpenCanon can define permanent areas, active changes, and cross-definition relationships as typed source of truth with generated docs, derived project state, CLI access, MCP access, and local API visibility.",
    updates: {
      areas: [
        "company-read-model",
        "project-map-governance",
        "project-context-index",
        "local-service-and-runtimes",
        "living-conventions",
        "product-docs-and-guidance",
        "definition-authoring-flow",
        "agent-feedback-and-gates",
        "runtime-release-update",
      ],
      specs: ["spec-governance-model"],
      conventions: ["service-events-current"],
      surfaces: ["company-read-model", "local-service-control", "project-canon-model", "project-context-index", "release-update"],
      docs: [
        "docs/opencanon/canon/architecture.md",
        "docs/opencanon/canon/service-events-current.md",
        "docs/opencanon/areas/company-read-model.md",
        "docs/opencanon/areas/definition-authoring-flow.md",
        "docs/opencanon/areas/project-map-governance.md",
        "docs/opencanon/areas/project-context-index.md",
        "docs/opencanon/areas/local-service-and-runtimes.md",
        "docs/opencanon/areas/living-conventions.md",
        "docs/opencanon/areas/agent-feedback-and-gates.md",
        "docs/opencanon/areas/product-docs-and-guidance.md",
        "docs/opencanon/areas/runtime-release-update.md",
        "docs/opencanon/specs/spec-governance-model.md",
      ],
    },
    scope: [
      { kind: DefinitionTargetKind.File, path: "package.json" },
      { kind: DefinitionTargetKind.File, path: "package-lock.json" },
      { kind: DefinitionTargetKind.File, path: "vitest.config.ts" },
      { kind: DefinitionTargetKind.File, path: ".github/workflows/**" },
      { kind: DefinitionTargetKind.File, path: ".opencode/plugins/opencanon.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/service-contracts/**" },
      { kind: DefinitionTargetKind.File, path: "packages/distribution/**" },
      { kind: DefinitionTargetKind.File, path: "packages/observability/**" },
      { kind: DefinitionTargetKind.File, path: "packages/core/package.json" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/area.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/area-loader.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/area-render.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/spec.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/spec-loader.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/spec-render.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/change.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/change-loader.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/change-render.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/context.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/core-utils.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/core.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/definition-graph.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/semantic-index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/semantic-models.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/definition-target.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/feedback.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/hooks.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/language-analyzer.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/opencanon-skill.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/project-types.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/producer-registry.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/release-keys.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/testing.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/type-facts-provider.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validator.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/validator-graph.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/areas.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/specs.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/changes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/conventions.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/context.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/analyze.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/baseline.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/feedback.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/init-flow.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/update.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/validate.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/project-types-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/runtime-client.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/engine/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/local-protocol.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/cli.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/state.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/semantic-index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/type-producer/producer-main.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/type-producer/runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-fs.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/snapshot.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/**" },
      { kind: DefinitionTargetKind.File, path: "packages/validators/src/**" },
      { kind: DefinitionTargetKind.File, path: "packages/validators/package.json" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/**" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-vector/**" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-inference/**" },
      { kind: DefinitionTargetKind.File, path: "scripts/**" },
      { kind: DefinitionTargetKind.File, path: "opencanon/areas/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/specs/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/changes/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/conventions/docs-only-conventions.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/conventions/no-secret-like-literals.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/conventions/spec-definitions-are-enforced.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/fixtures/**" },
      { kind: DefinitionTargetKind.File, path: "tests/**" },
      { kind: DefinitionTargetKind.File, path: "examples/projects/**" },
      { kind: DefinitionTargetKind.File, path: "apps/site/**" },
      { kind: DefinitionTargetKind.File, path: "examples/conventions/**" },
      { kind: DefinitionTargetKind.Doc, path: "README.md" },
      { kind: DefinitionTargetKind.Doc, path: "AGENTS.md" },
      { kind: DefinitionTargetKind.Doc, path: "CLAUDE.md" },
      { kind: DefinitionTargetKind.Doc, path: ".agents/skills/opencanon/SKILL.md" },
      { kind: DefinitionTargetKind.Doc, path: ".agents/skills/opencanon/**" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/canon/architecture.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/runtime-update-security.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/canon/service-events-current.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/areas/company-read-model.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/areas/definition-authoring-flow.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/areas/project-map-governance.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/areas/project-context-index.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/areas/local-service-and-runtimes.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/areas/living-conventions.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/areas/agent-feedback-and-gates.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/areas/product-docs-and-guidance.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/areas/runtime-release-update.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/changes/area-change-model.md" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/spec-governance-model.md" },
    ],
    intent: {
      problem: "Product behavior, active change, and their relationships were not first-class typed definitions.",
      outcome:
        "Areas, changes, surfaces, conventions, checks, and targets can be parsed into a Project Map, validated by doctor, rendered into docs, persisted as derived project state, and exposed through CLI, MCP, and local APIs.",
      why: "Agents and humans need product-level context, state ownership, change-aware validation, and simple product language, not only file findings and validator lists.",
    },
    plan: [
      { id: "board-state", title: "Derive Change board columns from change-level events and task aggregate state", checks: ["runtime-tests"] },
      { id: "context-index-recovery", title: "Repair generated semantic vectors when cached metadata points at missing vectors", checks: ["semantic-index-tests"] },
      { id: "cli-and-copy", title: "Remove stale command aliases and keep CLI and README examples on current surfaces", checks: ["service-lifecycle-tests"] },
      { id: "examples-and-hooks", title: "Refresh example projects and hooks so they teach the current runtime-owned workflow", checks: ["project-doctor", "typecheck"] },
      { id: "canon-dogfood", title: "Keep active Change tasks scoped to current work instead of completed historical migrations", checks: ["project-doctor"] },
      { id: "runtime-repair-hardening", title: "Make supervised runtime repair deterministic across worktrees and stale pipes", checks: ["runtime-tests", "service-lifecycle-tests", "worktree-tests"] },
      { id: "release-gate-proof", title: "Ensure release test gates include every committed test file", checks: ["release-tests", "test-tree"] },
      { id: "headless-runtime-split", title: "Keep the main branch focused on CLI, MCP, local service, runtime, and versioned APIs", checks: ["typecheck", "release-tests", "release-check", "runtime-build"] },
    ],
    tasks: [
      {
        id: "board-state",
        title: "Keep task events from closing whole Changes in the board projection",
        files: ["packages/runtime/src/snapshot.ts", "packages/runtime/test/client.test.ts"],
        surfaces: ["project-canon-model"],
        checks: ["runtime-tests"],
      },
      {
        id: "context-index-recovery",
        title: "Rebuild semantic vectors after missing-vector reuse failures",
        files: ["packages/runtime/src/snapshot.ts", "packages/runtime/test/semantic-index.test.ts"],
        surfaces: ["project-context-index"],
        checks: ["semantic-index-tests"],
      },
      {
        id: "cli-copy-cleanup",
        title: "Remove stale Change check alias and refresh current command copy",
        files: [
          "packages/cli/src/changes.ts",
          "packages/cli/src/context.ts",
          "README.md",
          "crates/opencanon-engine/src/state.rs",
          "packages/runtime/test/service.test.ts",
        ],
        surfaces: ["project-canon-model"],
        checks: ["service-lifecycle-tests"],
      },
      {
        id: "examples-current-canon",
        title: "Replace old decision examples with current Project Canon definitions",
        files: ["examples/projects/**"],
        surfaces: ["project-canon-model"],
        checks: ["project-doctor"],
      },
      {
        id: "hook-and-export-cleanup",
        title: "Expose hook failures and remove stale package export paths",
        files: [".opencode/plugins/opencanon.ts", "packages/core/package.json", "packages/core/src/opencanon-skill.ts", "packages/service-contracts/src/index.ts"],
        surfaces: ["project-canon-model", "local-service-control"],
        checks: ["typecheck"],
      },
      {
        id: "release-gate-proof",
        title: "Make the release test gate cover every committed test file",
        files: ["package.json", "tests/release.test.ts"],
        surfaces: ["release-update"],
        checks: ["release-tests", "test-tree"],
      },
      {
        id: "release-update-hardening",
        title: "Harden updater safety, release watching, hook scoping, and machine-readable CLI output",
        files: [
          "packages/cli/src/update.ts",
          "packages/cli/src/feedback.ts",
          "packages/cli/src/analyze.ts",
          "packages/core/src/hooks.ts",
          "scripts/publish-opencanon-release.ts",
          "docs/runtime-update-security.md",
          "README.md",
          "tests/update-guard.test.ts",
          "tests/feedback.test.ts",
          "tests/validator.test.ts",
          "tests/release.test.ts",
        ],
        surfaces: ["release-update", "local-service-control", "project-canon-model"],
        checks: ["release-tests", "typecheck", "project-doctor"],
      },
      {
        id: "runtime-repair-hardening",
        title: "Make supervised runtime repair deterministic across worktrees and stale pipes",
        files: [
          "packages/cli/src/brief.ts",
          "packages/cli/src/changes.ts",
          "packages/cli/src/runtime-client.ts",
          "packages/cli/src/validate.ts",
          "packages/core/src/index.ts",
          "packages/core/src/language-analyzer.ts",
          "packages/core/src/producer-registry.ts",
          "packages/core/src/type-facts-provider.ts",
          "packages/core/src/validator.ts",
          "packages/runtime/src/server.ts",
          "packages/runtime/src/service.ts",
          "packages/runtime/src/type-producer/producer-main.ts",
          "packages/runtime/src/type-producer/runtime.ts",
          "packages/runtime/test/type-producer.test.ts",
          "packages/runtime/test/service.test.ts",
          "tests/validator.test.ts",
          "tests/worktree.test.ts",
        ],
        surfaces: ["local-service-control"],
        checks: ["runtime-tests", "service-lifecycle-tests", "worktree-tests"],
      },
      {
        id: "headless-runtime-split",
        title: "Split retired UI and site surfaces away from the runtime API branch",
        files: [
          "package.json",
          "package-lock.json",
          "vitest.config.ts",
          ".github/workflows/**",
          "packages/service-contracts/**",
          "packages/runtime/**",
          "packages/validators/**",
          "apps/site/**",
          "opencanon/fixtures/**",
          "scripts/**",
          "README.md",
        ],
        surfaces: ["local-service-control", "project-canon-model", "release-update"],
        checks: ["typecheck", "release-tests", "release-check", "runtime-build"],
      },
    ],
    checks: [
      { id: "project-doctor", kind: "doctor" },
      { id: "typecheck", kind: "command", command: "npm run check:types" },
      { id: "definition-graph-tests", kind: "test", target: "tests/definition-graph.test.ts" },
      { id: "convention-tests", kind: "test", target: "tests/convention.test.ts" },
      { id: "engine-product-model-tests", kind: "test", target: "crates/opencanon-engine/src/tests.rs" },
      { id: "engine-wrapper-tests", kind: "test", target: "packages/runtime/test/engine.test.ts" },
      { id: "runtime-state-tests", kind: "test", target: "packages/runtime/test/state.test.ts" },
      { id: "runtime-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "service-lifecycle-tests", kind: "test", target: "packages/runtime/test/service.test.ts" },
      { id: "semantic-index-tests", kind: "test", target: "packages/runtime/test/semantic-index.test.ts" },
      { id: "worktree-tests", kind: "test", target: "tests/worktree.test.ts" },
      { id: "release-tests", kind: "test", target: "tests/release.test.ts" },
      { id: "release-check", kind: "command", command: "npm run release:check" },
      { id: "runtime-build", kind: "command", command: "npm run build:runtime -- --skip-engine" },
      { id: "test-tree", kind: "command", command: "npm run test:tree" },
    ],
    render: { kind: "generated", docs: "docs/opencanon/changes/area-change-model.md", style: "reference" },
  }),
];
