import { DefinitionTargetKind, defineChange } from "@opencanon/core";

export const runtimeSupervisionChanges = [
  defineChange({
    id: "observation-only-doctor",
    title: "Keep Doctor observation-only",
    kind: "fix",
    summary: "Prevent diagnostic producer inspection from starting repository-wide project work.",
    updates: {
      areas: ["local-service-and-runtimes"],
      specs: ["project-runtime-lifecycle-spec", "runtime-operations-spec"],
      surfaces: ["local-service-control", "project-canon-model"],
    },
    scope: [
      { kind: DefinitionTargetKind.File, path: "packages/core/src/type-facts-provider.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/doctor.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/cli/src/runtime-client.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-overview.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/type-producer/*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/type-producer.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/client*.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/validator-runtime.test.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/cli-reporting.test.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/specs/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/changes/runtime-supervision.ts" },
    ],
    intent: {
      problem: "Doctor warmed the lazy TypeScript producer, whose ready callback scheduled full project validation in the serving runtime and temporarily made both transports unavailable.",
      outcome: "Doctor reads bounded live state without starting work; producers start only for typed validation, and that validation publishes the generation it consumed without a redundant readiness rebuild.",
      why: "A diagnostic must not create the failure it is measuring, and producer lifecycle notifications must not become hidden repository-wide commands.",
    },
    tasks: [
      {
        id: "define-observation-contract",
        title: "Define observation-only diagnostics and explicit producer idle state",
        files: ["opencanon/specs/index.ts", "opencanon/changes/runtime-supervision.ts", "packages/core/src/type-facts-provider.ts", "packages/core/src/doctor.ts"],
        checks: ["canon-render", "doctor-tests", "runtime-types"],
      },
      {
        id: "remove-hidden-warm-work",
        title: "Remove diagnostic warming and producer-ready rebuilds",
        files: ["packages/cli/src/index.ts", "packages/cli/src/runtime-client.ts", "packages/runtime/src/server.ts", "packages/runtime/src/server-routes.ts", "packages/runtime/src/service-overview.ts", "packages/runtime/src/type-producer/runtime.ts", "packages/runtime/src/type-producer/live-provider.ts"],
        checks: ["producer-tests", "runtime-client-tests", "cli-tests", "runtime-types"],
        dependsOn: ["define-observation-contract"],
      },
      {
        id: "prove-continuous-availability",
        title: "Prove Doctor preserves runtime availability",
        files: ["packages/runtime/test/type-producer.test.ts", "packages/runtime/test/client-test-sources.ts", "packages/runtime/test/client.test.ts", "tests/validator-runtime.test.ts", "tests/cli-reporting.test.ts"],
        checks: ["producer-tests", "doctor-tests", "runtime-client-tests", "cli-tests", "process-steady-state", "full-ci"],
        dependsOn: ["remove-hidden-warm-work"],
      },
    ],
    checks: [
      { id: "canon-render", kind: "command", command: "npm run opencanon -- canon render specs --dry-run" },
      { id: "producer-tests", kind: "test", target: "packages/runtime/test/type-producer.test.ts" },
      { id: "doctor-tests", kind: "test", target: "tests/validator-runtime.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "cli-tests", kind: "test", target: "tests/cli-reporting.test.ts" },
      { id: "runtime-types", kind: "command", command: "npm run check:types" },
      { id: "process-steady-state", kind: "command", command: "npm run check:test-processes" },
      { id: "full-ci", kind: "command", command: "npm run check:ci", timeoutMs: 10 * 60 * 1000 },
    ],
    render: { kind: "none" },
  }),
  defineChange({
    id: "nonblocking-project-refresh",
    title: "Keep project refresh responsive",
    kind: "fix",
    summary: "Keep the serving runtime responsive by isolating complete project analysis and deriving graph deltas in dedicated state.",
    updates: {
      areas: ["local-service-and-runtimes"],
      specs: ["project-runtime-lifecycle-spec", "runtime-operations-spec"],
      surfaces: ["local-service-control", "project-knowledge-index", "project-canon-model", "release-update"],
    },
    scope: [
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/project.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/project/code_graph_connection.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/project/code_graph_store.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/state.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/migrations/012_separate_code_graph.sql" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/tests/code_graph.rs" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/tests/jobs.rs" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/contracts-code-graph.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/engine/src/index.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/project-source-snapshot.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/project-analysis-operation.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/project-analysis-protocol.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/project-analysis-worker.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/project-analysis-worker-main.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/activity-projection.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/change-check-runner.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server-routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/server.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-identity.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-namespace.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/snapshot.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/state-manager.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/state.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/engine-async.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/engine.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/client-test-sources.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/project-analysis.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/project-source-snapshot.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/semantic-index.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/service.test.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/state-manager.test.ts" },
      { kind: DefinitionTargetKind.File, path: "scripts/build-opencanon-runtime.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/cli-reporting.test.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/specs/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/changes/runtime-supervision.ts" },
      { kind: DefinitionTargetKind.File, path: "package.json" },
    ],
    intent: {
      problem: "A watcher refresh synchronously rebuilt the complete native code graph in the serving runtime, blocking pipe and HTTP long enough for supervision to replace a live project runtime.",
      outcome: "A subordinate analysis process owns discovery, fact extraction, graph updates, and project validation; the serving runtime atomically publishes only the latest complete snapshot, graph generation, product model, and Change catalog while native graph transactions derive deltas in dedicated SQLite WAL state.",
      why: "The serving runtime must remain available through analysis CPU, memory pressure, native failure, and cancellation; unrelated Activity writes must not contend with graph transactions, and disposable graph state must rebuild correctly when absent.",
    },
    tasks: [
      {
        id: "define-refresh-availability",
        title: "Define continuous transport availability during source refresh",
        files: ["opencanon/specs/index.ts", "opencanon/changes/runtime-supervision.ts"],
        checks: ["canon-render", "runtime-types"],
      },
      {
        id: "isolate-native-graph-write",
        title: "Run native graph writes asynchronously with bounded memory",
        files: ["crates/opencanon-engine/src/project.rs", "crates/opencanon-engine/src/project/code_graph_connection.rs", "crates/opencanon-engine/src/project/code_graph_store.rs", "crates/opencanon-engine/src/state.rs", "crates/opencanon-engine/src/migrations/012_separate_code_graph.sql", "crates/opencanon-engine/src/tests/jobs.rs", "packages/engine/src/index.ts"],
        checks: ["engine-rust-tests", "engine-async-tests", "runtime-types"],
        dependsOn: ["define-refresh-availability"],
      },
      {
        id: "apply-source-deltas",
        title: "Derive graph deltas from complete source identity",
        files: ["packages/core/src/contracts-code-graph.ts", "crates/opencanon-engine/src/project/code_graph_store.rs", "packages/runtime/src/project-source-snapshot.ts", "packages/runtime/src/snapshot.ts", "packages/runtime/test/project-source-snapshot.test.ts"],
        checks: ["source-refresh-tests", "runtime-types"],
        dependsOn: ["isolate-native-graph-write"],
      },
      {
        id: "isolate-project-analysis",
        title: "Run complete refresh in a cancellable analysis process",
        files: ["packages/runtime/src/project-analysis-operation.ts", "packages/runtime/src/project-analysis-protocol.ts", "packages/runtime/src/project-analysis-worker.ts", "packages/runtime/src/project-analysis-worker-main.ts", "packages/runtime/src/activity-projection.ts", "packages/runtime/src/change-check-runner.ts", "packages/runtime/src/server-routes.ts", "packages/runtime/src/server.ts", "packages/runtime/src/snapshot.ts", "packages/runtime/src/state-manager.ts", "packages/runtime/src/state.ts", "packages/runtime/test/client-test-sources.ts", "packages/runtime/test/project-analysis.test.ts", "packages/runtime/test/state-manager.test.ts", "scripts/build-opencanon-runtime.ts"],
        checks: ["project-analysis-tests", "runtime-types", "process-steady-state"],
        dependsOn: ["apply-source-deltas"],
      },
      {
        id: "prove-refresh-availability",
        title: "Prove cold and incremental refresh preserve availability",
        files: ["packages/runtime/src/service-identity.ts", "packages/runtime/src/service-namespace.ts", "packages/runtime/test/engine-async.test.ts", "packages/runtime/test/engine.test.ts", "packages/runtime/test/service.test.ts", "tests/cli-reporting.test.ts", "package.json"],
        checks: ["engine-async-tests", "runtime-integration", "process-steady-state", "full-ci"],
        dependsOn: ["isolate-project-analysis"],
      },
    ],
    checks: [
      { id: "canon-render", kind: "command", command: "npm run opencanon -- canon render specs --dry-run" },
      { id: "engine-rust-tests", kind: "command", command: "cargo test --manifest-path crates/opencanon-engine/Cargo.toml" },
      { id: "engine-async-tests", kind: "test", target: "packages/runtime/test/engine-async.test.ts" },
      { id: "source-refresh-tests", kind: "test", target: "packages/runtime/test/project-source-snapshot.test.ts" },
      { id: "project-analysis-tests", kind: "test", target: "packages/runtime/test/project-analysis.test.ts" },
      { id: "runtime-types", kind: "command", command: "npm run check:types" },
      { id: "runtime-integration", kind: "command", command: "npm run test:runtime-integration", timeoutMs: 10 * 60 * 1000 },
      { id: "process-steady-state", kind: "command", command: "npm run check:test-processes" },
      { id: "full-ci", kind: "command", command: "npm run check:ci", timeoutMs: 10 * 60 * 1000 },
    ],
    render: { kind: "none" },
  }),
  defineChange({
    id: "runtime-health-confirmation",
    title: "Confirm runtime health failures before replacement",
    kind: "fix",
    summary: "Keep a live project runtime through one transient failed health probe before replacing it.",
    updates: {
      areas: ["local-service-and-runtimes"],
      specs: ["project-runtime-lifecycle-spec", "runtime-operations-spec"],
      surfaces: ["local-service-control", "project-canon-model", "release-update"],
    },
    scope: [
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-lifecycle.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-monitor.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-reconcile.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-render.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-storage.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-types.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/service-reconcile.test.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/changes/runtime-supervision.ts" },
    ],
    intent: {
      problem: "One delayed health response can make the supervisor replace a live project runtime and interrupt an active Proof run.",
      outcome: "Dead runtimes still repair immediately, while a live but temporarily unresponsive runtime gets one reconciliation interval to recover before replacement.",
      why: "Liveness supervision must distinguish process death from transient event-loop pressure without hiding persistent failures.",
    },
    tasks: [
      {
        id: "confirm-live-runtime-health",
        title: "Add health confirmation hysteresis for live runtimes",
        files: [
          "packages/runtime/src/service-lifecycle.ts",
          "packages/runtime/src/service-monitor.ts",
          "packages/runtime/src/service-reconcile.ts",
          "packages/runtime/src/service-render.ts",
          "packages/runtime/src/service-storage.ts",
          "packages/runtime/src/service-types.ts",
          "packages/runtime/test/service-reconcile.test.ts",
        ],
        checks: ["service-reconcile-tests", "runtime-types", "process-steady-state"],
      },
    ],
    checks: [
      { id: "service-reconcile-tests", kind: "test", target: "packages/runtime/test/service-reconcile.test.ts" },
      { id: "runtime-types", kind: "command", command: "npm run check:types" },
      { id: "process-steady-state", kind: "command", command: "npm run check:test-processes" },
    ],
    render: { kind: "none" },
  }),
  defineChange({
    id: "registered-worker-lease-ownership",
    title: "Keep registered worker ownership authoritative",
    kind: "fix",
    summary: "Prevent delayed worker heartbeats from bypassing runtime health confirmation.",
    updates: {
      areas: ["local-service-and-runtimes"],
      specs: ["project-runtime-lifecycle-spec", "runtime-operations-spec"],
      surfaces: ["local-service-control", "project-canon-model"],
    },
    scope: [
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-process.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-reconcile.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-start.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/service-storage.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/service-reconcile.test.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/changes/runtime-supervision.ts" },
    ],
    intent: {
      problem: "A delayed worker-lock heartbeat can make reconciliation retire the same live PID already owned by the runtime registry before health confirmation runs.",
      outcome: "The registry remains authoritative for its live worker PID; only dead or differently owned leases are retired as conflicts.",
      why: "Lease conflict repair and runtime health supervision must not make competing lifecycle decisions about the same registered process.",
    },
    tasks: [
      {
        id: "preserve-registered-worker",
        title: "Preserve registered workers through delayed heartbeats",
        files: [
          "packages/runtime/src/service-process.ts",
          "packages/runtime/src/service-reconcile.ts",
          "packages/runtime/src/service-start.ts",
          "packages/runtime/src/service-storage.ts",
          "packages/runtime/test/service-reconcile.test.ts",
        ],
        checks: ["service-reconcile-tests", "runtime-types", "process-steady-state"],
      },
    ],
    checks: [
      { id: "service-reconcile-tests", kind: "test", target: "packages/runtime/test/service-reconcile.test.ts" },
      { id: "runtime-types", kind: "command", command: "npm run check:types" },
      { id: "process-steady-state", kind: "command", command: "npm run check:test-processes" },
    ],
    render: { kind: "none" },
  }),
];
