import { DefinitionTargetKind, defineChange } from "@opencanon/core";

export const serviceOwnedInferenceChanges = [
  defineChange({
    id: "service-owned-inference",
    title: "Centralize native inference in the service",
    kind: "refactor",
    summary: "Replace per-project model processes with one bounded service coordinator and isolated native inference host.",
    updates: {
      areas: ["project-knowledge-index", "local-service-and-runtimes"],
      specs: ["runtime-operations-spec"],
      surfaces: ["project-knowledge-index", "local-service-control", "project-canon-model", "release-update"],
    },
    scope: [
      { kind: DefinitionTargetKind.File, path: "opencanon/specs/index.ts" },
      { kind: DefinitionTargetKind.File, path: "opencanon/changes/service-owned-inference.ts" },
      { kind: DefinitionTargetKind.Doc, path: "docs/opencanon/specs/runtime-operations-spec.md" },
      { kind: DefinitionTargetKind.File, path: "packages/service-contracts/src/**" },
      { kind: DefinitionTargetKind.File, path: "packages/core/src/{context,contracts-semantic,index,semantic-index,semantic-models}.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/engine/src/**" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/{inference,knowledge,semantic,service,server,doctor}*.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/local-protocol.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/src/routes.ts" },
      { kind: DefinitionTargetKind.File, path: "packages/runtime/test/{client,semantic-index,service,inference}*.test.ts" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-inference/src/**" },
      { kind: DefinitionTargetKind.File, path: "crates/opencanon-engine/src/**" },
      { kind: DefinitionTargetKind.File, path: "scripts/{build-opencanon-runtime,check-test-processes,native-embedding-smoke}.ts" },
      { kind: DefinitionTargetKind.File, path: "tests/{cli-reporting,contracts,validator-runtime}.test.ts" },
      { kind: DefinitionTargetKind.File, path: "package.json" },
    ],
    intent: {
      problem: "Indexing loads a disposable native model, every queried project retains another model process, project config mixes durable vector identity with machine hardware controls, and native embedding silently truncates over-budget text.",
      outcome: "One global coordinator admits exact-token inference through an isolated shared host, projects retain independent Knowledge state, model residency is bounded and observable, and invalid input fails explicitly without data loss.",
      why: "Project Knowledge must scale across projects without multiplying native memory or allowing optional inference to destabilize the required service, runtime, Canon, and Proof paths.",
    },
    tasks: [
      {
        id: "canon-contract",
        title: "Define service-owned inference behavior",
        files: ["opencanon/specs/index.ts", "opencanon/changes/service-owned-inference.ts", "docs/opencanon/specs/runtime-operations-spec.md"],
        checks: ["canon-render", "project-doctor"],
      },
      {
        id: "provider-contracts",
        title: "Separate durable model identity from machine execution policy",
        files: ["packages/service-contracts/src/**", "packages/core/src/{context,contracts-semantic,index,semantic-index,semantic-models}.ts", "packages/runtime/src/inference*.ts", "tests/contracts.test.ts"],
        checks: ["contracts-tests", "typecheck"],
        dependsOn: ["canon-contract"],
      },
      {
        id: "native-host",
        title: "Build exact-token native inference host",
        files: ["crates/opencanon-inference/src/**", "crates/opencanon-engine/src/**", "packages/engine/src/**", "packages/runtime/src/inference-host*.ts"],
        checks: ["inference-tests", "engine-tests", "typecheck"],
        dependsOn: ["provider-contracts"],
      },
      {
        id: "service-coordinator",
        title: "Own admission, scheduling, cancellation, residency, and eviction in the service",
        files: ["packages/runtime/src/inference*.ts", "packages/runtime/src/service*.ts", "packages/runtime/src/local-protocol.ts", "packages/runtime/test/{service,inference}*.test.ts"],
        checks: ["inference-tests", "service-tests", "process-steady-state", "typecheck"],
        dependsOn: ["native-host"],
      },
      {
        id: "knowledge-integration",
        title: "Use exact token planning and shared inference for Knowledge",
        files: ["packages/runtime/src/{knowledge,semantic,server}*.ts", "packages/runtime/src/routes.ts", "packages/runtime/test/{client,semantic-index,inference}*.test.ts", "tests/cli-reporting.test.ts"],
        checks: ["semantic-index-tests", "runtime-client-tests", "service-tests", "typecheck"],
        dependsOn: ["service-coordinator"],
      },
      {
        id: "remove-project-inference",
        title: "Delete project-owned model workers and compatibility paths",
        files: ["packages/engine/src/**", "crates/opencanon-engine/src/**", "packages/runtime/src/{knowledge,semantic,server}*.ts", "scripts/build-opencanon-runtime.ts"],
        checks: ["engine-tests", "inference-tests", "runtime-client-tests", "process-steady-state", "typecheck"],
        dependsOn: ["knowledge-integration"],
      },
      {
        id: "observability-and-doctor",
        title: "Expose inference lifecycle, capacity, and actionable failures",
        files: ["packages/runtime/src/{doctor,inference,service}*.ts", "packages/runtime/test/{client,inference,service}*.test.ts", "tests/validator-runtime.test.ts"],
        checks: ["doctor-tests", "inference-tests", "service-tests", "runtime-client-tests"],
        dependsOn: ["remove-project-inference"],
      },
      {
        id: "representative-proof",
        title: "Prove shared inference on representative projects",
        files: ["opencanon/changes/service-owned-inference.ts", "package.json", "scripts/check-test-processes.ts"],
        checks: ["inference-tests", "engine-tests", "semantic-index-tests", "service-tests", "runtime-client-tests", "project-validation", "project-doctor", "process-steady-state", "full-ci"],
        dependsOn: ["observability-and-doctor"],
      },
    ],
    checks: [
      { id: "canon-render", kind: "command", command: "npm run opencanon -- canon render specs --dry-run" },
      { id: "contracts-tests", kind: "test", target: "tests/contracts.test.ts" },
      { id: "inference-tests", kind: "command", command: "npm run check:inference" },
      { id: "engine-tests", kind: "command", command: "npm run check:engine" },
      { id: "semantic-index-tests", kind: "test", target: "packages/runtime/test/semantic-index.test.ts" },
      { id: "service-tests", kind: "test", target: "packages/runtime/test/service.test.ts" },
      { id: "runtime-client-tests", kind: "test", target: "packages/runtime/test/client.test.ts" },
      { id: "doctor-tests", kind: "test", target: "tests/validator-runtime.test.ts" },
      { id: "typecheck", kind: "command", command: "npm run check:types" },
      { id: "project-validation", kind: "command", command: "npm run opencanon -- validate --changed" },
      { id: "project-doctor", kind: "doctor" },
      { id: "process-steady-state", kind: "command", command: "node scripts/check-test-processes.ts" },
      { id: "full-ci", kind: "command", command: "npm run check:ci", timeoutMs: 10 * 60 * 1000 },
    ],
    render: { kind: "none" },
  }),
];
